
[.preface]
== Introduction

A statement of measurement uncertainty is indispensable in judging the fitness for purpose of a measured quantity value. At the greengrocery store the customer would be content if, when buying a kilogram of fruit, the scales gave a value within, say, 2 grams of the fruit's actual weight. However, the dimensions of components of the gyroscopes within the inertial navigation systems of commercial aircraft are checked by measurement to parts in a million for correct functioning.

Measurement uncertainty is a general concept associated with any measurement and can be used in professional decision processes as well as judging attributes in many domains, both theoretical and experimental. As the tolerances applied in industrial production become more demanding, the role of measurement uncertainty becomes more important when assessing conformity to these tolerances. Measurement uncertainty plays a central role in quality assessment and quality standards.

Measurement is present in almost every human activity, including but not limited to industrial, commercial, scientific, healthcare, safety and environmental. Measurement helps the decision process in all these activities. Measurement uncertainty enables users of a measured quantity value to make comparisons, in the context of conformity assessment, to obtain the probability of making an incorrect decision based on the measurement, and to manage the consequential risks.

This document serves as an introduction to measurement uncertainty, the GUM and the related documents indicated in the Foreword. A probabilistic basis for uncertainty evaluation is used. <<cls_A>> gives acronyms and initialisms used in this document.

In future editions of JCGM 200 (VIM) it is intended to make a clear distinction between the use of the term _error_ as a quantity and as a quantity value. The same statement applies to the term indication. In the current document such a distinction is made. JCGM 200:2008 does not distinguish explicitly between these uses.
