== Measurement uncertainty in conformity assessment

[[scls_8-1]]
=== {blank}

Conformity assessment is an area of importance in manufacturing quality control, legal metrology, and in the maintenance of health and safety. In the industrial inspection of manufactured parts, decisions are made concerning the compatibility of the parts with the design specification. Similar issues arise in the context of regulation (relating to emissions, radiation, drugs, doping control, etc.) concerning whether stipulated limits for true quantity values have been surpassed. Guidance is provided in JCGM 106 <<bipm_role>>. Also see reference <<IEC2007>>.


=== {blank}

Measurement is intrinsic to conformity assessment in deciding whether the output quantity, or measurand, conforms to a specified requirement. For a single quantity, such a requirement typically takes the form of specification limits that define an interval of permissible quantity values. In the absence of uncertainty, a measured quantity value lying within this interval is said to be conforming, and non-conforming otherwise. The influence of measurement uncertainty on the inspection process necessitates a balance of risks between producers and consumers.


[[scls_8-3]]
=== {blank}

The possible values of a quantity stem:[ii(Y)] of interest are represented by a probability distribution. The probability that stem:[ii(Y)] conforms to specification can be calculated, given this probability distribution and the specification limits.


=== {blank}

Because of the incomplete knowledge of the quantity stem:[ii(Y)] (as encoded in its probability distribution), there is a risk of a mistaken decision in deciding conformity to specification. Such mistaken decisions are of two types: a quantity accepted as conforming might actually be non-conforming, and a quantity rejected as non-conforming might actually conform. The related risks correspond, respectively, to _consumer's risk_ and _producer's risk_ (see JCGM 106).


[[scls_8-5]]
=== {blank}

By defining an _acceptance interval_ of acceptable measured quantity values, the risks of a mistaken decision concerning acceptance or rejection can be balanced so as to minimize the costs associated with these decisions <<ISO10576-1>>. The problem of calculating the conformity probability and the probabilities of the two types of mistaken decision, given the probability distribution, the specification limits, and the limits of the acceptance interval is addressed in JCGM 106. The choice of acceptance interval limits is a matter that depends on the implications of these mistaken decisions.


=== {blank}

Although the probability distribution in <<scls_8-3>> to <<scls_8-5>> is general, the treatment is then specialized in JCGM 106 to the most important case in practice, namely, when the probability distribution is Gaussian.
