= Traceability Statements -- References to the JCTLM
:edition:
:revdate:
:language: en
:docnumber: JCTLM_EXE_15-03
:doctype: policy
:fullname:
:title-en: Traceability Statements -- References to the JCTLM
:committee-en: Joint Committee for Traceability in Laboratory Medicine
:committee-fr: Comité commun pour la traçabilité en médecine de laboratoire
:committee-acronym: JCTLM
:mn-document-class: bipm
:mn-output-extensions: xml,html,pdf,rxl
:imagesdir: images
:local-cache-only:
:data-uri-image:
:authorizer: JCTLM Executive

== Summary

This document provides advice to manufacturers and others on the appropriate manner to make reference to JCTLM-listing of reference materials, methods and services in any documentation in which information on metrological traceability is included.


== Preamble

One of the primary activities of the JCTLM is to maintain a database of higher order reference materials, reference methods and reference measurement services (materials, methods and services). The purpose of this database is to provide a listing of the reference materials, methods and services which have been reviewed and found to meet the requirements of the relevant harmonized standards (see https://www.bipm.org/utils/common/pdf/JCTLM/JCTLM-framework.pdf) for use at the top of traceability chains for in-vitro diagnostic assays. It is also the purpose of the JCTLM to promote and support the implementation of metrological traceability.

The JCTLM Executive Committee believes that when reference materials, methods or services listed in the JCTLM Database, have been used appropriately to establish traceable measurement results, there is benefit in including this information in manufacturers’ metrological traceability statements or in other relevant manufacturers’ documents. The aim of these references would be to provide purchasers of kits assurance of the quality of the highest order metrological items referred to in the traceability chain for their test kit.

Traceability statements are also made for values assigned to other materials such as controls and quality assurance (proficiency testing) material. Reference to the JCTLM-listing of reference materials, methods and services would provide important information for users of these products.

This document has been developed to provide advice to manufacturers and others in the appropriate manner to make reference to JCTLM-listing of reference materials, methods and services in any documentation in which information on metrological traceability is provided.


== Principles

A traceability statement will include reference to a material and/or method to which the results are traceable. The principle of referring to the JCTLM-listing of these elements is to clearly indicate that the material or method is currently listed on the database, or was listed a time relevant to the procedures described in the statement. The material or method should be clearly identified by name and source with an additional note indicating JCTLM-listing. The reference to the JCTLM must be specifically related to the identity of the material or method. With regard to listed methods, a clear indication should be made as to whether the analyses using the method were performed by a JCTLM-listed reference measurement service provider or in another facility.

The terminology used to describe the material, method or service should be sufficiently close to that used in the JCTLM database to avoid any possibility of confusion as to the identity of the material, method or service.

The use of the Term '`JCTLM`' should not be used in any manner which suggests that other procedures or materials used in establishing the traceability chain, or the entirety of the traceability chain are in any way endorsed or supported by the JCTLM.


== Examples

=== References to materials

As a sentence:: Measurement results are traceable to SRM 912a (NIST, USA). This material is/was listed on the JCTLM database.

As a phrase:: Measurement results are traceable to SRM 912a, a JCTLM-listed reference material.


=== References to methods

As a Sentence:: The values generated by the method are traceable to the IFCC reference method. This reference method was listed on the JCTLM database at the time of method comparison and calibration performed by a JCTLM-listed Reference Measurement Service Provider.

As a phrase:: Traceable to the IFCC reference method (JCTLM-listed).

NOTE: A reference to a method alone is sufficient only in cases where the method defines the measurand. Examples of this are the liver enzymes AST and ALT. Where a method is calibrated using a material, the material should also be identified.

NOTE: The method should be supported by a statement indicating whether the testing was performed by a JCTLM-listed reference measurement service provider or other facility. Identification of the service provider is desirable, but optional.


=== References to methods and materials

As a Sentence:: The values assigned to the calibrators are traceable to SRM 914a using Isotope Dilution Mass Spectrometry. The reference material and method are JCTLM-listed and the method was performed by a JCTLM-listed Reference Measurement Service Provider.

As a phrase:: Traceable to SRM 914a (NIST, USA) using Isotope Dilution Mass Spectrometry (JCTLM-listed method) performed by a JCTLM-listed Reference Measurement Service Provider.


== Unacceptable Statements

Any statement which conveys, or appears to convey approval by the JCTLM of any other facet of the traceability statement other than the identity of the material, method or measurement service is unacceptable.

It is acceptable to note that a JCTLM-listed material, procedure or measurement service was not available at the time of calibrator value assignment. This may be done in order to assure customers that an opportunity for higher-order traceability has not been overlooked.
