
[[cls_1]]
== Scope

[[scls_1-1]]
=== {blank}

This _Guide_ establishes general rules for evaluating and expressing uncertainty in measurement thatcan be followed at various levels of accuracy and in many fields -- from the shop floor to fundamental research. Therefore, the principles of this _Guide_ are intended to be applicable to a broad spectrum of measurements, including those required for:

* maintaining quality control and quality assurance in production; complying with and enforcing laws and regulations;
* conducting basic research, and applied research and development, in science and engineering;
* calibrating standards and instruments and performing tests throughout a national measurement system in order to achieve traceability to national standards;
* developing, maintaining, and comparing international and national physical reference standards, including reference materials.


[[scls_1-2]]
=== {blank}

This _Guide_ is primarily concerned with the expression of uncertainty in the measurement of a well-defined physical quantity -- the measurand -- that can be characterized by an essentially unique value. If the phenomenon of interest can be represented only as a distribution of values or is dependent on one or more parameters, such as time, then the measurands required for its description are the set of quantities describing that distribution or that dependence.


[[scls_1-3]]
=== {blank}

This _Guide_ is also applicable to evaluating and expressing the uncertainty associated with the conceptual design and theoretical analysis of experiments, methods of measurement, and complex components and systems. Because a measurement result and its uncertainty may be conceptual and based entirely on hypothetical data, the term "result of a measurement" as used in this _Guide_ should be interpreted in this broader context.


[[scls_1-4]]
=== {blank}

This _Guide_ provides general rules for evaluating and expressing uncertainty in measurement rather than detailed, technology-specific instructions. Further, it does not discuss how the uncertainty of a particular measurement result, once evaluated, may be used for different purposes, for example, to draw conclusions about the compatibility of that result with other similar results, to establish tolerance limits in a manufacturing process, or to decide if a certain course of action may be safely undertaken. It may therefore be necessary to develop particular standards based on this _Guide_ that deal with the problems peculiar to specific fields of measurement or with the various uses of quantitative expressions of uncertainty. footnote:[*Footnote to the 2008 version:* Since the initial publication of this _Guide_, several general and specific applications documents derived from this document have been published. For information purposes, nonexhaustive compilations of these documents can be found on http://www.bipm.org/en/committees/jc/jcgm/wg1_bibliography.html.]These standards may be simplified versions of this _Guide_ but should include the detail that is appropriate to the level of accuracy and complexity of the measurements and uses addressed.

NOTE: There may be situations in which the concept of uncertainty of measurement is believed not to be fully applicable, such as when the precision of a test method is determined (see Reference <<ISO1986>> for example).
