
[[cls_1]]
== Scope

The Joint Committee for Guides in Metrology (JCGM) has prepared this document to promote the sound evaluation of measurement uncertainty through the use of the GUM (see <<cls_2>>) and to provide an introduction to the GUM Supplements and other documents JCGM is producing: JCGM 101:2008 (see <<cls_2>>) and references <<bipm_app>>, <<bipm_concepts>>, <<bipm_supp2>>, <<bipm_supp3>>, <<bipm_role>>.

As in the GUM, this document is primarily concerned with the expression of uncertainty relating to the measurement of a well-defined quantity -- _the measurand_ <<JCGM2002008,clause=(VIM) 2.3>> -- that can be characterized by an _essentially unique true value_ <<JCGM2002008,clause=(VIM) 2.11 NOTE 3>>. The GUM provides a rationale for not using the term 'true', but this term will be kept in this document when there is otherwise a possibility for ambiguity or confusion.

The purpose of the GUM Supplements and the other documents produced by the JCGM is to help with the interpretation of the GUM and enhance its application. The GUM Supplements and the other documents are together intended to have a scope that is considerably broader than that of the GUM.

This document introduces measurement uncertainty, the GUM, and the GUM Supplements and other documents that support the GUM. It is directed predominantly at the measurement of quantities that can be characterized by continuous variables such as length, temperature, time, and amount of substance.

This introductory document is aimed at the following, including but not limited to

* scientific activities and disciplines in general,
* industrial activities and disciplines in general,
* calibration, testing and inspection laboratories in industry, and laboratories such as those concerned with health, safety and environment, and
* evaluation and accreditation bodies.

It is hoped that it will also be useful to designers, because a product specification that takes better account of inspection requirements (and the associated measurement) can result in less stringent manufacturing requirements. It is also directed at academia, with the hope that more university departments will include modules on measurement uncertainty evaluation in their courses. As a result, a new generation of students would be better armed to understand and provide uncertainty statements associated with measured quantity values, and thus gain an improved appreciation of measurement.

This introductory document, the GUM, the GUM Supplements and the other documents should be used in conjunction with the 'International Vocabulary of Metrology -- Basic and general concepts and associated terms' and all three parts of ISO 3534 cited in <<cls_2>>, which define statistical terms (used in statistics and probability, including applied statistics and design of experiments), and express them in a conceptual framework in accordance with normative terminology practice. The last consideration relates to the fact that the theoretical background of evaluation of measurement data and evaluation of the uncertainty of measurement is supported by mathematical statistics and probability.
