
[[cls_3]]
== What is measurement uncertainty?

=== {blank}

The purpose of measurement is to provide information about a quantity of interest -- a _measurand_ <<JCGM2002008,clause=(VIM) 2.3>>. The measurand might be the volume of a vessel, the potential difference between the terminals of a battery, or the mass concentration of lead in a flask of water.


[[scls_3-2]]
=== {blank}

No measurement is exact. When a quantity is measured, the outcome depends on the measuring system <<JCGM2002008,clause=(VIM) 3.2>>, the measurement procedure, the skill of the operator, the environment, and other effects <<Bell1999>>. Even if the quantity were to be measured several times, in the same way and in the same circumstances, a different _indication value_ <<JCGM2002008,clause=(VIM) 4.1>> (measured quantity value <<JCGM2002008,clause=(VIM) 2.10>>) would in general be obtained each time, assuming that the measuring system has sufficient resolution to distinguish between the indication values. Such indication values are regarded as instances of an indication quantity.


=== {blank}

The _dispersion_ of the indication values would relate to how well the measurement is made. Their average would provide an _estimate_ <<ISO_3534-1,clause=1.31>> of the _true quantity value_ <<JCGM2002008,clause=(VIM) 2.11>> that generally would be more reliable than an individual indication value. The dispersion and the number of indication values would provide information relating to the average value as an estimate of the true quantity value. However, this information would not generally be adequate.


=== {blank}

The measuring system may provide indication values that are not dispersed about the true quantity value, but about some value offset from it. The difference between the offset value and the true quantity value is sometimes called the _systematic error value_ <<JCGM2002008,clause=(VIM) 2.17>>. Take the domestic bathroom scales. Suppose they are not set to show zero when there is nobody on the scales, but to show some value offset from zero. Then, no matter how many times the person's mass were re-measured, the effect of this offset would be inherently present in the average of the indication values. In general, a systematic error, regarded as a quantity, is a component of error that remains constant or depends in a specific manner on some other quantity.


=== {blank}

There are two types of measurement error quantity, _systematic and random_ <<JCGM2002008,clause=(VIM) 2.19>>. A systematic error (an estimate of which is known as a _measurement bias_ <<JCGM2002008,clause=(VIM) 2.18>>) is associated with the fact that a measured quantity value contains an offset. A random error is associated with the fact that when a measurement is repeated it will generally provide a measured quantity value that is different from the previous value. It is random in that the next measured quantity value cannot be predicted exactly from previous such values. (If a prediction were possible, allowance for the effect could be made!) In general, there can be a number of contributions to each type of error.


=== {blank}

A challenge in measurement is how best to express what is learned about the measurand. Expression of systematic and random error values relating to the measurement, along with a best estimate of the measurand, is one approach that was often used prior to the introduction of the GUM. The GUM provided a different way of thinking about measurement, in particular about how to express the perceived quality of the result of a measurement. Rather than express the result of a measurement by providing a best estimate of the measurand, along with information about systematic and random error values (in the form of an 'error analysis'), the GUM approach is to express the result of a measurement as a best estimate of the measurand, along with an associated _measurement uncertainty_.


=== {blank}

One of the basic premises of the GUM approach is that it is possible to characterize the quality of a measurement by accounting for both systematic and random errors on a comparable footing, and a method is provided for doing that (see <<scls_7-2>>). This method refines the information previously provided in an 'error analysis', and puts it on a probabilistic basis through the concept of measurement uncertainty.


[[scls_3-8]]
=== {blank}

Another basic premise of the GUM approach is that it is not possible to state how well the essentially unique true value of the measurand is known, but only how well it is believed to be known. Measurement uncertainty can therefore be described as a measure of how well one believes one knows the essentially unique true value of the measurand. This uncertainty reflects the incomplete knowledge of the measurand. The notion of 'belief' is an important one, since it moves metrology into a realm where results of measurement need to be considered and quantified in terms of _probabilities_ that express degrees of belief.

[[scls_3-9]]
=== {blank}

The above discussion concerns the direct measurement of a quantity, which incidentally occurs rarely. The bathroom scales may convert a measured extension of a spring into an estimate of the measurand, the mass of the person on the scales. The particular relationship between extension and mass is determined by the _calibration_ <<JCGM2002008,clause=(VIM) 2.39>> of the scales.


=== {blank}

A relationship such as that in <<scls_3-9>> constitutes a rule for converting a quantity value into the corresponding value of the measurand. The rule is usually known as a _measurement model_ <<JCGM2002008,clause=(VIM) 2.48>> or simply a model. There are many types of measurement in practice and therefore many rules or models. Even for one particular type of measurement there may well be more than one model. A simple model (for example a proportional rule, where the mass is proportional to the extension of the spring) might be sufficient for everyday domestic use. Alternatively, a more sophisticated model of a weighing, involving additional effects such as air buoyancy, is capable of delivering better results for industrial or scientific purposes. In general there are often several different quantities, for example temperature, humidity and displacement, that contribute to the definition of the measurand, and that need to be measured.


=== {blank}

Correction terms should be included in the model when the conditions of measurement are not exactly as stipulated. These terms correspond to systematic error values <<JCGM2002008,clause=(VIM) 2.17>>. Given an estimate of a correction term, the relevant quantity should be corrected by this estimate <<JCGM1002008,clause=(GUM) 3.2.4>>. There will be an uncertainty associated with the estimate, even if the estimate is zero, as is often the case. Instances of systematic errors arise in height measurement, when the alignment of the measuring instrument is not perfectly vertical, and the ambient temperature is different from that prescribed. Neither the alignment of the instrument nor the ambient temperature is specified exactly, but information concerning these effects is available, for example the lack of alignment is at most 0:001 and the ambient temperature at the time of measurement differs from that stipulated by at most 2 °C.


=== {blank}

A quantity can depend on time, for instance a radionuclide decaying at a particular rate. Such an effect should be incorporated into the model to yield a measurand corresponding to a measurement at a given time.


=== {blank}

As well as raw data representing measured quantity values, there is another form of data that is frequently needed in a model. Some such data relate to quantities representing physical constants, each of which is known imperfectly. Examples are material constants such as modulus of elasticity and specific heat. There are often other relevant data given in reference books, calibration certificates, etc., regarded as estimates of further quantities.


=== {blank}

The items required by a model to define a measurand are known as _input quantities in a measurement model_ <<JCGM2002008,clause=(VIM) 2.50>>. The rule or model is often referred to as a functional relationship <<JCGM1002008,clause=(GUM) 4.1>>. The _output quantity in a measurement model_ <<JCGM2002008,clause=(VIM) 2.51>> is the measurand.


=== {blank}

Formally, the output quantity, denoted by stem:[ii(Y)], about which information is required, is often related to input quantities, denoted by stem:[ii(X)_1,..., ii(X)_{ii(N)}], about which information is available, by a measurement model <<JCGM1002008,clause=(GUM) 4.1.1>> in the form of a measurement function <<JCGM2002008,clause=(VIM) 2.49>>

[stem]
++++
ii(Y) = f(ii(X)_1,..., ii(X)_{ii(N)} ).
++++


[[scls_3-16]]
=== {blank}

A general expression for a measurement model <<JCGM2002008,clause=2.48 note 1>> is

[[eq2]]
[stem]
++++
h(ii(Y),ii(X)_1,...,ii(X)_{ii(N)}) = 0.
++++


It is taken that a procedure exists for calculating stem:[ii(Y)] given stem:[ii(X)_1,..., ii(X)_{ii(N)}] in <<eq2>> and that stem:[ii(Y)] is uniquely defined by this equation.


[[scls_3-17]]
=== {blank}

The true values of the input quantities stem:[ii(X)_1,...,ii(X)_{ii(N)}] are unknown. In the approach advocated, stem:[ii(X)_1,..., ii(X)_{ii(N)}] are characterized by probability distributions <<JCGM1002008,clause=(GUM) 3.3.5>>, <<ISO_3534-1,clause=2.11>> and treated mathematically as random variables <<ISO_3534-1,clause=2.10>>. These distributions describe the respective probabilities of their true values lying in different intervals, and are assigned based on available knowledge concerning stem:[ii(X)_1,..., ii(X)_{ii(N)}]. Sometimes, some or all of stem:[ii(X)_1,..., ii(X)_{ii(N)}] are interrelated and the relevant distributions, which are known as _joint_, apply to these quantities taken together. The following considerations, which largely apply to unrelated (independent) quantities, can be extended to interrelated quantities.


[[scls_3-18]]
=== {blank}

Consider estimates stem:[x_1,..., x_{ii(N)}], respectively, of the input quantities stem:[ii(X)_1,..., ii(X)_{ii(N)}], obtained from certificates and reports, manufacturers' specifications, the analysis of measurement data, and so on. The probability distributions characterizing stem:[ii(X)_1,..., ii(X)_{ii(N)}] are chosen such that the estimates stem:[x_1,..., x_{ii(N)}], respectively, are the _expectations_ <<JCGM1012008,clause=3.6>>, <<ISO_3534-1,clause=2.12>> of stem:[ii(X)_1,..., ii(X)_{ii(N)}] . Moreover, for the ith input quantity, consider a so-called _standard uncertainty_ <<JCGM2002008,clause=(VIM) 2.30>>, given the symbol stem:[u(x_i)], defined as the standard deviation <<JCGM1012008,clause=3.8>>, <<ISO_3534-1,clause=2.37>> of the input quantity stem:[ii(X)_i]. This standard uncertainty is said to be _associated_ with the (corresponding) estimate stem:[x_i]. The estimate stem:[x_i] is best in the sense that stem:[u^2(x_i)] is smaller than the expected squared difference of stem:[ii(X)_i] from any other value.


[[scls_3-19]]
=== {blank}

The use of available knowledge to establish a probability distribution to characterize each quantity of interest applies to the stem:[ii(X)_i] and also to stem:[ii(Y)]. In the latter case, the characterizing probability distribution for stem:[ii(Y)] is determined by the functional relationship <<eq1,(1)>> or <<eq2,(2)>> together with the probability distributions for the stem:[ii(X)_i]. The determination of the probability distribution for stem:[ii(Y)] from this information is known as the _propagation of distributions_ <<JCGM1012008,clause=5.2>>.


[[scls_3-20]]
=== {blank}

Prior knowledge about the true value of the output quantity stem:[ii(Y)] can also be considered. For the domestic bathroom scales, the fact that the person's mass is positive, and that it is the mass of a person, rather than that of a motor car, that is being measured, both constitute prior knowledge about the possible values of the measurand in this example. Such additional information can be used to provide a probability distribution for stem:[ii(Y)] that can give a smaller standard deviation for stem:[ii(Y)] and hence a smaller standard uncertainty associated with the estimate of stem:[ii(Y)] <<Bernardo2000>>, <<Elster>>, <<Possolo2007>>.
