= Guidelines for the monitoring and reporting of the operation of quality systems by RMOs
:edition: 3
:copyright-year: 2010
:revdate: 2010-10
:language: en
:docnumber: CIPM MRA-G-02
:title-en: Guidelines for the monitoring and reporting of the operation of quality systems by RMOs
:title-fr:
:doctype: cipm-mra
:committee-en:
:committee-fr:
:committee-acronym:
:supersedes-date:
:supersedes-draft:
:docstage: in-force
:docsubstage: 60
:imagesdir: images
:mn-document-class: bipm
:mn-output-extensions: xml,html,pdf,rxl
:local-cache-only:
:data-uri-image:

== Introduction

A central component of the CIPM MRA requires that signatory NMIs establish and maintain a Quality System (QS). Unlike the CMC situation, however, the CIPM MRA does not explicitly specify how signatory NMIs review, gain confidence and accept each other's quality systems.

With regard to the establishment of a QS, the CIPM MRA provides for the following methods:

. _an NMI that chooses for its calibration and measurement services a quality system that meets the requirements of ISO Guide 25 or equivalent for an NMI, assessed by an accreditation body fulfilling the requirements of ISO Guide 58, declares its calibration measurement capabilities and submits them to the local RMO for review and transmission to the Joint Committee for analysis and inclusion in Appendix C._
. _an NMI that chooses to use a different way of assuring quality or chooses a different quality system, or ISO Guide 25 without third-party assessment, for its calibration and measurement services declares its calibration and measurement capabilities and submits them to the local RMO for review and transmission to the Joint Committee for analysis and inclusion in Appendix C._

_Demonstration of competence and capability may require visits and examination of procedures by an NMI and/or by peers selected by the local RMO._

== Review Guidelines

Each RMOs should have an open process in place for the monitoring and review of the QS footnote:[In this document, QS means a quality system that meets the requirements of ISO/IEC 17025 or equivalent or a different way of assuring quality or a different quality system, as described in the MRA.] of each of their member NMIs and DIs and to to report on their acceptance or otherwise to the JCRB. The process followed for the review is decided by each RMO and it shall satisfy at least the following requirements.

* The review processes should include the presentation of each member NMIs and DIs' QS to a panel of experts. The initial and periodic presentations of the QS of DI to the corresponding QS review panel must be done directly by the responsible person of the DI and not through its NMI. In the same sense, the QS annual reports must also be prepared and submitted directly by the DI.
* The RMO must satisfy itself through its review process that the QS operated by the NMI or DI has an effective and durable system in place for dealing with corrective actions, non-conforming work and complaints.
* The NMIs should submit a full description of their QS to the RMO, for its calibration and measurement service. Minimum features to be included are:
+
--
[align=left]
organogram of the NMI ; +
quality system management mechanisms ; +
detailed table of contents of the quality manual; +
list of administrative and technical procedures; +
table of cross references between ISO/IEC17025 and the quality documentation of the NMI; +
list of calibration capabilities covered by the quality system; +
customer complaints – process employed and statistics; +
non conforming work – process employed & corrective actions; +
report on internal audits ;

* status of management reviews.
--

* If considered necessary, the RMO may request that review visits by 'peers' be undertaken, in order that the NMI may demonstrate confidence and capability in their claimed CMCs. The NMI itself may request the review visits by peers. Where such visits take place, the RMO must ensure that the 'peers' have the necessary experience and are suitably qualified and independent.
* The RMO must have a process in place for the on-going monitoring of the QS of the NMIs. This process should aim to ensure that:

** the accreditation or self declaration continues to be valid;
** the QS continues to cover the declared CMCs;
** major extensions and modifications to QS (including changes to key staff) have been notified to the RMO;
** a general review of the QS is undertaken at a maximum interval of five years.

* In addition to the requirements of the QS, the review process may also take into account:

** RMO projects and activities ;
** other available knowledge and experience;participation in scientific and training activities, visits and consultation with technical experts from other RMOs.

== Requirements for the QS

The QS operated by the NMI should be:

* accredited to ISO/IEC 17025 for calibration laboratories or equivalent for an NMI, or
* self declared to ISO/IEC 17025 or a different quality system.

The QS should cover all declared CMCs

=== QS assessed by Accreditation Body

* The claimed CMC uncertainty must not be smaller than the accredited uncertainties documented in the scope of accreditation
* The NMI must submit the name of the accreditation body and the names of the technical assessors and the lead assessor who were involved in the assessment of the NMIs capabilities.
* The accreditation body should operate according to ISO/IEC 17011(draft) and should be a signatory to the ILAC MRA.

=== Self declared QS

* Where the QS is based on ISO/IEC 17025 the RMO must satisfy itself that the quality system complies with the standard.
* Where the QS is not based on ISO/IEC 17025 the following must be addressed:
* Organizational and Management requirements including:
** quality manual ;
** document control process ;
** contract review ;
** complaints ;
** control of non conforming work;
** corrective and preventative actions ;
** internal audits and management review.
* Technical requirements including:
** Personnel
** Accommodation and environment conditions
** Test and calibration methods and method validation
** Equipment
** Calibration and measurement traceability
** Assuring the quality of results
** Reporting of results
** Sampling and handling of items (where applicable).

== Report Guidelines

As part of the regular reports to the JCRB, the RMOs must provide annual summary reports on the status of the QS of the NMIs and DIs in their region,.

The report should include:

* summary of the RMO's QS review process;
* whether and when each member NMIs' QS was approved by the RMO (necessary details of each NMIs' QS status, e.g. path a, b, or c, can be provided meanwhile);
* major changes in the member NMIs' QS that may affect the validity of CMCs, like changes in key personnel, new installations or equipment, etc.
* other relevant information, which will help build inter-regional confidence (eg training courses/workshops on QS, exchange of information between NMIs on QS, interaction with other RMOs on QS)

== Periodic Reviews of the Quality Management Systems

The quality management systems implemented to support the calibration and measurement capabilities of the NMIs and DIs must undergo a full review with a period not longer than five years. The individual RMOs are responsible for this review, under the auspices of their respective quality system working groups.

This comprehensive periodic review includes examination of evidence for the continued validity and vitality of published CMCs.

In addition to the 5-year review of the supporting QMS, CMCs published in the KCDB undergo continual monitoring to ensure their validity. NMIs and DIs are responsible for demonstrating that they are maintaining quality systems, including regular review of their services. All DIs and NMIs with published CMCs submit annual quality reports to their RMOs which include full disclosure of any issues (e.g., departure of key staff, loss of facilities and equipment, poor performance in comparisons with other NMIs and DIs, etc.) that would affect published CMCs.

== List of Acronyms

CIPM MRA:: Mutual Recognition Arrangement
CMC:: Calibration and Measurement Capability
JCRB:: Joint Committee of the RMOs and the BIPM
NMI:: National Metrology Institute
QS:: Quality System
RMO:: Regional Metrology Organization

== Revision History

[%unnumbered]
|===
^a| Version number ^a| Date of Issue/Review ^a| Summary of change
| 2 | 2008-11-18 a| Initially approved as JCRB 10/8 (1c) +
Reformatted by JCRB Executive Secretary, November 2008
.2+| 3 | 2010-09-29 a| General review, new chapters 3 and 5. Approved by the JCRB.
| 2010-10-15 | Changes approved by CIPM.
|===
