= Measuring Conditions and Uncertainties for the Comparison and Calibration of National Dosimetric Standards at the BIPM
:edition: 1
:copyright-year: 2018
:revdate: 2018-12
:language: en
:docnumber: BIPM-2018/06
:title-en: Measuring Conditions and Uncertainties for the Comparison and Calibration of National Dosimetric Standards at the BIPM
:title-fr:
:doctype: rapport
:committee-en:
:committee-fr:
:committee-acronym:
:fullname: C. Kessler
:affiliation: 
:fullname_2: D.T. Burns
:affiliation_2: 
:supersedes-date:
:supersedes-draft: Rapport BIPM-2011/04
:docstage: in-force
:docsubstage: 60
:imagesdir: images
:mn-document-class: bipm
:mn-output-extensions: xml,html,pdf,rxl
:local-cache-only:
:data-uri-image:


.Abstract

Information is presented on the experimental conditions used in the x- and gamma-radiation beams at the BIPM for comparisons of national primary standards and calibrations of national secondary standards in terms of air kerma and absorbed dose to water, together with the uncertainties involved in the determination of these dosimetric quantities.

== Introduction

For each signatory of the Metre Convention and for a given type of measurement, the BIPM works with the National Metrology Institute (NMI) or a laboratory designated nationally for the purpose. For those laboratories that hold national primary standards, the BIPM compares these standards against the BIPM reference standards, either directly using the primary standards in the BIPM reference beams or indirectly through the calibration of transfer instruments by both the BIPM and the NMI. For those that do not hold primary standards, the BIPM calibrates secondary standards that are then normally used as national reference instruments. For this reason, the chambers should be instruments of good quality; in particular with respect to leakage current and both short- and long-term stability.

Comparisons, characterizations and calibrations of ionization chambers are performed at the BIPM in terms of:

* air kerma in the low- (including mammography) and medium-energy x-ray ranges and in ^60^Co gamma radiation;
* absorbed dose to water in medium-energy x-ray beams and in ^60^Co gamma radiation;

The present report documents the conditions of measurement at the BIPM, the values for the physical constants and correction factors, and the estimated uncertainties in the determination of the primary quantities and of calibration coefficients.

== General remarks

The reference plane is specified in terms of a distance from the radiation source or, in the case of low-energy x-rays, from the beam exit window. The reference point is the intersection of the beam axis with the reference plane.

For chamber types other than parallel plate, the chamber is positioned with its axis in the reference plane and with the stated point of measurement of the chamber at the reference point. For measurements in gamma radiation, the chamber is used with the build-up cap provided. The orientation of the chamber is such that the number, text or line inscribed on the stem faces the radiation source, unless a different orientation is indicated. Parallel-plate chambers are calibrated with the front surface of the chamber casing in the reference plane, unless a different surface is indicated on the chamber, and with the entrance window centred on the beam axis.

All chambers are irradiated for at least thirty minutes, with the appropriate polarizing potential applied to the outer electrode (wall or window), before any measurements are made. If the NMI applies a potential of a given polarity to the collecting electrode, the BIPM will apply the same potential with opposite polarity to the outer electrode.

The leakage current is normally measured before and after each set of measurements and a correction is applied, based on the mean value. A chamber for which the relative leakage current is high, and in particular for which the leakage is also variable, is unsuitable for use as a transfer instrument and might also be considered unsuitable for calibration. In the latter case, a study note is issued.

The irradiation facilities at the BIPM are temperature controlled (close to 20 °C) at the level of around 100 mK. For air-kerma measurements in ^60^Co, an additional passive enclosure is used to ensure temperature stability below 50 mK. The BIPM reference conditions for air temperature, pressure and relative humidity are stem:[T_0 = 293.15" K"], stem:[P_0 = 101.325" kPa"] and 50 %, respectively. As the relative humidity is controlled within the range 40 % to 55 %, no humidity correction is applied.

_Calibration of national standards_: No correction is applied for lack of saturation; the air-kerma rate or absorbed-dose-to-water rate is stated in the certificate. For thimble chamber types calibrated in gamma radiation and in airkerma for medium-energy x-rays, the radial non-uniformity correction for the BIPM beams is small and is stated in the certificate, although no correction factor is applied. For waterproof thimble chamber types calibrated in terms of absorbed dose to water in medium-energy x-rays, the correction factor at the reference depth will be similar at both laboratories and again no correction factor is applied. In low-energy x-rays, chambers of larger dimensions may be calibrated and the radial uniformity of the beam shows more variation from one laboratory to another. For these reasons, the appropriate correction factor is always applied.

_Comparisons of national standards_: This depends to some extent on the practice at the NMI and no general statement can be made; the measuring conditions adopted are clearly stated in the comparison report.

== Comparison and calibration in terms of air kerma (x-rays, ^60^Co)

The primary standard, transfer chamber or national reference standard is operated in air at the stated reference distance. The ionization current stem:[I] is determined under the BIPM reference conditions of air temperature, pressure and humidity. The value of stem:[I] is given by

[[eq1]]
[stem]
++++
I = I_("exp") (T/(T_0)) ((P_0)/P)
++++

where stem:[I_("exp")] is the ionization current measured at temperature stem:[T] (expressed in K) and pressure stem:[P] (expressed in kPa).

For a transfer chamber or national reference standard, the calibration coefficient stem:[N_K] is defined by the relation

[[eq2]]
[stem]
++++
N_K = dot(K)_("BIPM")//I,
++++

where stem:[dot(K)_("BIPM")] is the air-kerma rate at the reference point, measured with the BIPM standard.

Details of the conditions of measurement at the BIPM and the uncertainties in the determination of stem:[dot(K)_("BIPM")] are given in <<table1>> to <<table6>> for x-rays and in <<table7>> and <<table9>> for ^60^Co. In these tables, the relative standard uncertainties estimated by statistical methods (Type A) are denoted by stem:[s_("i")] and those estimated by other means (Type B) are denoted by stem:[u_("i")].

== Comparison and calibration in terms of absorbed dose to water (x-rays, ^60^Co)

_^60^Co gamma radiation_

When a primary standard is compared directly, the measuring conditions are stated clearly in the comparison report. For indirect comparisons and calibrations, the transfer chamber or national reference standard is placed in its waterproof sleeve (unless calibration of a waterproof chamber without a sleeve is requested) and positioned in the BIPM cubic water phantom of side length 30 cm. Its axis is placed in the reference plane, at the reference depth of 5 g cm^−2^ in water. This depth includes the window of the phantom (PMMA, 0.476 g cm^−2^) and is corrected for the change in water density with temperature. As well as correctly orienting the chamber, a reference mark on the sleeve (if used) is rotated so as to point towards the radiation source, unless a different orientation is indicated.

The calibration coefficient stem:[N_(D,w)] is determined using the relation

[[eq3]]
[stem]
++++
N_(D,w) = dot(D)_w//(I_wk_("win"))
++++

where:

stem:[dot(D)_w]:: is the absorbed dose rate to water at the reference point, measured using the BIPM standard at a depth of 5 g cm^−2^ in water;
stem:[I_w]:: is the ionization current measured using the chamber under the BIPM reference conditions of air temperature, pressure and humidity;
stem:[k_("win") = 0.9997]:: is a correction factor applied to stem:[I_w] for the non-equivalence with water of the PMMA window of the phantom (required because a similar factor is applied to the BIPM standard).

The conditions of measurement at the BIPM are given in <<table7>>. The physical constants and correction factors used in the ionometric determination of the absorbed dose rate to water at 5 g cm^−2^ are given in <<table9>> along with their estimated relative uncertainties.

_Medium-energy x-ray beams_

Only waterproof thimble chamber types are accepted and are measured without a waterproof sleeve. For indirect comparisons and calibrations, the transfer chamber or national reference standard is positioned in the BIPM cubic water phantom of side length 20 cm. Its axis is placed in the reference plane, at the reference depth of 2 g cm^−2^ in water. This depth includes the window of the phantom (PMMA, 0.200 g cm^−2^). Because of the shallow depth, no correction is required for the change in water density with temperature.

The calibration coefficient stem:[N_(D,w)] is determined using the relation

[[eq4]]
[stem]
++++
N_(D,w) = dot(D)_w//I_w,
++++

where:

stem:[dot(D)_w]:: is the absorbed dose rate to water at the reference point at a depth of 2 g cm^−2^ in the water phantom, determined by the BIPM standard;
stem:[I_w]:: is the ionization current measured using the chamber under the BIPM reference conditions of air temperature, pressure and humidity.

At the BIPM, the absorbed dose to water is derived from the air-kerma determination. The conditions of measurement are given in <<table4>>. The physical constants and correction factors used in the ionometric determination of air kerma and the factor for the conversion to absorbed dose to water are given in <<table5>> and their estimated relative uncertainties are given in <<table6>>.

== Use of calibration coefficients

A transfer chamber or national reference standard calibrated in the BIPM beam can be used in another beam, taking the calibration coefficients stem:[N_K] or stem:[N_(Dw)] to determine stem:[K] or stem:[D_w] in that beam, subject to certain provisions as listed below:

. The humidity conditions must not differ significantly from those of the calibration at the BIPM. If the relative humidity is outside the range 30 % to 70 %, the recommendations of ICRU Report 90 (ICRU 2016) should be used.
. The conditions of measurement must not differ significantly from those of the calibration at the BIPM. Otherwise, additional corrections may be necessary as described by Boutillon _et al_ (1993) and Boutillon (1996). Particular attention should be paid to:

** the radiation quality, particularly in the x-ray range;
** the distance from the source;
** the dimensions of the radiation field, in particular with regard to the radiation scattered by the stem and the support for calibration in terms of air kerma;
** the intensity of the ionization current, which can produce a change in the ion recombination;
** the radial non-uniformity of the beam over the cross-section of the chamber.

== Comparison and calibration uncertainties

The uncertainties associated with dosimetry measurements made at the BIPM are analysed in accordance with the _Guide to the Expression of Uncertainty in Measurement_ (JCGM 2008). The uncertainty budgets for the dosimetry standards are given in <<table3>>, <<table6>>, <<table8>> and <<table9>>. For comparisons, the BIPM standard uncertainties are combined with those associated with the primary or transfer chamber, taking correlation into account, to give the combined standard uncertainty of the comparison results. The detailed uncertainty budgets are given in the comparison report. For the calibration of national reference standards, the BIPM standard uncertainties are combined with the uncertainties associated with the chamber under calibration to give the combined standard uncertainty of the calibration coefficient. This value is given in the calibration certificate.

It is emphasized that the uncertainty associated with BIPM calibrations is a combined _standard_ uncertainty without the application of a coverage factor stem:[k]. This long-standing practice of not applying a coverage factor is maintained to facilitate the combination of the BIPM and NMI uncertainties and thus simplify the subsequent dissemination of the standard to the customers of the NMI.

The BIPM dosimetry measurements fulfil the criteria of Annex G.6.6 of JCGM (2008). In particular, for the purpose of calculating the expanded uncertainty for their end result at a specified level of confidence, an NMI can assume that the effective number of degrees of freedom for a BIPM calibration is sufficient to be able to use a coverage factor stem:[k = 2] for a level of confidence of approximately 95 %. Any exceptions are noted in the calibration certificate.

[align=center]
*Conditions of measurement at the BIPM*

[[table1]]
[cols="<,^,^"]
.X-rays (10 kV to 50 kV)
|===
| X-ray tube | W-anode | Mo-anode
| Distance between beryllium window of x-ray tube and reference plane of standard | 50 cm | 60 cm
| Beam diameter in reference plane | 8.4 cm | 10 cm
| Beryllium filtration | stem:[~~] 3.0 mm | 0.8 mm
|===

[%unnumbered]
[cols="<,^,^,^,^,^"]
|===
6+<h| Reference qualities W-anode x-ray tube footnote:[Recommended by Section I of the CCEMRI (1972, 1975).]
| X-ray tube voltage / kV | 10 | 30 | 25 | 50 (b) | 50 (a) footnote:[The more heavily-filtered of the two 50 kV radiation qualities.]
| Al filtration / mm | 0 | 0.208 | 0.372 | 1.008 | 3.989
| Al half-value layer / mm | 0.037 | 0.169 | 0.242 | 1.017 | 2.262
| stem:[bar(mu)//rho] footnote:f2[Mass attenuation coefficient for air.] / stem:[cm^2g^(-1)] | 14.84 | 3.66 | 2.60 | 0.75 | 0.38
| air-kerma rate / mGy s^−1^ | 1.00 | 1.00 | 1.00 | 1.00 | 1.00
|===

[%unnumbered]
[cols="<,^,^,^,^"]
|===
5+<h| Reference qualities Mo-anode x-ray tube footnote:[Endorsed by the CCRI (2011).]
| X-ray tube voltage / kV | 25 | 28 | 30 | 35
| Mo filtration / stem:[mu]m | 30 | 30 | 30 | 30
| Al half-value layer / mm | 0.277 | 0.310 | 0.329 | 0.365
| stem:[bar(mu)//rho] footnote:f2[] / stem:[cm^2g^(-1)] | 2.20 | 1.99 | 1.91 | 1.74
| air-kerma rate / mGy s^−1^ | 2.00 | 2.00 | 2.00 | 2.00
|===

[%unnumbered]
[cols="<,^,^,^,^,^,^,^"]
|===
8+<h| Reference qualities W-anode x-ray tube, Mo filter
| X-ray tube voltage / kV | 23 | 25 | 28 | 30 | 35 | 40 | 50
| Mo filtration / stem:[mu]m | 60 | 60 | 60 | 60 | 60 | 60 | 60
| Al half-value layer / mm | 0.332 | 0.342 | 0.355 | 0.364 | 0.388 | 0.417 | 0.489
| stem:[bar(mu)//rho] footnote:f2[] / stem:[cm^2g^(-1)] | 1.79 | 1.75 | 1.70 | 1.67 | 1.60 | 1.53 | 1.40
| air-kerma rate / mGy s^−1^ | 1.00 | 1.00 | 1.00 | 1.00 | 1.00 | 1.00 | 1.00
|===

[align=center]
*Physical constants and correction factors used in the BIPM determination of the air-kerma rate* footnote:[Details on the determination of the air-kerma rate are given in Boutillon _et al_ (1969); correction factors are described by Burns (2004) and Burns _et al_ (2009) for the W-anode qualities and by Kessler et al (2010) for the Mo-anode qualities.]

Dry air density stem:[(273.15" K, "101.325" kPa") = 1.2930" kg m"^(−3)]

stem:[W//e = 33.97" J C"^(−1)]

[[table2]]
[cols="^,<,^,^,^,^,^"]
.X-rays (10 kV to 50 kV)
|===
7+<h| W-anode x-ray tube
7+<| Measuring volume FAC-L-01: 1.2004 cm^3^
2+<| X-ray tube voltage / kV ^| 10 ^| 30 ^| 25 ^| 50 (b) ^| 50 (a)
7+<| _Correction factors_
| stem:[k_("sc")] | scattered radiation | 0.9962 | 0.9972 | 0.9973 | 0.9977 | 0.9979
| stem:[k_("fl")] | fluorescence | 0.9952 | 0.9971 | 0.9969 | 0.9980 | 0.9985
| stem:[k_("e")] | electron loss | 1.0000 | 1.0000 | 1.0000 | 1.0000 | 1.0000
| stem:[k_("ii")] | initial ionization footnote:f22[Combined values for stem:[k_("ii")] and stem:[k_("W")] adopted from January 2019 (Burns and Kessler 2018).] .2+.^| 0.9953 .2+.^| 0.9968 .2+.^| 0.9969 .2+.^| 0.9977 .2+.^| 0.9980
| stem:[k_("w")] | energy dependence of stem:[W_("air")] footnote:f22[]
| stem:[k_("s")] | saturation | 1.0006 | 1.0007 | 1.0007 | 1.0007 | 1.0007
| stem:[k_("pol")] | polarity | 1.0005 | 1.0005 | 1.0005 | 1.0005 | 1.0005
| stem:[k_("a")] | air attenuation footnote:f23[Values at 293.15 K and 101.325 kPa for an attenuation length of 10.0 cm.] | 1.1957 | 1.0451 | 1.0319 | 1.0091 | 1.0046
| stem:[k_("d")] | field distortion | 1.0000 | 1.0000 | 1.0000 | 1.0000 | 1.0000
| stem:[k_("dia")] | diaphragm | 0.9999 | 0.9995 | 0.9996 | 0.9989 | 0.9984
| stem:[k_("p")] | wall transmission | 1.0000 | 1.0000 | 1.0000 | 1.0000 | 1.0000
| stem:[k_("h")] | humidity | 0.998 | 0.998 | 0.998 | 0.998 | 0.998
| stem:[1-g] | radiative loss | 1.0000 | 1.0000 | 1.0000 | 1.0000 | 1.0000
|===

[%unnumbered]
[cols="^,<,^,^,^,^"]
|===
6+<h| Mo-anode x-ray tube
6+<| Measuring volume FAC-L-02: 1.2197 cm^3^
2+<| X-ray tube voltage / kV ^| 25 ^| 28 ^| 30 ^| 35
6+<| _Correction factors_
| stem:[k_("sc")] | scattered radiation | 0.9977 | 0.9977 | 0.9978 | 0.9978
| stem:[k_("fl")] | fluorescence | 0.9975 | 0.9976 | 0.9976 | 0.9977
| stem:[k_("e")] | electron loss | 1.0000 | 1.0000 | 1.0000 | 1.0000
| stem:[k_("ii")] | initial ionization footnote:f22[] .2+| 0.9968 .2+| 0.9968 .2+| 0.9969 .2+| 0.9969
| stem:[k_("w")] | energy dependence of stem:[W_("air")] footnote:f22[]
| stem:[k_("s")] | saturation | 1.0015 | 1.0015 | 1.0015 | 1.0015
| stem:[k_("pol")] | polarity | 1.0000 | 1.0000 | 1.0000 | 1.0000
| stem:[k_("a")] | air attenuation footnote:f23[] | 1.0269 | 1.0244 | 1.0233 | 1.0212
| stem:[k_("d")] | field distortion | 1.0000 | 1.0000 | 1.0000 | 1.0000
| stem:[k_("dia")] | diaphragm | 0.9996 | 0.9995 | 0.9995 | 0.9995
| stem:[k_("p")] | wall transmission | 1.0000 | 1.0000 | 1.0000 | 1.0000
| stem:[k_("h")] | humidity | 0.998 | 0.998 | 0.998 | 0.998
| stem:[1-g] | radiative loss | 1.0000 | 1.0000 | 1.0000 | 1.0000
|===

[%unnumbered]
[cols="^,<,^,^,^,^,^,^,^"]
|===
9+<h| W-anode x-ray tube, Mo filter
9+<| Measuring volume FAC-L-01: 1.2004 cm^3^
2+<| X-ray tube voltage / kV ^| 23 ^| 25 ^| 28 ^| 30 ^| 35 ^| 40 ^| 50
9+<| _Correction factors_
| stem:[k_("sc")] | scattered radiation | 0.9974 | 0.9974 | 0.9974 | 0.9974 | 0.9974 | 0.9974 | 0.9975
| stem:[k_("fl")] | Fluorescence | 0.9972 | 0.9972 | 0.9972 | 0.9972 | 0.9973 | 0.9973 | 0.9975
| stem:[k_("e")] | electron loss | 1.0000 | 1.0000 | 1.0000 | 1.0000 | 1.0000 | 1.0000 | 1.0000
| stem:[k_("ii")] | initial ionization footnote:f22[] .2+| 0.9971 .2+| 0.9971 .2+| 0.9971 .2+| 0.9971 .2+| 0.9972 .2+| 0.9972 .2+| 0.9973
| stem:[k_("w")] | energy dependence of stem:[W_("air")] footnote:f22[]
| stem:[k_("s")] | Saturation | 1.0006 | 1.0006 | 1.0006 | 1.0006 | 1.0006 | 1.0006 | 1.0006
| stem:[k_("pol")] | Polarity | 1.0005 | 1.0005 | 1.0005 | 1.0005 | 1.0005 | 1.0005 | 1.0005
| stem:[k_("a")] | air attenuation footnote:f23[] | 1.0218 | 1.0213 | 1.0208 | 1.0203 | 1.0195 | 1.0187 | 1.0170
| stem:[k_("d")] | field distortion | 1.0000 | 1.0000 | 1.0000 | 1.0000 | 1.0000 | 1.0000 | 1.0000
| stem:[k_("dia")] | diaphragm | 0.9995 | 0.9995 | 0.9995 | 0.9995 | 0.9995 | 0.9995 | 0.9994
| stem:[k_("p")] | wall transmission | 1.0000 | 1.0000 | 1.0000 | 1.0000 | 1.0000 | 1.0000 | 1.0000
| stem:[k_("h")] | Humidity | 0.998 | 0.998 | 0.998 | 0.998 | 0.998 | 0.998 | 0.998
| stem:[1-g] | radiative loss | 1.0000 | 1.0000 | 1.0000 | 1.0000 | 1.0000 | 1.0000 | 1.0000
|===

[align=center]
*Estimated relative standard uncertainties in the BIPM determination of the air-kerma rate*

[[table3]]
[cols="<,<,^,^"]
.X-rays (10 kV to 50 kV)
|===
.2+| Symbol .2+| Parameter / unit 2+a| stem:[10^2 xx] Relative standard uncertainty footnote:[stem:[s_i] represents the relative uncertainty estimated by statistical methods (Type A); stem:[u_i] represents the relative uncertainty estimated by other methods (Type B).]
^| stem:[s_("i")] ^| stem:[u_("i")]
4+| _Physical constants_
| stem:[rho_("a")] | dry air density (0°C, 101.325 kPa) / stem:["kg m"^(−3)] | – | 0.01
| stem:[W//e] | mean energy per charge / stem:["J C"^(−1)] | – | 0.35 footnote:f32[Value adopted from January 2019 (Burns and Kessler 2018).]
| stem:[g] | fraction of energy lost in radiative processes in air | – | 0.01
4+| _Correction factors_
| stem:[k_("sc")] | scattered radiation | – | 0.03
| stem:[k_("fl")] | fluorescence | – | 0.05
| stem:[k_("e")] | electron loss | – | 0.01
| stem:[k_("ii") k_("w")] | initial ionization and energy dependence of stem:[W_("air")] footnote:f32[] | – | 0.12
| stem:[k_("s")] | saturation | 0.01 | 0.01
| stem:[k_("pol")] | polarity | 0.01 | –
| stem:[k_("a")] | air attenuation | 0.02 | 0.01
| stem:[k_("d")] | field distortion | – | 0.07
| stem:[k_("dia")] | diaphragm | – | 0.03
| stem:[k_("p")] | wall transmission | 0.01 | –
| stem:[k_("h")] | humidity | – | 0.03
4+| _Measurement of_ stem:[I//nu]
| stem:[I] | ionization current (stem:[T], stem:[P], air compressibility) | 0.02 | 0.02
| stem:[nu] | volume | 0.03 | 0.05
| | positioning of standard | 0.01 | 0.01
4+| _Combined uncertainty of the BIPM determination of air-kerma rate_ ^(3)^
2+| quadratic summation ^| 0.05 ^| 0.39
2+| combined relative standard uncertainty 2+^| 0.39
|===

[align=center]
*Conditions of measurement at the BIPM*

Distance between focal spot and reference plane of standard: 120 cm

Beam diameter in the reference plane: 9.8 cm

Inherent filtration: stem:[~~] 3 mm Be

Reference depth for absorbed dose measurement: 2 g cm^−2^

[[table4]]
.X-rays (100 kV to 250 kV)
[cols="<,^,^,^,^"]
|===
5+<h| Reference qualities footnote:[Recommended by Section I of the CCEMRI (1972).]
| X-ray tube voltage / kV | 100 | 135 | 180 | 250
| Al filtration / mm | 3.431 | 2.228 | 2.228 | 2.228
| Cu filtration / mm | - | 0.232 | 0.485 | 1.570
| Al half-value layer / mm | 4.030 | - | - | -
| Cu half-value layer / mm | 0.149 | 0.489 | 0.977 | 2.484
| stem:[bar(mu)//rho] footnote:f2[] / stem:[cm^2g^(-1)] | 0.290 | 0.190 | 0.162 | 0.137
| air-kerma rate / mGy s^−1^ | 0.50 | 0.50 | 0.50 | 0.50
| Absorbed-dose-to-water rate / mGy s^−1^ | 0.59 | 0.71 | 0.72 | 0.68
|===

[align=center]
*Physical constants and correction factors used in the BIPM determination of the air-kerma rate footnote:[Details on the determination of the air-kerma rate are described by Boutillon (1978) and the re-evaluation of the correction factors is described by Burns _et al_ (2009).] and absorbed-dose-to-water rate footnote:f52[Details on the determination of the absorbed-dose-to-water rate are described by Burns (2017).] and conversion factor from air kerma to absorbed dose to water*

Dry air density stem:[(273.15" K, "101.325" kPa") = 1.2930" kg m"^(−3)]

stem:[W//e = 33.97" J C"^(−1)]

[[table5]]
[cols="^,<,^,^,^,^"]
.X-rays (100 kV to 250 kV)
|===
6+<h| W-anode x-ray tube
6+<| Measuring volume FAC-M-01: 4.6554 cm^3^
2+<| X-ray tube voltage / kV ^| 100 ^| 135 ^| 180 ^| 250
6+<| _Correction factors_
| stem:[k_("sc")] | scattered radiation | 0.9952 | 0.9959 | 0.9964 | 0.9974
| stem:[k_("fl")] | fluorescence | 0.9985 | 0.9992 | 0.9994 | 0.9999
| stem:[k_("e")] | electron loss | 1.0000 | 1.0015 | 1.0047 | 1.0085
| stem:[k_("ii")] | initial ionization footnote:f53[Combined values for stem:[k_("ii")] and stem:[k_("W")] adopted from June 2017 for absorbed dose to water and from January 2019 for air kerma (Burns and Kessler 2018).] .2+| 0.9980 .2+| 0.9980 .2+| 0.9981 .2+| 0.9986
| stem:[k_("w")] | energy dependence of stem:[W_("air")] footnote:f53[]
| stem:[k_("s")] | saturation | 1.0010 | 1.0010 | 1.0010 | 1.0010
| stem:[k_("pol")] | polarity | 1.0002 | 1.0002 | 1.0002 | 1.0002
| stem:[k_("a")] | air attenuation footnote:[Values at 293.15 K and 101.325 kPa for an attenuation length of 28.15 cm.] | 1.0099 | 1.0065 | 1.0055 | 1.0047
| stem:[k_("d")] | field distortion | 1.0000 | 1.0000 | 1.0000 | 1.0000
| stem:[k_("dia")] | diaphragm | 0.9995 | 0.9993 | 0.9991 | 0.9980
| stem:[k_("p")] | wall transmission | 1.0000 | 1.0000 | 0.9999 | 0.9988
| stem:[k_("h")] | humidity | 0.998 | 0.998 | 0.998 | 0.998
| stem:[1–g] | radiative loss | 0.9999 | 0.9999 | 0.9998 | 0.9997
6+<| _Conversion factor from air kerma to absorbed dose to water_
2+<| stem:[C_("w,air")] footnote:f52[] ^| 1.1840 | 1.4294 | 1.4429 | 1.3673
|===

[align=center]
*Estimated relative standard uncertainties in the BIPM determination of the air-kerma rate and absorbed-dose-to-water rate*

[[table6]]
[cols="<,<,^,^"]
.X-rays (100 kV to 250 kV)
|===
.2+| Symbol .2+| Parameter / unit 2+| stem:[10^2 xx] Relative standard uncertainty footnote:[stem:[s_i] represents the relative uncertainty estimated by statistical methods (Type A); stem:[u_i] represents the relative uncertainty estimated by other methods (Type B).]
^| stem:[s_("i")] ^| stem:[u_("i")]
4+| _Physical constants_
| stem:[rho_("a")] | dry air density (0°C, 101.325 kPa) / stem:["kg m"^(−3)] | – | 0.01
| stem:[W//e] | mean energy per charge / stem:["J C"^(−1)] | – | 0.35 footnote:f62[Value adopted from June 2017 for absorbed dose to water and from January 2019 for air kerma (Burns and Kessler 2018).]
| stem:[g] | fraction of energy lost in radiative processes in air | – | 0.01
4+| _Correction factors_
| stem:[k_("sc")] | scattered radiation | – | 0.03
| stem:[k_("fl")] | fluorescence | – | 0.03
| stem:[k_("e")] | electron loss | – | 0.05
| stem:[k_("ii") k_("w")] | initial ionization and energy dependence of stem:[W_("air")] footnote:f62[] | – | 0.05
| stem:[k_("s")] | saturation | 0.02 | 0.01
| stem:[k_("pol")] | polarity | 0.01 | –
| stem:[k_("a")] | air attenuation | 0.02 | 0.01
| stem:[k_("d")] | field distortion | – | 0.07
| stem:[k_("dia")] | diaphragm | – | 0.03
| stem:[k_("p")] | wall transmission | 0.01 | –
| stem:[k_("h")] | humidity | – | 0.03
4+| _Measurement of_ stem:[I//nu]
| stem:[I] | ionization current (stem:[T], stem:[P], air compressibility) | 0.02 | 0.02
| stem:[nu] | volume | 0.01 | 0.05
| | positioning of standard | 0.01 | 0.01
4+<| _Combined uncertainty of the BIPM determination of air-kerma rate_
2+<| quadratic summation ^| 0.04 ^| 0.37
2+<| combined relative standard uncertainty 2+^| 0.38
|===

[%unnumbered]
[cols="<,<,^,^"]
|===
.2+| Symbol .2+| Parameter / unit 2+| stem:[10^2 xx] Relative standard uncertainty footnote:[stem:[s_i] represents the relative uncertainty estimated by statistical methods (Type A); stem:[u_i] represents the relative uncertainty estimated by other methods (Type B).]
^| stem:[s_("i")] ^| stem:[u_("i")]

| stem:[K] | air-kerma rate / stem:["Gy s"^(−1)] | 0.04 | 0.37
| stem:[C_("w,air")] footnote:f62[] | conversion factor from air kerma to absorbed dose to water | 0.13 | 0.40
4+| _Combined uncertainty of the BIPM determination of absorbed-dose-to-water rate_
2+<| quadratic summation ^| 0.14 ^| 0.55
2+<| combined relative standard uncertainty 2+^| 0.56
|===

*Conditions of measurement at the BIPM*

[[table7]]
[cols="<,^"]
.^60^Co gamma radiation
|===
2+| Radiotherapy level
2+| _Measurement of air kerma and absorbed dose to water_
| Theratron source activity (2017-01-01) | stem:[~~] 65 TBq
| source type: solid discs of 20 mm diameter |
| distance from source centre to reference plane | 1 m
| beam section in the reference plane footnote:[The photon fluence rate at the centre of each side of the 10 cm stem:[xx] 10 cm field is 50 % of the photon fluence rate at the centre of the square.] | 10 cm stem:[xx] 10 cm
| reference depth for absorbed dose measurement | 5 g cm^−2^
|===

[align=center]
*Physical constants and correction factors used in the BIPM determination of the air-kerma rate footnote:[Details on the determination of air kerma are described by Boutillon _et al_ (1973), Burns (2006), Burns _et al_ (2007) and the re-evaluation of the standard is described in Burns and Kessler (2018).], and their estimated relative standard uncertainties*

[[table8]]
[cols="<,<,^,^,^,^"]
.^60^Co gamma radiation
|===
.2+| Symbol .2+| Parameter / unit 2.2+| Value 2+| stem:[10^2 xx] Relative standard uncertainty footnote:[stem:[s_i] represents the relative uncertainty estimated by statistical methods (Type A); stem:[u_i] represents the relative uncertainty estimated by other methods (Type B).]
^| stem:[s_("i")] ^| stem:[u_("i")]
6+| _Physical constants_
| stem:[rho_("a")] | dry air density (0°C, 101.325 kPa) / stem:["kg m"^(–3)] | 1.2930 | | – | 0.01
| stem:[(bar(mu_("en"))//rho)_("a,c")] | ratio of mass energy-absorption coefficients | 0.9989 | | 0.01 | 0.04
| stem:[s_("c,a")] | ratio of mass stopping powers | 0.9928 .2+| } | .2+| 0.08 footnote:[Uncertainty value for the product stem:[s_("c,a") W//e] adopted from January 2019 (Burns and Kessler 2018).]
| stem:[W//e] | mean energy per charge / stem:["J C"^(–1)] | 33.97 |
| stem:[g] | fraction of energy lost in radiative processes in air | 0.0031 | | – | 0.02
6+| _Correction factors_
| stem:[k_("g")] | re-absorption of radiative loss | 0.9996 | | – | 0.01
| stem:[k_("h")] | humidity | 0.9970 | | – | 0.03
| stem:[k_("s")] | saturation | 1.0022 | | 0.01 | 0.02
| stem:[k_("st")] | stem scattering | 1.0000 | | 0.01 | –
| stem:[k_("wall")] | wall attenuation and scattering | 1.0011 .2+| } | .2+| – footnote:f84[The uncertainties for kwall and kan are included in the determination of the effective volume (Burns et al 2007).]
| stem:[k_("an")] | axial non-uniformity | 1.0020 |
| stem:[k_("rn")] | radial non-uniformity | 1.0015 | | – | 0.02
6+| _Measurement of_ stem:[I//nu]
| stem:[nu] | effective volume / cm^3^ | 6.8855 footnote:[Standard CH6-1] | | – | 0.08 footnote:f84[]
| stem:[I] | ionization current (stem:[T], stem:[P], air compressibility) | | – | – | 0.02
| a| short-term reproducibility (including positioning and current measurement) footnote:[Over a period of 3 months. The long-term reproducibility over a period of 15 years, stem:[u_("rep")], is 0.0004.] | | – | 0.01 | –
6+a| _Combined uncertainty of the BIPM determination of air-kerma rate at 1 m_
4+| quadratic summation ^| 0.02 ^| 0.13
4+| combined relative standard uncertainty 2+^| 0.13
|===

[align=center]
*Physical constants and correction factors used in the BIPM ionometric determination of the absorbed-dose-to-water rate footnote:[Details on the determination of absorbed dose to water are described by Boutillon _et al_ (1993) and the re-evaluation of the standard is described by Burns and Kessler (2018).] at 5 g cm^−2^, and their estimated relative standard uncertainties*

[[table9]]
[cols="<,<,^,^,^"]
.^60^Co gamma radiation
|===
.2+| Symbol .2+| Parameter / unit .2+| Value 2+a| stem:[10^2 xx] Relative standard uncertainty footnote:[stem:[s_i] represents the relative uncertainty estimated by statistical methods (Type A); stem:[u_i] represents the relative uncertainty estimated by other methods (Type B).]
^| stem:[s_("i")] ^| stem:[u_("i")]

5+| _Physical constants_
| stem:[rho_"a"] | dry air density (0°C, 101.325 kPa) / stem:["kg m"^(−3)] | 1.2930 | – | 0.01
| stem:[(mu_("en")//rho)_("w,g")] a| ratio of mass energy-absorption coefficients | 1.1131 | – | 0.05
| stem:[W//e] | mean energy per charge / stem:["J C"^(−1)] | 33.97 | – | 0.08
| stem:[D_("g,air")=s_("g,air")k_("cav")] a| product of the ratio of mass stopping powers and cavity perturbation correction | 0.9958 | 0.02 | 0.13
| stem:[psi_("w,g")] | fluence ratio | 1.0037 | 0.01 | 0.07
| stem:[beta_("w,g")] a| absorbed-dose-to-collision-kerma ratio | 0.9998 | 0.01 | 0.01
5+| _Correction factors_
| stem:[k_("env")] | envelope of the chamber | 0.9993 | 0.01 | 0.02
| stem:[k_("win")] | entrance window of the phantom | 0.9997 | 0.01 | 0.01
| stem:[k_("rn")] | radial non-uniformity | 1.0056 | 0.01 | 0.03
| stem:[k_("s")] | saturation | 1.0021 | 0.01 | 0.02
| stem:[k_("h")] | humidity | 0.9970 | – | 0.03
5+| _Measurement of_ stem:[I//nu]
| stem:[nu] | volume / cm^3^ | 6.7928 footnote:[Standard CH7-1.] | – | 0.08
| stem:[I] | ionization current (stem:[T], stem:[P], air compressibility) | – | – | 0.02
| a| short-term reproducibility (including positioning and current measurement) footnote:[Over a period of 3 months. The long-term reproducibility over a period of 15 years, stem:[u_("rep")], is 0.0006.] | | 0.02 | –
5+| _Combined uncertainty of the BIPM determination of absorbed-dose rate to water_
3+| quadratic summation ^| 0.04 ^| 0.18
3+| combined relative standard uncertainty 2+^| 0.19
|===

[bibliography]
== References

* [[[boutillon1,1]]], Boutillon M, Henry W H and Lamperti PJ 1969 Comparison of exposure standards in the 10-50 kV x-ray region https://www.iop.org/EJ/abstract/0026-1394/5/1/002/[_Metrologia_, *5*, 1-11].

* [[[boutillon2,2]]], Boutillon M and Niatel M-T 1973 A study of a graphite chamber for absolute exposure measurement of ^60^Co gamma rays https://www.iop.org/EJ/abstract/0026-1394/9/4/001/[_Metrologia_, *9*, 139-146]

* [[[boutillon3,3]]], Boutillon M 1978 Mesure de l'exposition au BIPM dans le domaine des rayons X de 100 à 250 kV https://www.bipm.org/utils/common/pdf/rapportBIPM/1978/03.pdf[_Rapport BIPM-78/3_].

* [[[boutillon4,4]]], Boutillon M and Perroche A-M 1993 Determination of calibration factors in terms of air kerma and absorbed dose to water in the ^60^Co gamma rays SSDL Newsletter *32*.

* [[[boutillon5,5]]], Boutillon M and Perroche A-M 1993 Ionometric determination of absorbed dose to water for cobalt-60 gamma rays, https://www.iop.org/EJ/abstract/0031-9155/38/3/010/[_Phys. Med. Biol._ *38*, 439-454]

* [[[boutillon6,6]]], Boutillon M 1996 Behaviour of transfer chambers in the low-energy x-ray range https://www.iop.org/EJ/abstract/0026-1394/33/5/7/[_Metrologia_ *33* 479-484].

* [[[burns7,7]]], Burns D T 2004 Changes to the BIPM primary air-kerma standards for x-rays https://www.iop.org/EJ/abstract/0026-1394/41/1/L02/[_Metrologia_ *41* L3].

* [[[burns8,8]]], Burns D T 2006 A new approach to the determination of air kerma using primary-standard cavity ionization chambers https://www.iop.org/EJ/abstract/0031-9155/51/4/012/[_Phys. Med. Biol._ *51*, 929-942]

* [[[burns9,9]]], Burns D T, Allisy P J and Kessler C 2007 Re-evaluation of the BIPM international standard for air kerma in ^60^Co gamma radiation, https://www.iop.org/EJ/abstract/0026-1394/44/6/N02[_Metrologia_, 44, L53-L56]

* [[[burns10,10]]], Burns D T, Kessler C and Allisy P J 2009 Re-evaluation of the BIPM international standards for air kerma in x-rays https://www.bipm.org/metrologia/ViewArticle.jsp?VOLUME=46&PAGE=L21-L23[_Metrologia_, 46, L21-L23]

* [[[burns11,11]]], Burns D T 2017 New BIPM absorbed dose standard for medium-energy x-rays https://www.bipm.org/cc/AllowedDocuments.jsp[CCRI(I)/17-08]

* [[[burns12,12]]], Burns D T and Kessler C 2018 Re-evaluation of the BIPM international dosimetry standards on adoption of the recommendations of ICRU Report 90 https://iopscience.iop.org/article/10.1088/1681-7575/aacb01[_Metrologia_ *55* R21-R26]

* [[[ccemri13,13]]], CCEMRI 1972 Qualités de rayonnement _Comité Consultative pour les Etalons de Mesures des Rayonnements Ionisants (Section I)_ 2 R15 (Offilib, 75240 Paris Cedex 05)

* [[[ccemri14,14]]], CCEMRI 1975 Qualités de rayonnement _Comité Consultative pour les Etalons de Mesures des Rayonnements Ionisants (Section I)_ *3* R(I)6 (Offilib, F-75240 Paris Cedex 05)

* [[[ccri,15]]], CCRI 2011 Mammography dosimetry radiation qualities Consultative _Committee for Ionizing Radiation_ 22nd meeting report (2011)

* [[[icru,16]]], ICRU 2016 Key data for ionizing radiation dosimetry: Measurement standards and applications https://academic.oup.com/jicru/article/14/1/NP/2468591[_J. ICRU_ *14* ICRU Report 90] (Oxford University Press)

* [[[jcgm,17]]], JCGM 2008 _Evaluation of measurement data – Guide to the expression of uncertainty in measurement_ https://www.bipm.org/utils/common/documents/jcgm/JCGM_100_2008_E.pdf[JCGM 100:2008] (GUM with minor corrections)

* [[[kessler,18]]], Kessler C, Roger P and Burns D T 2010 Establishment of reference radiation qualities for mammography https://www.bipm.org/utils/common/pdf/rapportBIPM/2010/01.pdf[_Rapport BIPM-2010/01_]
