
[[cls_1]]
== Scope

This Supplement provides a general numerical approach, consistent with the broad principles of the GUM <<JCGM-100,clause=G.1.5>>, for carrying out the calculations required as part of an evaluation of measure-ment uncertainty. The approach applies to arbitrary models having a single output quantity where the input quantities are characterized by any specified PDFs <<JCGM-100,clause=G.1.4, G.5.3>>.

As in the GUM, this Supplement is primarily concerned with the expression of uncertainty in the measurement of a well-defined physical quantity—the measurand—that can be characterized by an essentially unique value <<JCGM-100,clause=1.2>>.

This Supplement also provides guidance in situations where the conditions for the GUM uncertainty frame-work <<JCGM-100,clause=G.6.6>> are not fulfilled, or it is unclear whether they are fulfilled. It can be used when it is difficult to apply the GUM uncertainty framework, because of the complexity of the model, for example. Guidance is given in a form suitable for computer implementation.

This Supplement can be used to provide (a representation of) the PDF for the output quantity from which

. [[item_scope_a]]an estimate of the output quantity,
. [[item_scope_b]]the standard uncertainty associated with this estimate, and
. [[item_scope_c]]a coverage interval for that quantity, corresponding to a specified coverage probability

can be obtained.

Given (i) the model relating the input quantities and the output quantity and (ii) the PDFs characterizing the input quantities, there is a unique PDF for the output quantity. Generally, the latter PDF cannot be determined analytically. Therefore, the objective of the approach described here is to determine <<item_scope_a>>, <<item_scope_b>>, and <<item_scope_c>> above to a prescribed numerical tolerance, without making unquantified approximations.

For a prescribed coverage probability, this Supplement can be used to provide any required coverage interval, including the probabilistically symmetric coverage interval and the shortest coverage interval.

This Supplement applies to input quantities that are independent, where each such quantity is assigned an appropri-ate PDF, or not independent, i.e. when some or all of these quantities are assigned a joint PDF.

Typical of the uncertainty evaluation problems to which this Supplement can be applied include those in which

* the contributory uncertainties are not of approximately the same magnitude <<JCGM-100,clause=G.2.2>>,
* it is difficult or inconvenient to provide the partial derivatives of the model, as needed by the law of propagation of uncertainty <<JCGM-100,clause=5>>,
* the PDF for the output quantity is not a Gaussian distribution or a scaled and shifted stem:[t]-distribution <<JCGM-100,clause=G.6.5>>,
* an estimate of the output quantity and the associated standard uncertainty are approximately of the same magnitude <<JCGM-100,clause=G.2.1>>,
* the models are arbitrarily complicated <<JCGM-100,clause=G.1.5>>, and
* the PDFs for the input quantities are asymmetric <<JCGM-100,clause=G.5.3>>.

A validation procedure is provided to check whether the GUM uncertainty framework is applicable. The GUM uncer-tainty framework remains the primary approach to uncertainty evaluation in circumstances where it is demonstrably applicable.

It is usually sufficient to report measurement uncertainty to one or perhaps two significant decimal digits. Guidance is provided on carrying out the calculation to give reasonable assurance that in terms of the information provided the reported decimal digits are correct.

Detailed examples illustrate the guidance provided.

This document is a Supplement to the GUM and is to be used in conjunction with it. Other approaches generally consistent with the GUM may alternatively be used. The audience of this Supplement is that of the GUM.

NOTE: This Supplement does not consider models that do not define the output quantity uniquely (for example, involving the solution of a quadratic equation, without specifying which root is to be taken).

[[note2_1]]
NOTE: This Supplement does not consider the case where a prior PDF for the output quantity is available, but the treatment here can be adapted to cover this case <<Elster2007>>.