
[[cls_3]]
== Terms and definitions

For the purposes of this document the terms and definitions of the GUM and the "International vocabulary of basic and general terms in metrology" (VIM) apply unless otherwise indicated. Some of the most relevant definitions, adapted where necessary from these documents (see <<scls_4-2>>), are given below. Further definitions are given, including definitions taken or adapted from other sources, that are important for this Supplement.

A glossary of principal symbols is given in <<annexG>>.


=== probability distribution

(random variable) function giving the probability that a random variable takes any given value or belongs to a given set of values

NOTE: The probability on the whole set of values of the random variable equals 1.

// &#x200c;[Adapted from ISO 3534-1:1993 1.3; GUM:1995 C.2.3]
<<ISO_3534-1,clause=1.3>>,<<JCGM-100,clause=C.2.3>>

NOTE: A probability distribution is termed univariate when it relates to a single (scalar) random variable, and multivariate when it relates to a vector of random variables. A multivariate probability distribution is also described as a joint distribution.

NOTE: A probability distribution can take the form of a distribution function or a probability density function.


=== distribution function

function giving, for every value stem:[xi], the probability that the random variable stem:[ii(X)] be less than or equal to stem:[xi]: 

[stem%unnumbered]
++++
G_x (xi) = "Pr"(X <= xi)
++++

// &#x200c;[Adapted from ISO 3534-1:1993 1.4; GUM:1995 C.2.4]
[.source]
<<ISO_3534-1,clause=1.4>>,<<JCGM-100,clause=C.2.4>>


=== probability density function

derivative, when it exists, of the distribution function

[stem%unnumbered]
++++
g_X (xi) = "d"G_X (xi)//"d"xi
++++

[NOTE]
====
stem:[g_X (xi) "d"xi] is the "probability element"

[stem%unnumbered]
++++
g_X (xi) "d"xi = "Pr"(xi < X < xi + "d"xi).
++++
====

// &#x200c;[Adapted from ISO 3534-1:1993 1.5; GUM:1995 C.2.5]
[.source]
<<ISO_3534-1,clause=1.5>>,<<JCGM-100,clause=C.2.5>>


=== normal distribution

probability distribution of a continuous random variable stem:[ii(X)] having the probability density function

[stem%unnumbered]
++++
g_X (xi) = 1 /{sigma sqrt(2 pi)} exp[- 1/2 ({xi - mu}/sigma)^2]
++++

for stem:[-infty < xi < +infty]


NOTE: stem:[mu] is the expectation and stem:[sigma] is the standard deviation of stem:[ii(X)].

// &#x200c;[Adapted from ISO 3534-1:1993 1.37; GUM:1995 C.2.14]
[.source]
<<ISO_3534-1,clause=1.37>>,<<JCGM-100,clause=C.2.14>>

NOTE: The normal distribution is also known as a Gaussian distribution.


=== stem:[t]-distribution

probability distribution of a continuous random variable stem:[ii(X)] having the probability density function


[stem%unnumbered]
++++
g_x(xi) = Gamma((nu + 1)//2) / {sqrt(pi nu)Gamma (nu//2)} (1 + xi^2/nu)^{-(nu+1)//2},
++++


for stem:[-oo < xi < +oo], with parameter stem:[nu], a positive integer, the degrees of freedom of the distribution, where

[stem%unnumbered]
++++
Gamma(z) = int_0^{oo} t^{z-1} e^{-t} " d"t, " " " " z > 0
++++

is the gamma function


[[scls_3-6]]
=== expectation

property of a random variable, which, for a continuous random variable stem:[ii(X)] characterized by a PDF stem:[g_X (xi)], is given by

[stem%unnumbered]
++++
ii(E)(ii(X)) = int_{-oo}^{oo} xi g_X (xi) " d"xi
++++

NOTE: Not all random variables have an expectation.

[NOTE]
====
The expectation of the random variable stem:[ii(Z) = F(X)], for a given function stem:[F(X)], is

[stem%unnumbered]
++++
E(Z) = E(F(X)) = int_{-oo}^{oo} F(xi) g_X (xi) " d"xi.
++++
====


[[scls_3-7]]
=== variance

property of a random variable, which, for a continuous random variable stem:[ii(X)] characterized by a PDF stem:[g_X (xi)], is given by

[stem%unnumbered]
++++
ii(V)(ii(X)) = int_{-oo}^{oo} [xi - ii(E)(ii(X))]^2 g_X (xi) " d"xi
++++

NOTE: Not all random variables have a variance.


=== standard deviation

positive square root stem:[[ii(V)(ii(X))\]^{1//2}] of the variance


=== moment of order stem:[r]

expectation of the __r__th power of a random variable, namely

[stem%unnumbered]
++++
E(X^r) = int_{-oo}^{oo} xi^r g_X (xi) " d"xi
++++

NOTE: The central moment of order stem:[r] is the expectation of the random variable stem:[ii(Z) = [X - ii(E)(ii(X))\]^r].

NOTE: The expectation stem:[ii(E)(ii(X))] is the first moment. The variance stem:[ii(V)(ii(X))] is the central moment of order 2.


=== covariance

property of a pair of random variables, which, for two continuous random variables stem:[X_1] and stem:[X_2] characterized by a joint (multivariate) PDF stem:[g_{bb(X)} (bb(xi))], where stem:[X = (X_1, X_2)^T] and stem:[xi = (xi_1, xi_2)^T], is given by

[stem%unnumbered]
++++
"Cov"(X_1,X_2) = int_{-oo}^{oo} int_{-oo}{oo} [xi_1 - E(X_1)][xi_2 - E(X_2)] g_X (xi) " d"xi_1 " d"xi_2
++++

NOTE: Not all pairs of random variables have a covariance.


=== uncertainty matrix

matrix of dimension stem:[ii(N) xx ii(N)], containing on its diagonal the squares of the standard uncertainties associated with estimates of the components of an N-dimensional vector quantity, and in its off-diagonal positions the covariances associated with pairs of estimates

NOTE: An uncertainty matrix stem:[bb(U)_x] of dimension stem:[ii(N) xx ii(N)] associated with the vector estimate stem:[x] of a vector quantity stem:[ii(X)] has the representation

[stem%unnumbered]
++++
bb(U_x) = [(u(x_1,x_1),cdots,u(x_1,x_N)),(vdots,ddots,vdots),(u(x_N,x_1),cdots,u(x_N,x_N))],
++++

where stem:[u(x_i, x_i) = u^2(x_i)] is the variance (squared standard uncertainty) associated with stem:[x_i] and stem:[u(x_i, x_j)] is the covariance associated with stem:[x_i] and stem:[x_j]. stem:[u(x_i, x_j) = 0] if elements stem:[X_i] and stem:[X_j] of stem:[bb(X)] are uncorrelated.

NOTE: Covariances are also known as mutual uncertainties.

NOTE: An uncertainty matrix is also known as a covariance matrix or variance-covariance matrix.


=== coverage interval

interval containing the value of a quantity with a stated probability, based on the information available

NOTE: A coverage interval is sometimes known as a credible interval or a Bayesian interval.

NOTE: Generally there is more than one coverage interval for a stated probability.

NOTE: A coverage interval should not be termed 'confidence interval' to avoid confusion with the statistical con-cept <<JCGM-100,clause=6.2.2>>.

NOTE: This definition differs from that in the VIM, 3rd Edition (2008), since the term 'true value' has not been used in this Supplement, for reasons given in the GUM <<JCGM-100,clause=E.5>>.


=== coverage probability

probability that the value of a quantity is contained within a specified coverage interval

NOTE: The coverage probability is sometimes termed "level of confidence" <<JCGM-100,clause=6.2.2>>.


=== length of a coverage interval

largest value minus smallest value in a coverage interval


=== probabilistically symmetric coverage interval

coverage interval for a quantity such that the probability that the quantity is less than the smallest value in the interval is equal to the probability that the quantity is greater than the largest value in the interval


=== shortest coverage interval

coverage interval for a quantity with the shortest length among all coverage intervals for that quantity having the same coverage probability


=== propagation of distributions

method used to determine the probability distribution for an output quantity from the probability distributions assigned to the input quantities on which the output quantity depends

NOTE: The method may be analytical or numerical, exact or approximate.


=== GUM uncertainty framework

application of the law of propagation of uncertainty and the characterization of the output quantity by a Gaussian distribution or a scaled and shifted stem:[t]-distribution in order to provide a coverage interval


=== Monte Carlo method

method for the propagation of distributions by performing random sampling from probability distributions


[[scls_3-20]]
=== numerical tolerance

semi-width of the shortest interval containing all numbers that can correctly be expressed to a specified number of significant decimal digits

[example]
All numbers greater than 1.75 and less than 1.85 can be expressed to two significant decimal digits as 1.8. The numerical tolerance is stem:[(1.85 - 1.75)//2 = 0.05].

NOTE: For the calculation of numerical tolerance associated with a numerical value, see <<scls_7-9-2>>.
