
[[annexA]]
[appendix]
== Historical perspective

=== {blank}

The GUM is a rich document, covering many aspects of uncertainty evaluation. Although it does not refer explicitly to the use of a Monte Carlo method, such use was recognized during the drafting of the GUM. The ISO/IEC/OIML/BIPM draft (First Edition) of June 1992, produced by ISO/TAG 4/WG 3, states [G.1.5]:

____
If the relationship between stem:[ii(Y)] and its input quantities is nonlinear, or if the values available for the parameters characterizing the probabilities of the stem:[ii(X)_i] (expectation, variance, higher moments) are only estimates and are themselves characterized by probability distributions, and a first-order Taylor expansion of the relationship is not an acceptable approximation, the distribution of stem:[ii(Y)] cannot be expressed as a convolution. In this case, a numerical approach (such as Monte Carlo calculations) will generally be required and the evaluation is computationally more difficult.
____


=== {blank}

In the published version of the GUM, this subclause had been modified to read:
____
If the functional relationship between stem:[ii(Y)] and its input quantities is nonlinear and a first-order Taylor expansion of the relationship is not an acceptable approximation (see 5.1.2 and 5.1.5), then the probability distribution of stem:[ii(Y)] cannot be obtained by convolving the distributions of the input quantities. In such cases, other analytical or numerical methods are required.
____


=== {blank}

The interpretation made here of this re-wording is that "other analytical or numerical methods" cover any other appropriate approach. This interpretation is consistent with that of the National Institute of Standards and Technology of the United States <<Taylor1994>>:

____
[6.6] The NIST policy provides for exceptions as follows (see Annex C):


It is understood that any valid statistical method that is technically justified under the existing circumstances may be used to determine the equivalent of stem:[u_i], stem:[u_c], or U. Further, it is recognized that international, national, or contractual agreements to which NIST is a party may occasionally require deviation from NIST policy. In both cases, the report of uncertainty must document what was done and why.
____

