
[[annexF]]
[appendix]
== Comparison loss problem

This annex is concerned with some details of the comparison loss problem (see <<scls_9-4>>). <<scls_F-1>> provides the expectation and standard deviation of stem:[delta ii(Y)] (see <<scls_9-4-2-1-2>>). <<scls_F-2>> provides the PDF for stem:[delta ii(Y)] analytically when stem:[x_1 = x_2 = r(x_1, x_2) = 0] (see <<scls_9-4-2-1-2>>). <<scls_F-3>> applies the GUM uncertainty framework for uncor-related and correlated input quantities (see <<scls_9-4-2-1-3>> and <<scls_9-4-3-1-1>>).


[[scls_F-1]]
=== Expectation and standard deviation obtained analytically

==== {blank}

The variance of a quantity stem:[ii(X)] can be expressed in terms of expectations as <<Rice1995,page=124>>

[stem%unnumbered]
++++
ii(V)(ii(X)) = E(X^2) - [ii(E)(ii(X))]^2.
++++

Thus,

[stem%unnumbered]
++++
E(X^2) = [ii(E)(ii(X))]^2 + ii(V)(ii(X)) = x^2 + u^2(x),
++++

where stem:[x] is the best estimate of stem:[ii(X)] and stem:[u(x)] the standard uncertainty associated with stem:[x]. Thus, for the model <<eq28,(28)>>, viz. stem:[delta ii(Y) = 1 - ii(Y) = X_1^2 + X_2^2],

[stem%unnumbered]
++++
delta y = E(delta ii(Y)) = x_1^2 + x_2^2 + u^2(x_1) + u^2(x_2).
++++

This result applies

. regardless of which PDFs are assigned to stem:[ii(X)_1] and stem:[ii(X)_2], and
. whether stem:[ii(X)_1] and stem:[ii(X)_2] are independent or not.


==== {blank}

The standard uncertainty associated with stem:[delta y] can be obtained from

[stem%unnumbered]
++++
u^2 (delta y) = u^2 (x_1^2) + u^2(x_2^2) + 2u(x_1^2, x_2^2),
++++

where, for stem:[i = 1] and stem:[i = 2], stem:[u^2(x_i^2) = V (X_i^2)], and stem:[u(x_1^2, x_2^2) = rm(Cov)(X_1^2, X_2^2)]. Then, applying Price's Theorem for Gaussian distributions <<Papoulis1965>>, <<Price1958>>

[[eqf1]]
[stem]
++++
u^2 (delta y) = 4u^2 (x_1)x_1^2 + 4u^2(x_2)x_2^2 + 2u^4(x_1) + 2u^4(x_2) + 4u^2(x_1,x_2) + 8u(x_1,x_2)x_1 x_2
++++

When stem:[x_2 = 0] and stem:[u(x_2) = u(x_1)], and replacing stem:[u(x_1, x_2)] by stem:[r(x_1, x_2)u^2(x_1)],

[stem%unnumbered]
++++
u(delta y) = 2 x_1^2 + [1 + r^2(x_1, x_2)]u^2(x_1) ^1/2^ u(x_1).
++++


==== {blank}

When stem:[ii(X)_1] and stem:[ii(X)_2] are uncorrelated, i.e. stem:[u(x_1, x_2) = 0], <<eqf1>> becomes

[[eqf2]]
[stem]
++++
u^2 (delta y) = 4 u^2 (x_1) x_1^2 + 4u^2 (x_2) x_2^2 + 2 u^4 (x_1) + 2 u^4 (x_2).
++++


<<eqf2>> can be verified by applying <<eq10>> of the GUM <<JCGM-100,clause=5.1.2>> and the immediately following GUM formula <<JCGM-100,clause=5.1.2 note>>.


[[scls_F-2]]
=== Analytic solution for zero estimate of the voltage reflection coefficient having associated zero covariance

==== {blank}

For the case stem:[x_1 = x_2 = r(x_1, x_2) = 0] and stem:[u(x_1) = u(x_2)], the PDF stem:[g_Y (eta)] for Y can be obtained analytically. It is valuable to have such a solution for further validation purposes. In the above circumstances,

[stem%unnumbered]
++++
delta Y = u^2 (x_1) [X_1^2/{u^2 (x_1)} + X_2^2/{u^2(x_2)}].
++++


==== {blank}

The term in square brackets is the sum, stem:[ii(Z)], say, of the squares of two independent quantities, each of which is distributed as a standard Gaussian PDF. Thus the sum is distributed as chi-squared with two degrees of freedom <<Rice1995,page=177>>, so that

[stem%unnumbered]
++++
delta Y = u^2 (x_1) ii(Z),
++++

where stem:[ii(Z)] has PDF

[stem%unnumbered]
++++
g_Z (z) = χ_2^2 (z) = e^{-z//2}//2.
++++


==== {blank}

The application of a general formula <<Rice1995,page=57-61>> for the PDF stem:[g_Y (eta)] of a differentiable and strictly decreasing function of a variable (here stem:[Z]) with a specified PDF yields

[stem%unnumbered]
++++
g_Y (eta) = 1/{u^2 (x_1) χ_2^2} (eta/{u^2(x_1)}) = 1/{2u^2 (x_1)} exp(- eta/{2u^2(x_1)}), " " eta >= 0.
++++


==== {blank}

The expectation of stem:[delta ii(Y)] is given by

[stem%unnumbered]
++++
delta y = E(delta Y) = int_{0}^{oo} eta g_Y (eta) " d"eta = 2u^2 (x_1)
++++

and the variance

[stem%unnumbered]
++++
u^2 (delta y) = V(delta Y) = int_{0}^{oo} (eta - y)^2 g_Y (eta) " d"eta = 4u^4 (x_1),
++++

i.e. the standard deviation is stem:[2u^2 (x_1)], results that are consistent with those in <<scls_F-1>>.


==== {blank}

By integration, the corresponding distribution function is

[[eqf3]]
[stem]
++++
G_Y (eta) = 1 - exp(- eta/{2u^2(x_1)}), " " eta >= 0.
++++


==== {blank}

Let stem:[delta y_{alpha}] be that stem:[eta] in <<eqf3>> corresponding to stem:[G_Y (eta) = alpha] for any stem:[alpha] satisfying stem:[0 <= alpha <= 1-p]. Then

[stem%unnumbered]
++++
delta y_{alpha} = -2u^2(x_1) ln(1 - alpha)
++++

and a stem:[100p " %"] coverage interval for stem:[delta ii(Y)] (see <<scls_7-7>>) is

[[eqf4]]
[stem]
++++
[delta y_{alpha}, delta y_{p+alpha}] -= [-2u^2(x_1) ln(1 - alpha), -2u^2(x_1) ln(1 - p - alpha)]
++++

with length

[stem%unnumbered]
++++
H(alpha) = -2u^2(x_1)ln(1 - p/{1 - alpha}).
++++


==== {blank}

The shortest stem:[100p " %"] coverage interval is given by determining stem:[alpha] to minimize stem:[ii(H)(alpha)] (see <<scls_5-3-4>>). Since stem:[ii(H)(alpha)] is a strictly increasing function of stem:[alpha] for stem:[0 <= alpha <= 1 - p], stem:[H(alpha)] is minimized when stem:[alpha = 0]. Thus, the shortest stem:[100p " %"] coverage interval for stem:[delta ii(Y)] is

[stem%unnumbered]
++++
[0, - 2u^2 (x_1) ln(1 - p)].
++++

For stem:[u(x_1) = 0.005], the shortest 95 % coverage interval is

[stem%unnumbered]
++++
[0, 0.0001498].
++++

==== {blank}

The 95 % probabilistically symmetric coverage interval for stem:[delta ii(Y)] is given by setting stem:[alpha = (1 - p)//2] (see <<scls_5-3-3>>):

[stem%unnumbered]
++++
[-2u^2 (x_1) ln 0.975, - 2u^2 (x_1) ln 0.025] = [0.0000013, 0.0001844],
++++

which is 20 % longer than the shortest 95 % coverage interval.

NOTE: The above analysis is indicative of an analytical approach that can be applied to some problems of this type. In this particular case, the results could in fact have been obtained more directly, since stem:[g_Y(eta)] is strictly increasing and the shortest coverage interval is always in the region of highest density.


[[scls_F-3]]
=== GUM uncertainty framework applied to the comparison loss problem

==== Uncorrelated input quantities

===== {blank}

The comparison loss problem considered in <<scls_9-4>> has as the model of measurement

[stem%unnumbered]
++++
delta ii(Y) = f(bb(X)) = f(X_1, X_2) = X_1^2 + X_2^2,
++++

where stem:[ii(X)_1] and stem:[ii(X)_2] are assigned Gaussian PDFs having expectations stem:[x_1] and stem:[x_2] and variances stem:[u^2(x_1)] and stem:[u^2(x_2)], respectively.


===== {blank}

The application of GUM subclause 5.1.1 gives

[stem%unnumbered]
++++
delta y = x_1^2 + x_2^2
++++

as the estimate of stem:[delta ii(Y)]. The only non-trivially non-zero partial derivatives of the model are, for stem:[i = 1, 2],

[stem%unnumbered]
++++
{partial f}/{partial X_i} = 2 X_i, " " " " {partial^2 f}/{partial X_i^2} = 2.
++++


===== {blank}

Hence the application of GUM subclause 5.1.2 gives, for the standard uncertainty stem:[u(delta y)],

[[eqf5]]
[stem]
++++
u^2(delta y) = {:[({partial f}/{partial X_1})^2 u^2(x_1) + ({partial f}/{partial X_2})^2]|_{bb(X)=bb(x)} = 4 x_1^2 u^2 (x_1) + 4 x_2^2 u^2 (x_2),
++++

based on a first-order Taylor series approximation of stem:[f(bb(X))]. If the non-linearity of stem:[f] is significant <<JCGM-100,clause=5.1.2 note>>, the term


[stem%unnumbered]
++++
{:1/2 [{partial^2 f}/{partial X_1^2} + {partial^2 f}/{partial X_2^2}]|_{bb(X)=bb(x)} u^2 (x_1) u^2 (x_2)
++++

needs to be appended to <<eqf5>>, in which case <<eqf5>> becomes

[[eqf6]]
[stem]
++++
u^2(delta y) = 4x_1^2 u^2(x_1) + 4x_2^2 u^2(x_2) + 4u^2 (x_1)u^2(x_2).
++++


===== {blank}

A 95 % coverage interval for stem:[delta ii(Y)] is given by

[stem%unnumbered]
++++
delta y +- 2u(delta y),
++++

as a consequence of stem:[delta ii(Y)] having a Gaussian PDF.


[[scls_F-3-2]]
==== Correlated input quantities

===== {blank}

When the input quantities are correlated, the uncertainty matrix associated with the best estimates of the input quantities is given in <<eq27>>.


===== {blank}

The application of GUM subclause 5.2.2 gives

[[eqf7]]
[stem]
++++
{:(u^2(delta y),= {:[({partial f}/{partial X_1})^2 u^2(x_1) + ({partial f}/{partial X_2})^2 u^2(x_2) + 2 {partial f}/{partial X_1} {partial f}/{partial X_2} r(x_1,x_2)u(x_1)u(x_2)]|_{bb(X)=bb(x)}),
(" ",= 4x_1^2 u^2 (x_1) + 4x_2^2 u^2 (x_2) + 8r(x_1,x_2) x_1 x_2 u(x_1) u(x_2).):}
++++
