
[[cls_2]]
== Definitions

[[scls_2-1]]
=== General metrological terms

The definition of a number of general metrological terms relevant to this _Guide_, such as "measurable quantity", "measurand", and "error of measurement", are given in <<annexB>>. These definitions are taken from the _International vocabulary of basic and general terms in metrology_ (abbreviated VIM) footnote:[*Footnote to the 2008 version:* The third edition of the vocabulary was published in 2008, under the title JCGM 200:2008, _International vocabulary of metrology -- Basic and general concepts and associated terms (VIM)_.] <<International1993>>. In addition, <<annexC>> gives the definitions of a number of basic statistical terms taken mainly from International Standard ISO 3534-1 <<ISO_3534-1>>. When one of these metrological or statistical terms (or a closely related term) is first used in the text, starting with <<cls_3>>, it is printed in boldface and the number of the subclause in which it is defined is given in parentheses.

Because of its importance to this _Guide_, the definition of the general metrological term "uncertainty of measurement" is given both in <<annexB>> and <<scls_2-2-3>>. The definitions of the most important terms specific to this _Guide_ are given in <<scls_2-3-1>> to <<scls_2-3-6>>. In all of these subclauses and in <<annexB>> and <<annexC>>, the use of parentheses around certain words of some terms means that these words may be omitted if this is unlikely to cause confusion.


[[scls_2-2]]
=== The term "uncertainty"

The concept of uncertainty is discussed further in <<cls_3>> and <<annexD>>.


[[scls_2-2-1]]
==== {blank}

The word "uncertainty" means doubt, and thus in its broadest sense "uncertainty of measurement" means doubt about the validity of the result of a measurement. Because of the lack of different words for this _general concept_ of uncertainty and the specific quantities that provide _quantitative measures_ of the concept, for example, the standard deviation, it is necessary to use the word "uncertainty" in these two different senses.


[[scls_2-2-2]]
==== {blank}

In this _Guide_, the word "uncertainty" without adjectives refers both to the general concept of uncertainty and to any or all quantitative measures of that concept. When a specific measure is intended, appropriate adjectives are used.


[[scls_2-2-3]]
==== {blank}

The formal definition of the term "uncertainty of measurement" developed for use in this _Guide_ and in the VIM <<International1993>> (VIM:1993, definition 3.9) is as follows:

*uncertainty (of measurement)* +
parameter, associated with the result of a measurement, that characterizes the dispersion of the values that could reasonably be attributed to the measurand

NOTE: The parameter may be, for example, a standard deviation (or a given multiple of it), or the half-width of an interval having a stated level of confidence.

NOTE: Uncertainty of measurement comprises, in general, many components. Some of these components may be evaluated from the statistical distribution of the results of series of measurements and can be characterized by experimental standard deviations. The other components, which also can be characterized by standard deviations, are evaluated from assumed probability distributions based on experience or other information.

NOTE: It is understood that the result of the measurement is the best estimate of the value of the measurand, and that all components of uncertainty, including those arising from systematic effects, such as components associated with corrections and reference standards, contribute to the dispersion.


[[scls_2-2-4]]
==== {blank}

The definition of uncertainty of measurement given in <<scls_2-2-3>> is an operational one that focuses on the measurement result and its evaluated uncertainty. However, it is not inconsistent with other concepts of uncertainty of measurement, such as

* a measure of the possible error in the estimated value of the measurand as provided by the result of a measurement;
* an estimate characterizing the range of values within which the true value of a measurand lies (VIM:1984, definition 3.09).

Although these two traditional concepts are valid as ideals, they focus on _unknowable_ quantities: the "error" of the result of a measurement and the "true value" of the measurand (in contrast to its estimated value), respectively. Nevertheless, whichever _concept_ of uncertainty is adopted, an uncertainty component is always _evaluated_ using the same data and related information. (See also <<scls_E-5>>.)


[[scls_2-3]]
=== Terms specific to this _Guide_

In general, terms that are specific to this _Guide_ are defined in the text when first introduced. However, the definitions of the most important of these terms are given here for easy reference.

NOTE: Further discussion related to these terms may be found as follows: for <<scls_2-3-2>>, see <<scls_3-3-3>> and <<scls_4-2>>; for <<scls_2-3-3>>, see <<scls_3-3-3>> and <<scls_4-3>>; for <<scls_2-3-4>>, see <<cls_5>> and <<eq_10>> and <<eq_13>>; and for <<scls_2-3-5>> and <<scls_2-3-6>>, see <<cls_6>>.


[[scls_2-3-1]]
==== standard uncertainty

uncertainty of the result of a measurement expressed as a standard deviation


[[scls_2-3-2]]
==== Type A evaluation (of uncertainty)

method of evaluation of uncertainty by the statistical analysis of series of observations


[[scls_2-3-3]]
==== Type B evaluation (of uncertainty)

method of evaluation of uncertainty by means other than the statistical analysis of series of observations


[[scls_2-3-4]]
==== combined standard uncertainty

standard uncertainty of the result of a measurement when that result is obtained from the values of a number of other quantities, equal to the positive square root of a sum of terms, the terms being the variances or covariances of these other quantities weighted according to how the measurement result varies with changes in these quantities


[[scls_2-3-5]]
==== expanded uncertainty

quantity defining an interval about the result of a measurement that may be expected to encompass a large fraction of the distribution of values that could reasonably be attributed to the measurand

NOTE: The fraction may be viewed as the coverage probability or level of confidence of the interval.

[[note2_2-3-5]]
NOTE: To associate a specific level of confidence with the interval defined by the expanded uncertainty requires explicit or implicit assumptions regarding the probability distribution characterized by the measurement result and its combined standard uncertainty. The level of confidence that may be attributed to this interval can be known only to the extent to which such assumptions may be justified.

NOTE: Expanded uncertainty is termed _overall uncertainty_ in paragraph 5 of Recommendation INC-1 (1980).


[[scls_2-3-6]]
==== coverage factor

numerical factor used as a multiplier of the combined standard uncertainty in order to obtain an expanded uncertainty

NOTE: A coverage factor, stem:[k], is typically in the range 2 to 3.
