
[[cls_8]]
== Summary of procedure for evaluating and expressing uncertainty

The steps to be followed for evaluating and expressing the uncertainty of the result of a measurement as presented in this _Guide_ may be summarized as follows:

. Express mathematically the relationship between the measurand stem:[Y] and the input quantities stem:[X_i] on which stem:[Y] depends: stem:[Y = f(X_1, X_2,..., X_N)]. The function stem:[f] should contain every quantity, including all corrections andcorrection factors, that can contribute a significant component of uncertainty to the result of the measurement (see <<scls_4-1-1>> and <<scls_4-1-2>>).
. Determine stem:[x_i], the estimated value of input quantity stem:[X_i], either on the basis of the statistical analysis of series of observations or by other means (see <<scls_4-1-3>>).
. Evaluate the _standard uncertainty_ stem:[u(x_i)] of each input estimate stem:[x_i]. For an input estimate obtained from the statistical analysis of series of observations, the standard uncertainty is evaluated as described in <<scls_4-2>> (_Type A evaluation of standard uncertainty_). For an input estimate obtained by other means, the standard uncertainty stem:[u(x_i)] is evaluated as described in <<scls_4-3>> (_Type B evaluation of standard uncertainty_).
. Evaluate the covariances associated with any input estimates that are correlated (see <<scls_5-2>>).
. Calculate the result of the measurement, that is, the estimate stem:[y] of the measurand stem:[Y], from the functional relationship stem:[f] using for the input quantities stem:[X_i] the estimates stem:[x_i] obtained in step 2 (see <<scls_4-1-4>>).
. Determine the _combined standard uncertainty_stem:[u_{"c"}(y)] of the measurement result stem:[y] from the standard uncertainties and covariances associated with the input estimates, as described in <<cls_5>>. If the measurement determines simultaneously more than one output quantity, calculate their covariances (see <<scls_7-2-5>>,<<scls_H-2>>, <<scls_H-3>>, and <<scls_H-4>>).
. If it is necessary to give an _expanded uncertainty_ stem:[U], whose purpose is to provide an interval stem:[y - U] to stem:[y + U] that may be expected to encompass a large fraction of the distribution of values that couldreasonably be attributed to the measurand stem:[Y], multiply the combined standard uncertainty stem:[u_{"c"}(y)] by a _coverage factor_ stem:[k], typically in the range 2 to 3, to obtain stem:[U = k u_{"c"}(y)]. Select stem:[k] on the basis of the level of confidence required of the interval (see <<scls_6-2>>,<<scls_6-3>>, and especially <<annexG>>, which discusses the selection of a value of stem:[k], that produces an interval having a level of confidence close to a specified value).
. Report the result of the measurement stem:[y] together with its combined standard uncertainty stem:[u_{"c"}(y)] or expanded uncertainty stem:[U] as discussed in <<scls_7-2-1>> and <<scls_7-2-3>>; use one of the formats recommended in <<scls_7-2-2>> and <<scls_7-2-4>>. Describe, as outlined also in <<cls_7>>, how stem:[y] and stem:[u_{"c"}(y)] or stem:[U] were obtained.
