
[[annexA]]
[appendix]
== Recommendations of Working Group and CIPM

[[scls_A-1]]
=== Recommendation INC-1 (1980)

The Working Group on the Statement of Uncertainties (see <<foreword>>) was convened in October 1980 by the Bureau International des Poids et Mesures (BIPM) in response to a request of the Comité International des Poids et Mesures (CIPM). It prepared a detailed report for consideration by the CIPM that concluded with Recommendation INC-1 (1980) <<KAARLS1981>>. The English translation of this Recommendation is given in <<scls_0-7>> of this _Guide_ and the French text, which is authoritative, is as follows <<KAARLS1981>>:

Expression des incertitudes expérimentales

*Recommandation INC-1 (1980)*

. L'incertitude d'un résultat de mesure comprend généralement plusieurs composantes qui peuvent être groupées en deux catégories d'après la méthode utilisée pour estimer leur valeur numérique:
.. celles qui sont évaluées à l'aide de méthodes statistiques,
.. celles qui sont évaluées par d'autres moyens.
+
--
Il n'y a pas toujours une correspondance simple entre le classement dans les catégories A ou B et le caractère «aléatoire» ou «systématique» utilisé antérieurement pour classer les incertitudes. L'expression «incertitude systématique» est susceptible de conduire à des erreurs d'interprétation; elle doit être évitée.

Toute description détaillée de l'incertitude devrait comprendre une liste complète de ses composantes et indiquer pour chacune la méthode utilisée pour lui attribuer une valeur numérique.
--
. Les composantes de la catégorie A sont caractérisées par les variances estimées stem:[s_i^2] (ou les «écart-types» estimés stem:[s_i]) et les nombres stem:[nu_i] de degrés de liberté. Le cas échéant, les covariances estimées doivent être données.
. Les composantes de la catégorie B devraient être caractérisées par des termes stem:[u_j^2] qui puissent être considérés comme des approximations des variances correspondantes dont on admet l'existence. Les termes stem:[u_j^2] peuvent être traités comme des variances et les termes stem:[u_j] comme des écarts-types. Le cas échéant, les covariances doivent être traitées de façon analogue.
. L'incertitude composée devrait être caractérisée par la valeur obtenue en appliquant la méthode usuelle de combinaison des variances. L'incertitude composée ainsi que ses composantes devraient être exprimées sous la forme d'«écart-types».
. Si pour des utilisations particulières on est amené à multiplier par un facteur l'incertitude composée afin d'obtenir une incertitude globale, la valeur numérique de ce facteur doit toujours être donnée.


[[scls_A-2]]
=== Recommendation 1 (CI-1981)

The CIPM reviewed the report submitted to it by the Working Group on the Statement of Uncertainties and adopted the following recommendation at its 70th meeting held in October 1981 <<CIPM1982>>:

*Recommendation 1 (CI-1981)*

Expression of experimental uncertainties

The Comité International des Poids et Mesures

_considering_

* the need to find an agreed way of expressing measurement uncertainty in metrology,
* the effort that has been devoted to this by many organizations over many years,
* the encouraging progress made in finding an acceptable solution, which has resulted from the discussions of the Working Group on the Expression of Uncertainties which met at BIPM in 1980,

_recognizes_

* that the proposals of the Working Group might form the basis of an eventual agreement on the expression of uncertainties,

_recommends_

* that the proposals of the Working Group be diffused widely;
* that BIPM attempt to apply the principles therein to international comparisons carried out under its auspices in the years to come;
* that other interested organizations be encouraged to examine and test these proposals and let their comments be known to BIPM;
* that after two or three years BIPM report back on the application of these proposals.


[[scls_A-3]]
=== Recommendation 1 (CI-1986)

The CIPM further considered the matter of the expression of uncertainties at its 75th meeting held in October 1986 and adopted the following recommendation <<CIPM1987>>:

*Recommendation 1 (CI-1986)*

Expression of uncertainties in work carried out under the auspices of the CIPM

The Comité International des Poids et Mesures,

_considering_ the adoption by the Working Group on the Statement of Uncertainties of Recommendation INC-1 (1980) and the adoption by the CIPM of Recommendation 1 (CI-1981),

_considering_ that certain members of Comités Consultatifs may want clarification of this Recommendationfor the purposes of work that falls under their purview, especially for international comparisons,

_recognizes_ that paragraph 5 of Recommendation INC-1 (1980) relating to particular applications, especially those having commercial significance, is now being considered by a working group of the International Standards Organization (ISO) common to the ISO, OIML and IEC, with the concurrence and cooperation of the CIPM,

_requests_ that paragraph 4 of Recommendation INC-1 (1980) should be applied by all participants ingiving the results of all international comparisons or other work done under the auspices of the CIPM and the Comités Consultatifs and that the combined uncertainty of type A and type B uncertainties in terms of _one standard deviation_ should be given.
