
[[annexB]]
[appendix]
== General metrological terms

[[scls_B-1]]
=== Source of definitions

The definitions of the general metrological terms relevant to this _Guide_ that are given here have been taken from the _International vocabulary of basic and general terms in metrology_ (abbreviated VIM), second edition, 1993 footnote:[*Footnote to the 2008 version:* The third edition of the vocabulary was published in 2008, under the title JCGM 200:2008, _International vocabulary of metrology -- Basic and general concepts and associated terms (VIM)_.] <<International1993>>, published by the International Organization for Standardization (ISO), in the name of the seven organizations that supported its development and nominated the experts who prepared it: the Bureau International des Poids et Mesures (BIPM), the International Electrotechnical Commission (IEC), the International Federation of Clinical Chemistry (IFCC), ISO, the International Union of Pure and Applied Chemistry (IUPAC), the International Union of Pure and Applied Physics (IUPAP), and the International Organization of Legal Metrology (OIML). The VIM should be the first source consulted for the definitions of terms not included either here or in the text.

NOTE: Some basic statistical terms and concepts are given in <<annexC>>, while the terms "true value", "error", and "uncertainty" are further discussed in <<annexD>>.


[[scls_B-2]]
=== Definitions

As in <<cls_2>>, in the definitions that follow, the use of parentheses around certain words of some terms means that the words may be omitted if this is unlikely to cause confusion.

The terms in boldface in some notes are additional metrological terms defined in those notes, either explicitly or implicitly (see Reference <<International1993>>).


[[scls_B-2-1]]
==== (measurable) quantity

attribute of a phenomenon, body or substance that may be distinguished qualitatively and determined quantitatively

[[note1_B-2-1]]
NOTE: The term quantity may refer to a quantity in a general sense (see <<example1_B-2-1>>) or to a *particular quantity* (see <<example2_B-2-1>>).

[[example1_B-2-1]]
[example]
Quantities in a general sense: length, time, mass, temperature, electrical resistance, amount-of-substance concentration.

[[example2_B-2-1]]
[example]
====
Particular quantities:

* length of a given rod
* electrical resistance of a given specimen of wire
* amount-of-substance concentration of ethanol in a given sample of wine.
====

NOTE: Quantities that can be placed in order of magnitude relative to one another are called *quantities of the same kind*.

[NOTE]
====
Quantities of the same kind may be grouped together into *categories of quantities*, for example:

* work, heat, energy
* thickness, circumference, wavelength.
====

NOTE: *Symbols for quantities* are given in ISO 31 footnote:[*Footnote to the 2008 version:* The ISO 31 series is under revision as a series of ISO 80000 and IEC 80000 documents. (Some of these documents have already been published.)].

// [VIM:1993, definition 1.1]
[.source]
<<International1993,definition 1.1>>


[[scls_B-2-2]]
==== value (of a quantity)

magnitude of a particular quantity generally expressed as a unit of measurement multiplied by a number

[example]
Length of a rod: 5.34 m or 534 cm.

[example]
Mass of a body: 0.152 kg or 152 g.

[example]
Amount of substance of a sample of water (H~2~O): 0.012 mol or 12 mmol.

NOTE: The value of a quantity may be positive, negative or zero.

NOTE: The value of a quantity may be expressed in more than one way.

NOTE: The values of quantities of dimension one are generally expressed as pure numbers.

NOTE: A quantity that cannot be expressed as a unit of measurement multiplied by a number may be expressed by reference to a conventional reference scale or to a measurement procedure or to both.

// [VIM:1993, definition 1.18]
[.source]
<<International1993,definition 1.18>>


[[scls_B-2-3]]
==== true value (of a quantity)

value consistent with the definition of a given particular quantity

NOTE: This is a value that would be obtained by a perfect measurement.

NOTE: True values are by nature indeterminate.

NOTE: The indefinite article "a", rather than the definite article "the", is used in conjunction with "true value" because there may be many values consistent with the definition of a given particular quantity.

// [VIM:1993, definition 1.19]
[.source]
<<International1993,definition 1.19>>

_Guide_ Comment: See <<annexD>>, in particular <<scls_D-3-5>>, _for_ the reasons why the term "true value" is not used in this _Guide_ and why the terms "true value of a measurand" (or of a quantity) and "value of a measurand" (or of aquantity) are viewed as equivalent.


[[scls_B-2-4]]
==== conventional true value (of a quantity)

value attributed to a particular quantity and accepted, sometimes by convention, as having an uncertainty appropriate for a given purpose

[example]
At a given location, the value assigned to the quantity realized by a reference standard may be taken as a conventional true value.

[example]
The CODATA (1986) recommended value for the Avogadro constant: stem:[6.0221367 xx 10^{23}" mol"^{-1}].


NOTE: "Conventional true value" is sometimes called *assigned value*, *best estimate* of the value, *conventional value* or *reference value*. "Reference value", in this sense, should not be confused with "reference value" in the senseused in the Note to VIM:1993, definition 5.7.

NOTE: Frequently, a number of results of measurements of a quantity is used to establish a conventional true value.

// [VIM:1993, definition 1.20]
[.source]
<<International1993,definition 1.20>>

_Guide_ Comment: See the _Guide_ Comment to <<scls_B-2-3>>.


[[scls_B-2-5]]
==== measurement

set of operations having the object of determining a value of a quantity

NOTE: The operations may be performed automatically.

// [VIM:1993, definition 2.1]
[.source]
<<International1993,definition 2.1>>


[[scls_B-2-6]]
==== principle of measurement

scientific basis of a measurement

[example]
The thermoelectric effect applied to the measurement of temperature.

[example]
The Josephson effect applied to the measurement of electric potential difference.

[example]
The Doppler effect applied to the measurement of velocity.

[example]
The Raman effect applied to the measurement of the wave number of molecular vibrations.

// [VIM:1993, definition 2.3]
[.source]
<<International1993,definition 2.3>>


[[scls_B-2-7]]
==== method of measurement

logical sequence of operations, described generically, used in the performance of measurements

[NOTE]
====
Methods of measurement may be qualified in various ways such as:

* substitution method
* differential method
* null method.
====

// [VIM:1993, definition 2.4]
[.source]
<<International1993,definition 2.4>>


[[scls_B-2-8]]
==== measurement procedure

set of operations, described specifically, used in the performance of particular measurements according to a given method

NOTE: A measurement procedure is usually recorded in a document that is sometimes itself called a "measurement procedure" (or a *measurement method*) and is usually in sufficient detail to enable an operator to carry out a measurement without additional information.

// [VIM:1993, definition 2.5]
[.source]
<<International1993,definition 2.5>>


[[scls_B-2-9]]
==== measurand

particular quantity subject to measurement

[example]
Vapour pressure of a given sample of water at 20 °C.

NOTE: The specification of a measurand may require statements about quantities such as time, temperature and pressure.

// [VIM:1993, definition 2.6]
[.source]
<<International1993,definition 2.6>>


[[scls_B-2-10]]
==== influence quantity

quantity that is not the measurand but that affects the result of the measurement

[example]
Temperature of a micrometer used to measure length.

[example]
Frequency in the measurement of the amplitude of an alternating electric potential difference.

[example]
Bilirubin concentration in the measurement of haemoglobin concentration in a sample of human blood plasma.

// [VIM:1993, definition 2.7]
[.source]
<<International1993,definition 2.7>>

_Guide_ Comment: The definition of influence quantity is understood to include values associated with measurement standards, reference materials, and reference data upon which the result of a measurement may depend, as well as phenomena such as short-term measuring instrument fluctuations and quantities such as ambient temperature, barometric pressure and humidity.


[[scls_B-2-11]]
==== result of a measurement

value attributed to a measurand, obtained by measurement

[NOTE]
====
When a result is given, it should be made clear whether it refers to:

* the indication
* the uncorrected result
* the corrected result

and whether several values are averaged.
====

NOTE: A complete statement of the result of a measurement includes information about the uncertainty of measurement.

// [VIM:1993, definition 3.1]
[.source]
<<International1993,definition 3.1>>


[[scls_B-2-12]]
==== uncorrected result

result of a measurement before correction for systematic error

// [VIM:1993, definition 3.3]
[.source]
<<International1993,definition 3.3>>


[[scls_B-2-13]]
==== corrected result

result of a measurement after correction for systematic error

// [VIM:1993, definition 3.4]
[.source]
<<International1993,definition 3.4>>


[[scls_B-2-14]]
==== accuracy of measurement

closeness of the agreement between the result of a measurement and a true value of the measurand

NOTE: "Accuracy" is a qualitative concept.

NOTE: The term *precision* should not be used for "accuracy".

// [VIM:1993, definition 3.5]
[.source]
<<International1993,definition 3.5>>

_Guide_ Comment: See the _Guide_ Comment to <<scls_B-2-3>>.


[[scls_B-2-15]]
==== repeatability (of results of measurements)

closeness of the agreement between the results of successive measurements of the same measurand carried out under the same conditions of measurement

[[note1_B-2-15]]
NOTE: These conditions are called *repeatability conditions*.

[NOTE]
====
Repeatability conditions include:

* the same measurement procedure
* the same observer
* the same measuring instrument, used under the same conditions
* the same location
* repetition over a short period of time.
====

NOTE: Repeatability may be expressed quantitatively in terms of the dispersion characteristics of the results.

// [VIM:1993, definition 3.6]
[.source]
<<International1993,definition 3.6>>


[[scls_B-2-16]]
==== reproducibility (of results of measurements)

closeness of the agreement between the results of measurements of the same measurand carried out under changed conditions of measurement

NOTE: A valid statement of reproducibility requires specification of the conditions changed.

[NOTE]
====
The changed conditions may include:

* principle of measurement
* method of measurement
* observer
* measuring instrument
* reference standard
* location
* conditions of use
* time.
====

NOTE: Reproducibility may be expressed quantitatively in terms of the dispersion characteristics of the results.

NOTE: Results are here usually understood to be corrected results.

// [VIM:1993, definition 3.7]
[.source]
<<International1993,definition 3.7>>


[[scls_B-2-17]]
==== experimental standard deviation

for a series of stem:[n] measurements of the same measurand, the quantity stem:[s(q_k)] characterizing the dispersion of the results and given by the formula:

[stem%unnumbered]
++++
s(q_k) = sqrt({sum_{j=1}^n (q_j - bar(q))^2}/{n-1})
++++

stem:[q_k] being the result of the __k__th measurement and stem:[bar(q)] being the arithmetic mean of the stem:[n] results considered

NOTE: Considering the series of stem:[n] values as a sample of a distribution, stem:[bar(q)] is an unbiased estimate of the mean stem:[mu_q], and stem:[s^2(q_k)] is an unbiased estimate of the variance stem:[sigma^2], of that distribution.

[[note2_B-2-17]]
NOTE: The expression stem:[s(q_k)//sqrt(n)] is an estimate of the standard deviation of the distribution of stem:[bar(q)] and is called the *experimental standard deviation of the mean*.

NOTE: "Experimental standard deviation of the mean" is sometimes incorrectly called *standard error of the mean*.

NOTE: Adapted from VIM:1993, definition 3.8.

_Guide_ Comment: Some of the symbols used in the VIM have been changed in order to achieve consistency with the notation used in <<scls_4-2>> of this _Guide_.


[[scls_B-2-18]]
==== uncertainty (of measurement)

parameter, associated with the result of a measurement, that characterizes the dispersion of the values that could reasonably be attributed to the measurand

NOTE: The parameter may be, for example, a standard deviation (or a given multiple of it), or the half-width of an interval having a stated level of confidence.

NOTE: Uncertainty of measurement comprises, in general, many components. Some of these components may be evaluated from the statistical distribution of the results of series of measurements and can be characterized by experimental standard deviations. The other components, which can also be characterized by standard deviations, are evaluated from assumed probability distributions based on experience or other information.

NOTE: It is understood that the result of the measurement is the best estimate of the value of the measurand, and that all components of uncertainty, including those arising from systematic effects, such as components associated with corrections and reference standards, contribute to the dispersion.

// [VIM:1993, definition 3.9]
[.source]
<<International1993,definition 3.9>>

_Guide_ Comment: It is pointed out in the VIM that this definition and the notes are identical to those in this _Guide_ (see <<scls_2-2-3>>).


[[scls_B-2-19]]
==== error (of measurement)

result of a measurement minus a true value of the measurand

NOTE: Since a true value cannot be determined, in practice a conventional true value is used [see VIM:1993, definitions 1.19 (<<scls_B-2-3>>) and 1.20 (<<scls_B-2-4>>)].

NOTE: When it is necessary to distinguish "error" from "relative error", the former is sometimes called *absolute error of measurement*. This should not be confused with *absolute value of error*, which is the modulus of the error.

// [VIM:1993, definition 3.10]
[.source]
<<International1993,definition 3.10>>

_Guide_ Comment: If the result of a measurement depends on the values of quantities other than the measurand, the errors of the measured values of these quantities contribute to the error of the result of the measurement. Also see the _Guide_ Comment to <<scls_B-2-22>> and to <<scls_B-2-3>>.


[[scls_B-2-20]]
==== relative error

error of measurement divided by a true value of the measurand

NOTE: Since a true value cannot be determined, in practice a conventional true value is used [see VIM:1993, definitions 1.19 (<<scls_B-2-3>>) and 1.20 (<<scls_B-2-4>>)].

// [VIM:1993, definition 3.12]
[.source]
<<International1993,definition 3.12>>

_Guide_ Comment: See the _Guide_ Comment to <<scls_B-2-3>>.


[[scls_B-2-21]]
==== random error

result of a measurement minus the mean that would result from an infinite number of measurements of the same measurand carried out under repeatability conditions

NOTE: Random error is equal to error minus systematic error.

NOTE: Because only a finite number of measurements can be made, it is possible to determine only an estimate of random error.

// [VIM:1993, definition 3.13]
[.source]
<<International1993,definition 3.13>>

_Guide_ Comment: See the _Guide_ Comment to <<scls_B-2-22>>.


[[scls_B-2-22]]
==== systematic error

mean that would result from an infinite number of measurements of the same measurand carried out under repeatability conditions minus a true value of the measurand

NOTE: Systematic error is equal to error minus random error.

NOTE: Like true value, systematic error and its causes cannot be completely known.

NOTE: For a measuring instrument, see "bias" (VIM:1993, definition 5.25).

// [VIM:1993, definition 3.14]
[.source]
<<International1993,definition 3.14>>

_Guide_ Comment: The error of the result of a measurement (see <<scls_B-2-19>>) _may_ often be considered as arising from a number of random and systematic effects that contribute individual components of error to the error of the result. Also see the _Guide_ Comment to <<scls_B-2-19>> and to <<scls_B-2-3>>.


[[scls_B-2-23]]
==== correction

value added algebraically to the uncorrected result of a measurement to compensate for systematic error

NOTE: The correction is equal to the negative of the estimated systematic error.

NOTE: Since the systematic error cannot be known perfectly. the compensation cannot be complete.

// [VIM:1993, definition 3.15]
[.source]
<<International1993,definition 3.15>>


[[scls_B-2-24]]
==== correction factor

numerical factor by which the uncorrected result of a measurement is multiplied to compensate for systematic error

NOTE: Since the systematic error cannot be known perfectly, the compensation cannot be complete.

// [VIM:1993, definition 3.16]
[.source]
<<International1993,definition 3.16>>
