
[[annexG]]
[appendix]
== Degrees of freedom and levels of confidence

[[scls_G-1]]
=== Introduction

[[scls_G-1-1]]
==== {blank}

This annex addresses the general question of obtaining from the estimate stem:[y] of the measurand stem:[Y], and from the combined standard uncertainty stem:[u_{"c"}(y)] of that estimate, an expanded uncertainty stem:[U_p = k_p u_{"c"}(y)] that defines an interval stem:[y - U_p <= Y <= y + U_p] that has a high, specified coverage probability or level of confidence stem:[p]. It thus deals with the issue of determining the coverage factor stem:[k_p] that produces an interval about the measurement result stem:[y] that may be expected to encompass a large, specified fraction stem:[p] of the distribution of values that could reasonably be attributed to the measurand stem:[Y] (see <<cls_6>>).


[[scls_G-1-2]]
==== {blank}

In most practical measurement situations, the calculation of intervals having specified levels of confidence -- indeed, the estimation of most individual uncertainty components in such situations -- is at best only approximate. Even the experimental standard deviation of the mean of as many as 30 repeated observations of a quantity described by a normal distribution has itself an uncertainty of about 13 percent (see <<table_E-1>> in <<annexE>>).

In most cases, it does not make sense to try to distinguish between, for example, an interval having a level of confidence of 95 percent (one chance in 20 that the value of the measurand stem:[Y] lies outside the interval) and either a 94 percent or 96 percent interval (1 chance in 17 and 25, respectively). Obtaining justifiable intervals with levels of confidence of 99 percent (1 chance in 100) and higher is especially difficult, even if it is assumed that no systematic effects have been overlooked, because so little information is generally available about the most extreme portions or "tails" of the probability distributions of the input quantities.


[[scls_G-1-3]]
==== {blank}

To obtain the value of the coverage factor stem:[k_p] that produces an interval corresponding to a specified level of confidence stem:[p] requires detailed knowledge of the probability distribution characterized by the measurement result and its combined standard uncertainty. For example, for a quantity stem:[z] described by a normal distribution with expectation stem:[mu_z] and standard deviation stem:[sigma], the value of stem:[k_p] that produces an interval stem:[mu_z pm k_p sigma] that encompasses the fraction stem:[p] of the distribution, and thus has a coverage probability or level ofconfidence stem:[p], can be readily calculated. Some examples are given in <<table_G-1>>.


[[table_G-1]]
.Value of the coverage factor stem:[k_p] that produces an interval having level of confidence stem:[p] assuming a normal distribution
[cols="2*^"]
|===
| Level of confidence stem:[p] +
(percent) | Coverage factor stem:[k_p]

| stem:[68.27] | stem:[1]
| stem:[90] | stem:[1.645]
| stem:[95] | stem:[1.960]
| stem:[95.45] | stem:[2]
| stem:[99] | stem:[2.576]
| stem:[99.73] | stem:[3]
|===


NOTE: By contrast, if stem:[z] is described by a rectangular probability distribution with expectation stem:[mu_z] and standard deviation
stem:[sigma = a//sqrt(3)], where stem:[a] is the half-width of the distribution, the level of confidence stem:[p] is stem:[57.74] percent for stem:[k_p = 1]; 95 percent for
stem:[k_p = 1.65]; 99 percent for stem:[k_p = 1.71]; and 100 percent for stem:[k_p >= sqrt(3) ~~ 1.73]; the rectangular distribution is "narrower" than the
normal distribution in the sense that it is of finite extent and has no "tails".


[[scls_G-1-4]]
==== {blank}

If the probability distributions of the input quantities stem:[X_1,X_2,...,X_N] upon which the measurand stem:[Y] depends are known [their expectations, variances, and higher moments (see <<scls_C-2-13>> and <<scls_C-2-22>>) if the distributions are not normal distributions], and if stem:[Y] is a linear function of the input quantities, stem:[Y = c_1 X_1 + c_2 X_2 +...+ c_N X_N], then the probability distribution of stem:[Y] may be obtained by convolving the individual probability distributions <<DIETRICH1991>>. Values of stem:[k_p] that produce intervals corresponding to specified levels of confidence stem:[p] may then be calculated from the resulting convolved distribution.


[[scls_G-1-5]]
==== {blank}

If the functional relationship between stem:[Y] and its input quantities is nonlinear and a first-order Taylor series expansion of the relationship is not an acceptable approximation (see <<scls_5-1-2>> and <<scls_5-1-5>>), then the probability distribution of stem:[Y] cannot be obtained by convolving the distributions of the input quantities. In such cases, other analytical or numerical methods are required.


[[scls_G-1-6]]
==== {blank}

In practice, because the parameters characterizing the probability distributions of input quantities are usually estimates, because it is unrealistic to expect that the level of confidence to be associated with a given interval can be known with a great deal of exactness, and because of the complexity of convolving probability distributions, such convolutions are rarely, if ever, implemented when intervals having specified levels of confidence need to be calculated. Instead, approximations are used that take advantage of the Central Limit Theorem.


[[scls_G-2]]
=== Central Limit Theorem

[[scls_G-2-1]]
==== {blank}

If stem:[Y = c_1 X_1 + c_2 X_2 + ... + c_N X_N = sum_{i=1}^N c_i X_i] and all the stem:[X_i] are characterized by normal distributions, then the resulting convolved distribution of stem:[Y] will also be normal. However, even if the distributions of the stem:[X_i] are not normal, the distribution of stem:[Y] may often be approximated by a normal distribution because of the
Central Limit Theorem. This theorem states that the distribution of stem:[Y] will be _approximately normal_ with expectation stem:[E(Y)= sum_{i=1}^N c_i E(X_i)] and variance stem:[sigma^2 (Y) = sum_{i=1}^N  c_i^2 sigma^2(X_i)], where stem:[E(X_i)] is the expectation of stem:[X_i] and stem:[sigma^2(X_i)] is the variance of stem:[X_i], if the stem:[X_i] are independent and stem:[sigma^2(Y)] is much larger than any single component stem:[c_i^2 sigma^2(bar(X)_i)] from a non-normally distributed stem:[X_i].


[[scls_G-2-2]]
==== {blank}

The Central Limit Theorem is significant because it shows the very important role played by the variances of the probability distributions of the input quantities, compared with that played by the higher moments of the distributions, in determining the form of the resulting convolved distribution of stem:[Y]. Further, it implies that the convolved distribution converges towards the normal distribution as the number of input quantities contribut ing to stem:[sigma^2(Y)] increases; that the convergence will be more rapid the closer the values of stem:[c_i^2 sigma^2(bar(X)_i)] are to each other (equivalent in practice to each input estimate stem:[x_i] contribut ing a comparableuncertainty to the uncertainty of the estimate stem:[y] of the measurand stem:[Y]); and that the closer the distributions of the stem:[X_i] are to being normal, the fewer stem:[X_i] are required to yield a normal distribution for stem:[Y].

[example]
The rectangular distribution (see <<scls_4-3-7>> and <<scls_4-4-5>>) is an extreme example of a non-normal distribution, but the convolution of even as few as _three_ such distributions of equal width is approximately normal. If the half-width of each of the three rectangular distributions is stem:[a] so that the variance of each is stem:[a^2//3], the variance of the convolved distribution is stem:[sigma^2 = a^2]. The 95 percent and 99 percent intervals of the convolved distribution are defined by stem:[1.937 sigma] and stem:[2.379 sigma], respectively, while the corresponding intervals for a normal distribution with the same standard deviation stem:[sigma] are defined by stem:[1.960 sigma] and stem:[2.576 sigma] (see <<table_G-1>>) <<DIETRICH1991>>.

NOTE: For every interval with a level of confidence stem:[p] greater than about stem:[91.7] percent, the value of stem:[k_p] for a normal distribution is larger than the corresponding value for the distribution resulting from the convolution of any number and size of rectangular distributions.

NOTE: It follows from the Central Limit Theorem that the probability distribution of the arithmetic mean stem:[q] of stem:[n] observations stem:[q_k] of a random variable stem:[q] with expectation stem:[mu_q] and finite standard deviation stem:[sigma] approaches a normal distribution with mean stem:[mu_q] and standard deviation stem:[sigma//sqrt(n)] as stem:[n -> oo], whatever may be the probability distribution of stem:[q].


[[scls_G-2-3]]
==== {blank}

A practical consequence of the Central Limit Theorem is that when it can be established that its requirements are approximately met, in particular, if the combined standard uncertainty stem:[u_{"c"}(y)] is not dominated by a standard uncertainty component obtained from a Type A evaluation based on just a few observations, or by a standard uncertainty component obtained from a Type B evaluation based on an assumed rectangular distribution, a reasonable first approximation to calculating an expanded uncertainty stem:[U_p = k_p u_{"c"}(y)] that provides an interval with level of confidence stem:[p] is to use for stem:[k_p] a value from the normal distribution. The values most commonly used for this purpose are given in <<table_G-1>>.


[[scls_G-3]]
=== The stem:[t]-distribution and degrees of freedom

[[scls_G-3-1]]
==== {blank}

To obtain a better approximation than simply using a value of stem:[k_p] from the normal distribution as in <<scls_G-2-3>>, it must be recognized that the calculation of an interval having a specified level of confidence requires, not the distribution of the variable stem:[[Y-E(Y)\]//sigma(Y)], but the distribution of the variable stem:[(y - Y)//u_{"c"}(y)]. This is because in practice, all that is usually available are stem:[y], the estimate of stem:[Y] as obtained from stem:[y = sum_{i=1}^N c_i x_i], where stem:[x_i] is the estimate of stem:[X_i]; and the combined variance associated with stem:[y], stem:[u_{"c"}^2(y)], evaluated from stem:[u_{"c"}^2(y) = sum_{i=1}^N c_i^2 u^2(x_i)], where stem:[u(x_i)] is the standard uncertainty (estimated standard deviation) of the estimate stem:[x_i].

NOTE: Strictly speaking, in the expression stem:[(y - Y)//u_{"c"}(y)], stem:[Y] should read stem:[E(Y)]. For simplicity, such a distinction has only been made in a few places in this _Guide_. In general, the same symbol has been used for the physical quantity, the random variable that represents that quantity, and the expectation of that variable (see <<scls_4-1-1>>, notes).


[[scls_G-3-2]]
==== {blank}

If stem:[z] is a normally distributed random variable with expectation stem:[mu_z] and standard deviation stem:[sigma], and stem:[z] is the arithmetic mean of stem:[n] independent observations stem:[z_k] of stem:[z] with stem:[s(z)] the experimental standard deviation of stem:[z] [see <<eq_3>> and <<eq_5>>], then the distribution of the variable stem:[t = (bar(z) - mu_z)// s(bar(z))] is the stem:[t]-distribution or *Student's distribution* (<<scls_C-3-8>>) with stem:[v= n - 1] degrees of freedom.

Consequently, if the measurand stem:[Y] is simply a single normally distributed quantity stem:[X], stem:[Y = X]; and if stem:[X] is estimated by the arithmetic mean stem:[bar(X)] of stem:[n] independent repeated observations stem:[X_k] of stem:[X], with experimental standard deviation of the mean stem:[s(X)], then the best estimate of stem:[Y] is stem:[y = X] and the experimental standard deviation of that estimate is stem:[u_{"c"}(y) = s(bar(X))]. Then stem:[t = (bar(z) - mu_z)//s(bar(z)) = (bar(X) - X)//s(bar(X)) = (y - Y)//u_{"c"}(y)] is distributed according to the stem:[t]-distribution with

[stem]
++++
"Pr" [-t_p(v) <= t <= t_p] = p
++++

or

[stem]
++++
"Pr" [-t_p(v) <= (y - Y)//u_{"c"}(y) <= t_p(v)] = p
++++

which can be rewritten as

[stem]
++++
"Pr" [y - t_p(v) u_{"c"}(y) <= Y <= y + t_p(v) u_{"c"}(y)] = p
++++

In these expressions, stem:["Pr"[\]] means "probability of" and the stem:[t]-factor stem:[t_p(v)] is the value of stem:[t] for a given value of the parameter stem:[v] -- the degrees of freedom (see <<scls_G-3-3>>)-- such that the fraction stem:[p] of the stem:[t]-distribution is encompassed by the interval stem:[-t_p(v)] to stem:[+t_p(v)]. Thus the expanded uncertainty

[stem]
++++
U_p = k_p u_{"c"}(y) = t_p (v) u_{"c"}(y)
++++

defines an interval stem:[y - U_p] to stem:[y + U_p], conveniently written as stem:[Y = y pm U_p], that may be expected to encompass a fraction stem:[p] of the distribution of values that could reasonably be attributed to stem:[Y], and stem:[p] is the coverage probability or level of confidence of the interval.


[[scls_G-3-3]]
==== {blank}

The degrees of freedom stem:[v] is equal to stem:[n-1] for a single quantity estimated by the arithmetic mean of stem:[n] independent observations, as in <<scls_G-3-2>>. If stem:[n] independent observations are used to determine both the slopeand intercept of a straight line by the method of least squares, the degrees of freedom of their respective standard uncertainties is stem:[v = n - 2]. For a least-squares fit of stem:[m] parameters to stem:[n] data points, the degrees of freedom of the standard uncertainty of each parameter is stem:[v = n-m]. (See Reference <<BOX1978>> for a further discussion of degrees of freedom.)


[[scls_G-3-4]]
==== {blank}

Selected values of stem:[t_p(v)] for different values of stem:[v] and various values of stem:[p] are given in <<table_G-2>> at the end of this annex. As stem:[v -> oo] the stem:[t]-distribution approaches the normal distribution and stem:[t_p(v) ~~ (1 + 2//v)^{1//2} k_p], where in this expression stem:[k_p] is the coverage factor required to obtain an interval with level of confidence stem:[p] for a normally distributed variable. Thus the value of stem:[t_p(oo)] in <<table_G-2>> for a given stem:[p] equals the value of stem:[k_p] in <<table_G-1>> for the same stem:[p].

[NOTE]
====
Often, the stem:[t]-distribution is tabulated in quantiles; that is, values of the quantile stem:[t_{1-alpha}] are given, where stem:[1 - alpha] denotes the cumulative probability and the relation

[stem%unnumbered]
++++
1 - alpha = int_{-oo}^{t_1 - alpha} f(t,v)" d"t
++++

defines the quantile, where stem:[f] is the probability density function of stem:[t]. Thus stem:[t_p] and stem:[t_1 - alpha] are related by stem:[p = 1 - 2 alpha]. For example, the value of the quantile stem:[t_{0.975}], for which stem:[1 - alpha = 0.975] and stem:[alpha = 0.025], is the same as stem:[t_p(v)] for stem:[p = 0.95].
====


[[scls_G-4]]
=== Effective degrees of freedom

[[scls_G-4-1]]
==== {blank}

In general, the stem:[t]-distribution will not describe the distribution of the variable stem:[(y - Y)//u_{"c"}(y)] if stem:[u_{"c"}^2(y)] is the sum of two or more estimated variance components stem:[u_i^2(y) = c_i^2 u^2(x_i)] (see <<scls_5-1-3>>), even if each stem:[x_i] is the estimate of a normally distributed input quantity stem:[X_i]. However, the distribution of that variable may be approximated by a stem:[t]-distribution with an _effective_ degrees of freedom stem:[nu_{"eff"}] obtained from the
Welch-Satterthwaite formula <<WELCH1947>>, <<FAIRFIELD1936>>, <<SATTERTHWAITE1946>>

[[eq_G-2a]]
[stem]
++++
{u_{"c"}^4(y)}/{nu_{"eff"}} = sum_{i=1}^N {u_i^4(y)}/{nu_i}
++++

or

[[eq_G-2b]]
[stem]
++++
nu_{"eff"} = {u_{"c"}^4(y)}/{sum_{i=1}^N {u_i^4(y)}/{nu_i}}
++++

with

[[eq_G-2c]]
[stem]
++++
nu_{"eff"} <= sum_{i=1}^N nu_i
++++



where stem:[u_{"c"}^2(y) = sum_{i=1}^N u_i^2(y)] (see <<scls_5-1-3>>). The expanded uncertainty stem:[U_p = k_p u_{"c"}(y) = t_p (nu_{"eff"}) u_{"c"}(y)] then provides an
interval stem:[Y = y pm U_p] having an approximate level of confidence stem:[p].


NOTE: If the value of stem:[nu_{"eff"}] obtained from <<eq_G-2b>> is not an integer, which will usually be the case in practice, the corresponding value of stem:[t_p] may be found from <<table_G-2>> by interpolation or by truncating stem:[nu_{"eff"}] to the next lower integer.

NOTE: If an input estimate stem:[x_i] is itself obtained from two or more other estimates, then the value of stem:[nu_i] to be used with stem:[u_i^4(y) = [c_i^2 u^2(x_i)\]^2] in the denominator of <<eq_G-2b>> is the effective degrees of freedom calculated from anexpression equivalent to <<eq_G-2b>>.

[[note3_G-4-1]]
NOTE: Depending upon the needs of the potential users of a measurement result, it may be useful, in addition to stem:[nu_{"eff"}], to calculate and report also values for stem:[nu_{"effA"}] and stem:[nu_{"effB"}], computed from <<eq_G-2b>> treating separately the standard uncertainties obtained from Type A and Type B evaluations. If the contributions to stem:[u_{"c"}^2(y)] of the Type A and Type B standard uncertainties alone are denoted, respectively, by stem:[u_{"cA"}^2(y)] and stem:[u_{"cB"}^2(y)], the various quantities are related by

[stem%unnumbered]
++++
u_{"c"}^2(y) = u_{"cA"}^2(y) + u_{"cB"}^2(y)
++++

[stem%unnumbered]
++++
{u_{"c"}^4(y)}/{nu_{"eff"}} = {u_{"cA"}^4(y)}/{nu_{"effA"}} + {u_{"cB"}^4(y)}/{nu_{"effB"}}
++++


[example]
====
Consider that stem:[Y = f (X_1, X_2, X_3) = b X_1 X_2 X_3] and that the estimates stem:[x_1], stem:[x_2], stem:[x_3] of the normally distributed
input quantities stem:[X_1], stem:[X_2], stem:[X_3] are the arithmetic means of stem:[x_1 = 10], stem:[x_2 = 5], and stem:[x_3 = 15] independent repeated
observations, respectively, with relative standard uncertainties stem:[u(x_1)//x_1 = 0.25] percent, stem:[u(x_2)//x_2= 0.57] percent, and
stem:[u(x_3)//x_3 = 0.82] percent. In this case, stem:[c_i = partial f // partial X_i = Y // X_i] (to be evaluated at stem:[x_1], stem:[x_2], stem:[x_3] -- see <<scls_5-1-3>>, <<note1_5-1-3>>), stem:[[u_{"c"}(y)//y\]^2 = sum_{i=1}^3 [u(x_i)//x_i\]^2 = (1.03" "rm(percent))^2] (see <<note2_5-1-6>>), and <<eq_G-2b>> becomes

[stem%unnumbered]
++++
nu_{"eff"} = {[u_{"c"}(y)//y]^4}/{sum_{i=1}^3 {[u(x_i)//x_i]^4}/{nu_i}}
++++

Thus

[stem%unnumbered]
++++
nu_{"eff"} = {1.03^4}/{{0.25^4}/{10-1} + {0.57^4}/{5-1} + {0.82^4}/{15-1}} = 19.0
++++

The value of stem:[t_p] for stem:[p = 95] percent and stem:[v = 19] is, from <<table_G-2>>, stem:[t_{95}(19) = 2.09]; hence the relative expanded uncertainty for this level of confidence is stem:[U_{95} = 2.09 xx (1.03" "rm(percent)) = 2.2" "rm(percent)]. It may then be stated that stem:[Y = y pm U_{95} = y(1 pm 0.022)] (stem:[y] to be determined from stem:[y = b x_1 x_2 x_3]), or that stem:[0.978 y <= Y <= 1.022 y], and that the level of confidence to be associated with the interval is approximately 95 percent.
====


[[scls_G-4-2]]
==== {blank}

In practice, stem:[u_{"c"}(y)] depends on standard uncertainties stem:[u(x_i)] of input estimates of both normally and non-normally distributed input quantities, and the stem:[u(x_i)] are obtained from both frequency-based and _a priori_ probability distributions (that is, from both Type A and Type B evaluations). A similar statement applies to the estimate stem:[y] and input estimates stem:[x_i] upon which stem:[y] depends. Nevertheless, the probability distribution of the function stem:[t = (y - Y)//u_{"c"}(y)] can be approximated by the stem:[t]-distribution if it is expanded in a Taylor series about its expectation. In essence, this is what is achieved, in the lowest order approximation, by the Welch-Satterthwaite formula, <<eq_G-2a>> or <<eq_G-2b>>.

The question arises as to the degrees of freedom to assign to a standard uncertainty obtained from a Type B evaluation when stem:[nu_{"eff"}] is calculated from <<eq_G-2b>>. Since the appropriate definition of degrees of freedom recognizes that stem:[v] as it appears in the stem:[t]-distribution is a measure of the uncertainty of the variance stem:[s^2(bar(z))], <<eq_E-7>> in <<scls_E-4-3>> may be used to define the degrees of freedom stem:[nu_i],

[[eq_G-3]]
[stem]
++++
nu_i ~~ 1/2 {u^2(x_i)}/{sigma^2 [u(x_i)]} ~~ 1/2 [{Delta u(x_i)}/{u(x_i)}]^{-2}
++++

The quantity in large brackets is the relative uncertainty of stem:[u(x_i)]; for a Type B evaluation of standard uncertainty it is a subjective quantity whose value is obtained by scientific judgement based on the pool of available information.

[[example_G-4-2]]
[example]
Consider that one's knowledge of how input estimate stem:[x_i] was determined and how its standard uncertainty stem:[u(x_i)] was evaluated leads one to judge that the value of stem:[u(x_i)] is reliable to about 25 percent. This may be taken to mean that the relative uncertainty is stem:[Delta u(x_i)//u(x_i) = 0.25], and thus from <<eq_G-3>>, stem:[nu_i = (0.25)^{-2}//2 = 8]. If instead one had judged the value of stem:[u(x_i)] to be reliable to only about 50 percent, then stem:[nu_i = 2]. (See also <<table_E-1>> in <<annexE>>.)


[[scls_G-4-3]]
==== {blank}

In the discussion in <<scls_4-3>> and <<scls_4-4>> of Type B evaluation of standard uncertainty from an _a priori_ probability distribution, it was implicitly assumed that the value of stem:[u(x_i)] resulting from such an evaluation is exactly known. For example, when stem:[u(x_i)] is obtained from a rectangular probability distribution of assumed half-width stem:[a = (a_+ - a_-)//2] as in <<scls_4-3-7>> and <<scls_4-4-5>>, stem:[u(x_i) = a//sqrt(3)] is viewed as a constant with no uncertainty because stem:[a_+] and stem:[a_-], and thus stem:[a], are so viewed (but see <<note2_4-3-9>>). This implies through <<eq_G-3>> that stem:[nu_i -> oo] or stem:[1//nu_i -> 0], but it causes no difficulty in evaluating <<eq_G-2b>>. Further, assuming that stem:[nu_i -> oo] is not necessarily unrealistic; it is common practice to choose stem:[a_-] and stem:[a_+] in such a way that the probability of the quantity in question lying outside the interval stem:[a_-] to stem:[a_+] is extremely small.


[[scls_G-5]]
=== Other considerations

[[scls_G-5-1]]
==== {blank}

An expression found in the literature on measurement uncertainty and often used to obtain an uncertainty that is intended to provide an interval with a 95 percent level of confidence may be written as

[[eq_G-4]]
[stem]
++++
U'_{95} = [t_{95}^2 (v'_{"eff"})s^2 + 3u^2]^{1//2}
++++


Here stem:[t_{95}(v'_{"eff"})] is taken from the stem:[t]-distribution for stem:[v'_{"eff"}] degrees of freedom and stem:[p = 95] percent; stem:[v'_{"eff"}] is the
effective degrees of freedom calculated from the Welch-Satterthwaite formula [<<eq_G-2b>>] taking into
account _only_ those standard uncertainty components stem:[s] that have been evaluated statistically from repeated observations in the _current_ measurement; stem:[s^2 = sum c_i^2 s_i^2]; stem:[c_i -= partial f//partial x_i]; and stem:[u^2 = sum u_j^2(y) = sum c_j^2 (a_j^2//3)] accounts for _all_ other components of uncertainty, where stem:[+a_j] and stem:[-a_j] are the assumed exactly known upper and lower bounds of stem:[X_j] relative to its best estimate stem:[x_j] (that is, stem:[x_j - a_j <= X_j <= x_j + a_j]).

NOTE: A component based on repeated observations made _outside_ the current measurement is treated in the same way as any other component included in stem:[u^2]. Hence, in order to make a meaningful comparison between <<eq_G-4>> and <<eq_G-5>> of the following subclause, it is assumed that such components, if present, are negligible.


[[scls_G-5-2]]
==== {blank}

If an expanded uncertainty that provides an interval with a 95 percent level of confidence is evaluated according to the methods recommended in <<scls_G-3>> and <<scls_G-4>>, the resulting expression in place of <<eq_G-4>> is

[[eq_G-5]]
[stem]
++++
U_{95} = t_{95} (nu_{"eff"})(s^2 + u^2)^{1//2}
++++

where stem:[nu_{"eff"}] is calculated from <<eq_G-2b>> and the calculation includes _all_ uncertainty components.

In most cases, the value of stem:[U_{95}] from <<eq_G-5>> will be larger than the value of stem:[U'_{95}] from <<eq_G-4>>, if it is assumed that in evaluating <<eq_G-5>>, all Type B variances are obtained from _a priori_ rectangular distributions with half-widths that are the same as the bounds stem:[a_j] used to compute stem:[u^2] of <<eq_G-4>>. This may be understood by recognizing that, although stem:[t_{95}(v'_{"eff"})] will in most cases be somewhat larger than stem:[t_{95}(nu_{"eff"})], both factors are close to 2; and in <<eq_G-5>> stem:[u^2] is multiplied by stem:[t_p^2(nu_{"eff"}) ~~ 4] while in <<eq_G-4>> it is multiplied by 3. Although the two expressions yield equal values of stem:[U'_{95}] and stem:[U_{95}] for stem:[u^2 << s^2], stem:[U'_{95}] will be as much as 13 percent smaller than stem:[U_{95}] if stem:[u^2 " >> " s^2]. Thus in general, <<eq_G-4>> yields an uncertainty that provides an interval having a _smaller_ level of confidence than the interval provided by the expanded uncertainty calculated from <<eq_G-5>>.

NOTE: In the limits stem:[u^2//s^2 -> oo] and stem:[nu_{"eff"} -> oo], stem:[U'_{95} -> 1.732u] while stem:[U_{95} -> 1.960u]. In this case, stem:[U'_{95}] provides an interval having only a stem:[91.7] percent level of confidence, while stem:[U_{95}] provides a 95 percent interval. This case is approximated in practice when the components obtained from estimates of upper and lower bounds are dominant, large in number, and have values of stem:[u_j^2(y) = c_j^2 a_j^2//3] that are of comparable size.

NOTE: For a normal distribution, the coverage factor stem:[k = 3 ~~ 1.732] provides an interval with a level of confidence stem:[p = 91.673]... percent. This value of stem:[p] is robust in the sense that it is, in comparison with that of any other value, optimally independent of small deviations of the input quantities from normality.


[[scls_G-5-3]]
==== {blank}

Occasionally an input quantity stem:[X_i] is distributed asymmetrically -- deviations about its expected value of one sign are more probable than deviations of the opposite sign (see <<scls_4-3-8>>). Although this makes no difference in the evaluation of the standard uncertainty stem:[u(x_i)] of the estimate stem:[x_i] of stem:[X_i], and thus in the evaluation of stem:[u_{"c"}(y)], it may affect the calculation of stem:[U].

It is usually convenient to give a symmetric interval, stem:[Y = y pm U], unless the interval is such that there is a cost differential between deviations of one sign over the other. If the asymmetry of stem:[X_i] causes only a small asymmetry in the probability distribution characterized by the measurement result stem:[y] and its combined standard uncertainty stem:[u_{"c"}(y)], the probability lost on one side by quoting a symmetric interval is compensated by the probability gained on the other side. The alternative is to give an interval that is symmetric in probability (and thus asymmetric in stem:[U]): the probability that stem:[Y] lies below the lower limit stem:[y - U_-] is equal to the probability that stem:[Y] lies above the upper limit stem:[y + U_+]. But in order to quote such limits, more information than simply theestimates stem:[y] and stem:[u_{"c"}(y)] [and hence more information than simply the estimates stem:[x_i] and stem:[u(x_i)] of each input quantity stem:[X_i]] is needed.


[[scls_G-5-4]]
==== {blank}

The evaluation of the expanded uncertainty stem:[U_p] given here in terms of stem:[u_{"c"}(y)], stem:[nu_{"eff"}], and the factor stem:[t _p (nu_{"eff"})] from the stem:[t]-distribution is only an approximation, and it has its limitations. The distribution of stem:[(y - Y)//u_{"c"}(y)] is given by the stem:[t]-distribution only if the distribution of stem:[Y] is normal, the estimate stem:[y] and its combined standard uncertainty stem:[u_{"c"}(y)] are independent, and if the distribution of stem:[u_{"c"}^2(y)] is a stem:[χ^2] distribution. The introduction of stem:[nu_{"eff"}], <<eq_G-2b>>, deals only with the latter problem, and provides an approximately stem:[χ^2] distribution for stem:[u_{"c"}^2(y)]; the other part of the problem, arising from the non-normality of the distribution of stem:[Y], requires the consideration
of higher moments in addition to the variance.


[[scls_G-6]]
=== Summary and conclusions

[[scls_G-6-1]]
==== {blank}

The coverage factor stem:[k_p] that provides an interval having a level of confidence stem:[p] close to a specified level can only be found if there is extensive knowledge of the probability distribution of each input quantity and if these distributions are combined to obtain the distribution of the output quantity. The input estimates stem:[x_i] and their standard uncertainties stem:[u(x_i)] by themselves are inadequate for this purpose.


[[scls_G-6-2]]
==== {blank}

Because the extensive computations required to combine probability distributions are seldom justified by the extent and reliability of the available information, an approximation to the distribution of the output quantity is acceptable. Because of the Central Limit Theorem, it is usually sufficient to assume that the probability distribution of stem:[(y-Y)//u_{"c"}(y)] is the stem:[t]-distribution and take stem:[k_p = t_p(nu_{"eff"})], with the stem:[t]-factor based on an effective degrees of freedom stem:[nu_{"eff"}] of stem:[u_{"c"}(y)] obtained from the Welch-Satterthwaite formula, <<eq_G-2b>>.


[[scls_G-6-3]]
==== {blank}

To obtain stem:[nu_{"eff"}] from <<eq_G-2b>> requires the degrees of freedom stem:[nu_i] for each standard uncertainty component. For a component obtained from a Type A evaluation, stem:[nu_i] is obtained from the number of independent repeated observations upon which the corresponding input estimate is based and the number of independent quantities determined from those observations (see <<scls_G-3-3>>). For a component obtained from a Type B evaluation, stem:[nu_i] is obtained from the judged reliability of the value of that component [see <<scls_G-4-2>> and <<eq_G-3>>].


[[scls_G-6-4]]
==== {blank}

Thus the following is a summary of the preferred method of calculating an expanded uncertainty stem:[U_p = k_p u_{"c"}(y)] intended to provide an interval stem:[Y = y pm U_p] that has an approximate level of confidence stem:[p]:

. Obtain stem:[y] and stem:[u_{"c"}(y)] as described in <<cls_4>> and <<cls_5>>.

. Compute stem:[nu_{"eff"}] from the Welch-Satterthwaite formula, <<eq_G-2b>> (repeated here for easy reference)
+
--
[stem]
++++
nu_{"eff"} = {u_{"c"}^4(y)}/{sum_{i=1}^N {u_i^4(y)}/{nu_i}}
++++

If stem:[u(x_i)] is obtained from a Type A evaluation, determine stem:[nu_i] as outlined in <<scls_G-3-3>>. If stem:[u(x_i)] is obtained from a Type B evaluation and it can be treated as exactly known, which is often the case in practice, stem:[nu_i -> oo]; otherwise, estimate stem:[nu_i] from <<eq_G-3>>.
--

. Obtain the stem:[t]-factor stem:[t_p (nu_{"eff"})] for the desired level of confidence stem:[p] from <<table_G-2>>. If stem:[nu_{"eff"}] is not an integer, either interpolate or truncate stem:[nu_{"eff"}] to the next lower integer.
. Take stem:[k_p = t_p (nu_{"eff"})] and calculate stem:[U_p = k_p u_{"c"}(y)].


[[scls_G-6-5]]
==== {blank}

In certain situations, which should not occur too frequently in practice, the conditions required by the Central Limit Theorem may not be well met and the approach of <<scls_G-6-4>> may lead to an unacceptable result. For example, if stem:[u_{"c"}(y)] is dominated by a component of uncertainty evaluated from a rectangular distribution
whose bounds are assumed to be exactly known, it is possible [if stem:[t_p (nu_{"eff"}) > sqrt(3)]] that stem:[y + U_p] and stem:[y - U_p], the upper and lower limits of the interval defined by stem:[U_p], could lie outside the bounds of the probability distribution of the output quantity stem:[Y]. Such cases must be dealt with on an individual basis but are often amenable to an approximate analytic treatment (involving, for example, the convolution of a normal distribution with a rectangular distribution <<DIETRICH1991>>).


[[scls_G-6-6]]
==== {blank}

For many practical measurements in a broad range of fields, the following conditions prevail:

the estimate stem:[y] of the measurand stem:[Y] is obtained from estimates stem:[x_i] of a significant number of input quantities stem:[X_i] that are describable by well-behaved probability distributions, such as the normal and rectangulardistributions;

the standard uncertainties stem:[u(x_i)] of these estimates, which may be obtained from either Type A or Type B evaluations, contribute comparable amounts to the combined standard uncertainty stem:[u_{"c"}(y)] of the measurement result stem:[y];

the linear approximation implied by the law of propagation of uncertainty is adequate (see <<scls_5-1-2>> and <<scls_E-3-1>>);

the uncertainty of stem:[u_{"c"}(y)] is reasonably small because its effective degrees of freedom stem:[nu_{"eff"}] has a significant magnitude, say greater than 10.

Under these circumstances, the probability distribution characterized by the measurement result and its combined standard uncertainty can be assumed to be normal because of the Central Limit Theorem; and stem:[u_{"c"}(y)] can be taken as a reasonably reliable estimate of the standard deviation of that normal distribution because of the significant size of stem:[nu_{"eff"}]. Then, based on the discussion given in this annex, including that emphasizing the approximate nature of the uncertainty evaluation process and the impracticality of trying to distinguish between intervals having levels of confidence that differ by one or two percent, one may do the following:

* adopt stem:[k = 2] and assume that stem:[U = 2 u_{"c"}(y)] defines an interval having a level of confidence of approximately 95 percent;

or, for more critical applications,

* adopt stem:[k = 3] and assume that stem:[U = 3 u_{"c"}(y)] defines an interval having a level of confidence of approximately 99 percent.

Although this approach should be suitable for many practical measurements, its applicability to any particular measurement will depend on how close stem:[k = 2] must be to stem:[t_{95}(nu_{"eff"})] or stem:[k = 3] must be to stem:[t_{99}(nu_{"eff"})]; that is, on how close the level of confidence of the interval defined by stem:[U = 2 u_{"c"}(y)] or stem:[U = 3 u_{"c"}(y)] must be to 95 percent or 99 percent, respectively. Although for stem:[nu_{"eff"} = 11], stem:[k = 2] and stem:[k = 3] underestimate t_{95}(11) and t_{99}(11) by only about 10 percent and 4 percent, respectively (see <<table_G-2>>), this may not be acceptable in some cases. Further, for all values of stem:[nu_{"eff"}] somewhat larger than 13, stem:[k = 3] produces an interval having a level of confidence larger than 99 percent. (See <<table_G-2>>, which also shows that for stem:[nu_{"eff"} -> oo] the levels of confidence of the intervals produced by stem:[k= 2] and stem:[k = 3] are stem:[95.45] percent and 99.73 percent, respectively). Thus, in practice, the size of stem:[nu_{"eff"}] and what is required of the expanded uncertainty will determine whether this approach can be used.


[[table_G-2]]
.Value of stem:[t_p(v)] from the stem:[t]-distribution for degrees of freedom stem:[v] that defines an interval stem:[-t_p(v)] to stem:[+t_p(v)] that encompasses the fraction stem:[p] of the distribution
[cols="7*^"]
|===
.2+h| Degrees of freedom +
stem:[v]
6+h| Fraction stem:[p] in percent

h| stem:[68.27] footnote:noteG2[For a quantity stem:[z] described by a normal distribution with expectation stem:[mu_z] and standard deviation stem:[sigma], the interval stem:[mu_z pm k sigma] encompasses stem:[p = 68.27] percent, stem:[95.45] percent and stem:[99.73] percent of the distribution for stem:[k = 1], 2 and 3, respectively.] h| 90 h| 95 h| stem:[95.45] footnote:noteG2[] h| 99 h| stem:[99.73] footnote:noteG2[]

| 1 | stem:[1.84] | stem:[6.31] | stem:[12.71] | stem:[13.97] | stem:[63.66] | stem:[235.80]
| 2 | stem:[1.32] | stem:[2.92] | stem:[4.30] | stem:[4.53] | stem:[9.92] | stem:[19.21]
| 3 | stem:[1.20] | stem:[2.35] | stem:[3.18] | stem:[3.31] | stem:[5.84] | stem:[9.22]
| 4 | stem:[1.14] | stem:[2.13] | stem:[2.78] | stem:[2.87] | stem:[4.60] | stem:[6.62]
| 5 | stem:[1.11] | stem:[2.02] | stem:[2.57] | stem:[2.65] | stem:[4.03] | stem:[5.51]
7+|&nbsp;
| 6 | stem:[1.09] | stem:[1.94] | stem:[2.45] | stem:[2.52] | stem:[3.71] | stem:[4.90]
| 7 | stem:[1.08] | stem:[1.89] | stem:[2.36] | stem:[2.43] | stem:[3.50] | stem:[4.53]
| 8 | stem:[1.07] | stem:[1.86] | stem:[2.31] | stem:[2.37] | stem:[3.36] | stem:[4.28]
| 9 | stem:[1.06] | stem:[1.83] | stem:[2.26] | stem:[2.32] | stem:[3.25] | stem:[4.09]
| 10 | stem:[1.05] | stem:[1.81] | stem:[2.23] | stem:[2.28] | stem:[3.17] | stem:[3.96]
| 11 | stem:[1.05] | stem:[1.80] | stem:[2.20] | stem:[2.25] | stem:[3.11] | stem:[3.85]
| 12 | stem:[1.04] | stem:[1.78] | stem:[2.18] | stem:[2.23] | stem:[3.05] | stem:[3.76]
| 13 | stem:[1.04] | stem:[1.77] | stem:[2.16] | stem:[2.21] | stem:[3.01] | stem:[3.69]
| 14 | stem:[1.04] | stem:[1.76] | stem:[2.14] | stem:[2.20] | stem:[2.98] | stem:[3.64]
| 15 | stem:[1.03] | stem:[1.75] | stem:[2.13] | stem:[2.18] | stem:[2.95] | stem:[3.59]
7+|&nbsp;
| 16 | stem:[1.03] | stem:[1.75] | stem:[2.12] | stem:[2.17] | stem:[2.92] | stem:[3.54]
| 17 | stem:[1.03] | stem:[1.74] | stem:[2.11] | stem:[2.16] | stem:[2.90] | stem:[3.51]
| 18 | stem:[1.03] | stem:[1.73] | stem:[2.10] | stem:[2.15] | stem:[2.88] | stem:[3.48]
| 19 | stem:[1.03] | stem:[1.73] | stem:[2.09] | stem:[2.14] | stem:[2.86] | stem:[3.45]
| 20 | stem:[1.03] | stem:[1.72] | stem:[2.09] | stem:[2.13] | stem:[2.85] | stem:[3.42]
7+|&nbsp;
| 25 | stem:[1.02] | stem:[1.71] | stem:[2.06] | stem:[2.11] | stem:[2.79] | stem:[3.33]
| 30 | stem:[1.02] | stem:[1.70] | stem:[2.04] | stem:[2.09] | stem:[2.75] | stem:[3.27]
| 35 | stem:[1.01] | stem:[1.70] | stem:[2.03] | stem:[2.07] | stem:[2.72] | stem:[3.23]
| 40 | stem:[1.01] | stem:[1.68] | stem:[2.02] | stem:[2.06] | stem:[2.70] | stem:[3.20]
| 45 | stem:[1.01] | stem:[1.68] | stem:[2.01] | stem:[2.06] | stem:[2.69] | stem:[3.18]
7+|&nbsp;
| 50 | stem:[1.01] | stem:[1.68] | stem:[2.01] | stem:[2.05] | stem:[2.68] | stem:[3.16]
| 100 | stem:[1.005] | stem:[1.660] | stem:[1.984] | stem:[2.025] | stem:[2.626] | stem:[3.077]
| stem:[oo] | stem:[1.000] | stem:[1.645] | stem:[1.960] | stem:[2.000] | stem:[2.576] | stem:[3.000]
|===
