
[[bibliography]]
[bibliography]
== Bibliography

* [[[CIPM1980,1]]], CIPM (1980), _BIPM Proc.-Verb. Com. Int. Poids et Mesures_ *48*, C1-C30 (in French); BIPM (1980), Rapport BIPM-80/3, _Report on the BIPM enquiry on error statements_, Bur. Intl. Poids et Mesures (Sèvres, France) (in English)

* [[[KAARLS1981,2]]], KAARLS, R. (1981), _BIPM Proc.-Verb. Com. Int. Poids et Mesures_ *49*, A1-A12 (in French); Giacomo, P. (1981), _Metrologia_ *17*, 73 -74 (in English)

NOTE: The English translation of Recommendation INC-1 (1980) given in the <<cls_0>> to this _Guide_ (see <<scls_0-7>>) is that of the final version of the Recommendation and is taken from a BIPM internal report. It is consisfent with the authoritative French text of the Recommendation given in _BIPM Proc.-Verb. Com. Int. Poids et Mesures_ *49* and reproduced in <<scls_A-1>>, <<annexA>> of this _Guide_. The English translation of Recommendation INC-1 (1980) given in _Metrologia_ *17* is that of a draft and differs slightly from the translation given in the BIPM internal report and thus in <<scls_0-7>>.

* [[[CIPM1982,3]]], CIPM (1981), _BIPM Proc.-Verb. Com. Int. Poids et Mesures_ *49*, 8-9, 26 (in French); Giacomo, P. (1982), _Metrologia_ *18*, 43-44 (in English)

* [[[CIPM1987,4]]], CIPM (1986), _BIPM Proc.-Verb. Com. Int. Poids et Mesures_ *54*, 14, 35 (in French); Giacomo, P. (1987), _Metrologia_ *24*, 49-50 (in English)

* [[[ISO1986,5]]], ISO 5725:1986, _Precision of test methods -- Determination of repeatability and reproducibility for a standard test method by inter-laboratory tests_, International Organization for Standardization (Geneva,Switzerland)

NOTE: This standard is currently footnote:[*Footnote to the 2008 version:* ISO 5725:1986 has been replaced by a series of six parts. ISO 5725 consists of the following parts, under the general title _Accuracy (trueness and precision) of measurement methods and results_: _Part 1: General principles and definitions_ _Part 2: Basic method for the determination of repeatability and reproducibility of a standard measurement method_ _Part 3: Intermediate measures of the precision of a standard measurement method_ _Part 4: Basic methods for the determination of the trueness of a standard measurement method_ _Part 5: Alternative methods for the determination of the precision of a standard measurement method_ _Part 6: Use in practice of accuracy values_] being revised. The revision has a new title, "Accuracy (trueness and precision) of measurement methods and results", and it is composed of six parts.

* [[[International1993,6]]], _International vocabulary of basic and general terms in metrology_, second edition, 1993, footnote:[*Footnote to the 2008 version:* The third edition of the vocabulary was published in 2008, under the title JCGM 200:2008, _International vocabulary of metrology -- Basic and general concepts and associated terms (VIM)_.] InternationalOrganization for Standardization (Geneva, Switzerland)

The abbreviation of the title of this vocabulary is VIM.

NOTE: The definitions of terms given in <<annexB>> are taken from the revised English text of the VIM in its final form prior to publication.

NOTE: The second edition of the VIM was published by the International Organization for Standardization (ISO) in the name of the following seven organizations that participate in the work of ISO Technical Advisory Group 4 (TAG 4), the group that supported the development of the VIM: the Bureau International des Poids et Mesures (BIPM), the International Electrotechnical Commission (IEC), the International Federation of Clinical Chemistry (IFCC), ISO, the International Union of Pure and Applied Chemistry (IUPAC), the International Union of Pure and Applied Physics (IUPAP), and the International Organization of Legal Metrology (OIML).

NOTE: The first edition of the VIM was published by ISO in 1984 in the name of the BIPM, IEC, ISO, and OIML.



* [[[ISO_3534-1,7]]], ISO 3534-1:1993, footnote:[*Footnote to the 2008 version:* +
ISO 3534-1:2006 cancels and replaces ISO 3534-1:1993. Note that some of the terms and definitions have been revised. +
For further information, see the latest edition.] _Statistics -- Vocabulary and symbols -- Part 1: Probability and general statistical terms_, International Organization for Standardization (Geneva, Switzerland)

* [[[FULLER1987,8]]], FULLER, W.A. (1987), _Measurement error models_, John Wiley (New York, N.Y.)

* [[[ALLAN1987,9]]], ALLAN, D.W. (1987), _IEEE Trans. Instrum. Meas._ *IM-36*, 646-654

* [[[DIETRICH1991,10]]], DIETRICH, C.F. (1991), _Uncertainty, calibration and probability_, second edition, Adam-Hilger (Bristol)

* [[[M1979,11]]], MÜLLER, J.W. (1979), _Nucl. Instrum. Meth._ *163*, 241-251

* [[[M1984,12]]], MÜLLER, J.W. (1984), in _Precision measurement and fundamental constants II_, Taylor, B. N., and Phillips, W. D., eds., Natl. Bur. Stand. (U.S.) Spec. Publ. 617, US GPO (Washington, D.C.), 375-381

* [[[JEFFREYS1983,13]]], JEFFREYS, H. (1983), _Theory of probability_, third edition, Oxford University Press (Oxford)

* [[[PRESS1989,14]]], PRESS, S.J. (1989), _Bayesian statistics: principles, models, and applications_, John Wiley (New York, N.Y.)

* [[[BOX1978,15]]], BOX, G.E.P., HUNTER, W.G., and HUNTER, J.S. (1978), _Statistics for experimenters_, John Wiley (New York, N.Y.)

* [[[WELCH1947,16]]], WELCH, B.L. (1936), _J. R. Stat. Soc. Suppl._ *3*, 29-48; (1938), _Biometrika_ *29*, 350-362; (1947), _ibid._ *34*, 28-35

* [[[FAIRFIELD1936,17]]], FAIRFIELD-SMITH, H. (1936), _J. Counc. Sci. Indust. Res. (Australia)_ *9*(3), 211

* [[[SATTERTHWAITE1946,18]]], SATTERTHWAITE, F.E. (1941), _Psychometrika_ *6*, 309-316; (1946) _Biometrics Bull._ *2*(6), 110-114

* [[[ISO1989,19]]], ISO Guide 35:1989, footnote:[*Footnote to the 2008 version:* +
ISO Guide 35:2006 cancels and replaces ISO Guide 35:1989. For further information, see the latest edition.] _Certification of reference materials -- General and statistical principles_, second edition, International Organization for Standardization (Geneva, Switzerland)

* [[[BARKER1985,20]]], BARKER, T.B. (1985), _Quality by experimental design_, Marcel Dekker (New York, N.Y.)
