
[[cls_7]]
== Implementation of a Monte Carlo method

[[scls_7-1]]
=== General

This clause gives information about the implementation of a Monte Carlo method for the propagation of distributions: see the procedure given in <<scls_5-9-6>> and shown diagrammatically in <<fig4>>.


[[scls_7-2]]
=== Number of Monte Carlo trials

==== {blank}

A value of stem:[M], the number of Monte Carlo trials, i.e. the number of model evaluations to be made, needs to be selected. It can be chosen a priori, in which case there will be no direct control over the quality of the numerical results provided by MCM. The reason is that the number of trials needed to provide these results to a prescribed numerical tolerance will depend on the "shape" of the PDF for the output quantity and on the coverage probability required. Also, the calculations are stochastic in nature, being based on random sampling.

NOTE: A value of stem:[ii(M) = 10^6] can often be expected to deliver a 95 % coverage interval for the output quantity such that this length is correct to one or two significant decimal digits.


==== {blank}

The choice of a value of stem:[M] that is large compared with stem:[1//(1-p)], e.g. stem:[ii(M)] at least stem:[10^4] times greater than stem:[1//(1-p)], should be made. It can then be expected that G will provide a reasonable discrete representation of stem:[G_Y (eta)] in the regions near the endpoints of a stem:[100p " %"] coverage interval for stem:[ii(Y)].


==== {blank}

Because there is no guarantee that this or any specific pre-assigned number will suffice, a procedure that selects stem:[ii(M)] adaptively, i.e. as the trials progress, can be used. Some guidance in this regard is available <<Berthouex1994>>. Subclause <<scls_7-9>> provides such a procedure, a property of which is that the number of trials taken is economically consistent with the expectation of achieving a required numerical tolerance.

NOTE: If the model is complicated, e.g. involving the solution of a finite-element model, because of large computing times it may not be possible to use a sufficiently large value of stem:[ii(M)] to obtain adequate distributional knowledge of the output quantity. In such a case an approximate approach would be to regard stem:[g_Y (eta)] as Gaussian (as in the GUM) and proceed as follows. A relatively small value of stem:[ii(M)], 50 or 100, for example, would be used. The average and standard deviation of the resulting stem:[ii(M)] model values of stem:[ii(Y)] would be taken as stem:[y] and stem:[u(y)], respectively. Given this information, a Gaussian PDF stem:[g_Y(eta) = N(y,u^2(y))] would be assigned to characterize the knowledge of stem:[ii(Y)] (see <<scls_6-4-7>>) and a desired coverage interval for stem:[ii(Y)] calculated. Although this use of a small value of stem:[ii(M)] is inevitably less reliable than that of a large value in that it does not provide an approximation to the PDF for stem:[ii(Y)], it does take account of model non-linearity.


[[scls_7-3]]
=== Sampling from probability distributions

In an implementation of MCM, stem:[ii(M)] vectors stem:[bb(x)_r], stem:[r = 1,...,ii(M)] (see <<scls_7-2>>), are drawn from the PDFs stem:[g_{X_i} (xi_i)] for the N input quantities stem:[X_i]. Draws would be made from the joint (multivariate) PDF stem:[g_X (xi)] if appropriate. Recommendations concerning the manner in which this sampling can be carried out are given in <<annexC>>for the commonest distributions, viz. the rectangular, Gaussian, stem:[t], and multivariate Gaussian. Also see <<scls_6-4>>. It is possible to draw at random from any other distribution. See <<scls_C-2>>. Some such distributions could be approximations to distributions based on Monte Carlo results from a previous uncertainty calculation (see <<scls_6-5>>, <<scls_7-5>> and <<annexD>>).

NOTE: For the results of MCM to be statistically valid, it is necessary that the pseudo-random number generators used to draw from the distributions required have appropriate properties. Some tests of randomness of the numbers produced by a generator are indicated in <<scls_C-3-2>>.


[[scls_7-4]]
=== Evaluation of the model

[[scls_7-4-1]]
==== {blank}

The model is evaluated for each of the stem:[ii(M)] draws from the PDFs for the N input quantities. Specifically, denote the stem:[ii(M)] draws by stem:[bb(x)_1,...,bb(x)_M], where the __r__th draw stem:[bb(x)_r] contains stem:[x_{1,r},..., x_{N,r}], with stem:[x_{i,r}] a draw from the PDF for stem:[X_i]. Then, the model values are

[stem%unnumbered]
++++
y_r = f(bb(x)_r), r = 1,...,ii(M).
++++


==== {blank}

The necessary modifications are made to <<scls_7-4-1>> if the stem:[X_i] are not independent and hence a joint PDF is assigned to them.

NOTE: Model and derivative evaluations are made when applying the law of propagation of uncertainty, using exact derivatives, at the best estimates of the input quantities. Model evaluations only are made when applying the law of propagation of uncertainty when numerical (finite-difference) approximations to derivatives are used. These evaluations are made, if the GUM recommendation <<JCGM-100,clause=5.1.3 note 2>> is adopted, at the best estimates of the input quantities and at points perturbed by stem:[+-] one standard uncertainty from each estimate in turn. With MCM, model evaluations are made in the neighbourhood of these best estimates, viz. at points that can be expected to be up to several standard uncertainties away from these estimates. The fact that model evaluations are made at different points according to the approach used may raise issues regarding the numerical procedure used to evaluate the model, e.g. ensuring its convergence (where iterative schemes are used) and numerical stability. The user should ensure that, where appropriate, the numerical methods used to evaluate stem:[f] are valid for a sufficiently large region containing these best estimates. Only occasionally would it be expected that this aspect is critical.


[[scls_7-5]]
=== Discrete representation of the distribution function for the output quantity

[[scls_7-5-1]]
==== {blank}

A discrete representation stem:[bb(G)] of the distribution function stem:[G_Y (eta)] for the output quantity stem:[ii(Y)] can be obtained as follows:

. [[item_7-5-1a]]sort the model values stem:[y_r], stem:[r = 1,..., M], provided by MCM into non-decreasing order. Denote the sorted model values by stem:[y_{(r)}], stem:[r = 1,..., ii(M)];

. [[item_7-5-1b]]if necessary, make minute numerical perturbations to any replicate model values stem:[y_{(r)}] in such a way that the resulting complete set of stem:[y_{(r)}], stem:[r = 1,..., M], form a strictly increasing sequence (cf. condition <<item_5-10-1b>> in <<scls_5-10-1>>);

. [[item_7-5-1c]]take stem:[bb(G)] as the set stem:[y_{(r)}], stem:[r = 1,..., ii(M)].


NOTE: With reference to step <<item_7-5-1a>>, a sorting algorithm taking a number of operations proportional to stem:[M ln M] should be used <<Scowen1965>>. A naive algorithm would take a time proportional to stem:[M^2], making the computation time unnecessarily long. See <<scls_7-8>>.

NOTE: In step <<item_7-5-1a>>, the term "non-decreasing" rather than "increasing" is used because of possible equalities among the model values stem:[y_r].

NOTE: With reference to step <<item_7-5-1b>>, making only minute perturbations will ensure that the statistical properties of the stem:[y_{(r)}] are retained.

NOTE: In step <<item_7-5-1b>>, it is exceedingly unlikely that perturbations are necessary, because of the very large number of distinct floating-point numbers that can arise from model values generated from input quantities obtained as draws from random number generators. A sound software implementation would make appropriate provision, however.

NOTE: With reference to step <<item_7-5-1c>>, a variety of information can be deduced from G. In particular, information supplementary to the expectation and standard deviation can be provided, such as measures of skewness and kurtosis, and other statistics such as the mode and the median.

NOTE: If stem:[ii(Y)] is to become an input quantity for a further uncertainty calculation, sampling from its probability distribution is readily carried out by drawing randomly from the stem:[y_{(r)}], stem:[r = 1,..., M], with equal probability (see <<scls_6-5>>).


==== {blank}

The stem:[y_{(r)}] (or stem:[y_r]), when assembled into a histogram (with suitable cell widths) form a frequency distribution that, when normalized to have unit area, provides an approximation to the PDF stem:[g_Y (eta)] for stem:[ii(Y)]. Calculations are not generally carried out in terms of this histogram, the resolution of which depends on the choice of cell widths, but in terms of G. The histogram can, however, be useful as an aid to understanding the nature of the PDF, e.g. the extent of its asymmetry. See, however, <<scls_7-8-3>> <<note1_7-8-3>> regarding the use of a large numerical value of stem:[ii(M)].


==== {blank}

A continuous approximation to stem:[G_Y (eta)] is sometimes useful. <<annexD>> contains a means for obtaining such an approximation.


[[scls_7-6]]
=== Estimate of the output quantity and the associated standard uncertainty

The average

[[eq16]]
[stem]
++++
tilde y = 1/{ii(M)} sum_{r=1}^{ii(M)} y_r
++++

and standard deviation stem:[u(tilde y)] determined from

[[eq17]]
[stem]
++++
u^2(tilde y) = 1/{ii(M) - 1} sum_{r=1}^{ii(M)} (y_r - tilde(y))^2
++++

are taken, respectively, as an estimate stem:[y] of stem:[ii(Y)] and the standard uncertainty stem:[u(y)] associated with stem:[y].

[NOTE]
====
<<eq17>> should be used rather than the mathematically equivalent formula

[stem%unnumbered]
++++
u^2(tilde(y)) = {ii(M)}/{ii(M) - 1} (1/{ii(M)} sum_{r=1}^{ii(M)} y_r^2 - tilde(y)^2)
++++

For the many circumstances in metrology in which stem:[u(y)] is much smaller than stem:[|y|] (in which case the stem:[y_r] have a number of leading decimal digits in common) the latter formula suffers numerically from subtractive cancellation (involving a mean square less a squared mean). This effect can be so severe that the resulting numerical value might have too few correct significant decimal digits for the uncertainty evaluation to be valid <<Chan1983>>.
====

NOTE: In some special circumstances, such as when one of the input quantities has been assigned a PDF based on the stem:[t]-distribution with fewer than three degrees of freedom, the expectation and standard deviation of stem:[ii(Y)], as described by the PDF stem:[g_Y (eta)], might not exist. <<eq16>> and <<eq17>> might not then provide meaningful results. A coverage interval for stem:[ii(Y)] (see <<scls_7-7>>) can, however, be formed, since G is meaningful and can be determined.

NOTE: stem:[tilde(y)] will not in general agree with the model evaluated at the best estimates of the input quantities, since, for a non-linear model stem:[f(bb(X))], stem:[E(Y) = E(f(bb(X))) != f(E(bb(X)))] (cf. <<JCGM-100,clause=4.1.4>>). Irrespective of whether stem:[f] is linear or non-linear, in the limit as stem:[M] tends to infinity, stem:[tilde(y)] approaches stem:[E(f(bb(X)))] when stem:[E(f(bb(X)))] exists.


[[scls_7-7]]
=== Coverage interval for the output quantity

==== {blank}

A coverage interval for stem:[ii(Y)] can be determined from the discrete representation stem:[bb(G)] of stem:[G_Y (eta)] in an analogous manner to that in <<scls_5-3-2>> given stem:[G_Y (eta)].


==== {blank}

Let stem:[q = pM], if stem:[pM] is an integer. Otherwise, take stem:[q] to be the integer part of stem:[pM + 1//2]. Then stem:[[y_{"low"},y_{"high"}\]] is a stem:[100p " %"] coverage interval for stem:[ii(Y)], where, for any stem:[r = 1,..., ii(M) - q], stem:[y_{"low"} = y_{(r)}] and stem:[y_{"high"} = y_{(r+q)}]. The probabilistically symmetric stem:[100p " %"] coverage interval is given by taking stem:[r = (M - q)//2], if stem:[(M - q)//2] is an integer, or the integer part of stem:[(M - q + 1)//2], otherwise. The shortest stem:[100p " %"] coverage interval is given by determining stem:[r^∗] such that, for stem:[r = 1,..., ii(M) - q, y_{(r^∗ + q)} - y_{(r^*)} <= y_{(r+q)} - y_{(r)}].

NOTE: Because of the randomness in MCM, some of these stem:[M - q] interval lengths will be shorter than they would be on average, and some longer. So, by choosing the least such length, (the approximation to) the shortest stem:[100p " %"] coverage interval tends to be marginally shorter than that which would have been calculated from stem:[G_Y (eta)], with the consequence that the typical coverage probability is less than stem:[100p " %"]. For large stem:[ii(M)], this coverage probability is negligibly less than stem:[100p " %"].

[example]
stem:[10^5] numbers were drawn from a pseudo-random number generator for the rectangular distribution in the interval stem:[[0,1\]], and the shortest 95 % coverage interval formed as above. This exercise was carried out stem:[1000] times. The average coverage probability was 94.92 % and the standard deviation of the stem:[1000] coverage probabilities 0.06 %.


[[scls_7-8]]
=== Computation time

==== {blank}

The computation time for MCM is dominated by that required for the following three steps:

. make stem:[ii(M)] draws from the PDF for each input quantity stem:[X_i] (or the joint PDF for stem:[bb(X)]);
. make stem:[ii(M)] corresponding evaluations of the model;
. [[item_7-8-1c]]sort the resulting stem:[ii(M)] model values into non-decreasing order.


==== {blank}

The times taken in the three steps are directly proportional to (a) stem:[ii(M)], (b) stem:[ii(M)], and \(c) stem:[ii(M) ln ii(M)] (if an efficient sort algorithm <<Scowen1965>> is used).


[[scls_7-8-3]]
==== {blank}

If the model is simple and the input quantities are independent, the time in step <<item_7-8-1c>> can be expected to dominate, and the overall time taken is typically a few seconds for stem:[ii(M) = 10^6] on a personal computer operating at several GHz. Otherwise, let stem:[T_1] be the time taken to make one draw from the PDFs for the input quantities and stem:[T_2] that to make one evaluation of the model. Then, the overall time can be taken as essentially stem:[M xx (T_1 + T_2)], which, if the model is complicated, is dominated by the term stem:[M T_2].

[[note1_7-8-3]]
NOTE: If the model is simple and stem:[ii(M)] very large, e.g. stem:[10^8] or stem:[10^9], the sorting time may be excessive compared with the time taken to make the stem:[ii(M)] model evaluations. In such a case, calculations can instead be based on an approximation to stem:[g_Y (eta)] derived from a suitable histogram of the stem:[y_r].


[NOTE]
====
An indication of the computation time required for an application of MCM can be obtained as follows. Consider an artificial problem with a model consisting of the sum of five terms:

[stem%unnumbered]
++++
Y = cos X_1 + sin X_2 + tan^{-1} X_3 + exp(X_4) + X_5^(1//3).
++++

Assign a Gaussian PDF to each input quantity stem:[X_i]. Make stem:[M = 10^6] Monte Carlo trials. The relative computation times for (a) generating 5M random Gaussian numbers, (b) forming stem:[ii(M)] model values and \(c) sorting the stem:[ii(M)] model values were respectively 20 %, 20 % and 60 %, with a total computation time of a few seconds on a personal computer operating at several GHz.
====


[[scls_7-9]]
=== Adaptive Monte Carlo procedure

[[scls_7-9-1]]
==== General

A basic implementation of an adaptive Monte Carlo procedure involves carrying out an increasing number of Monte Carlo trials until the various results of interest have stabilized in a statistical sense. A numerical result is deemed to have stabilized if twice the standard deviation associated with it is less than the numerical tolerance (see <<scls_7-9-2>>) associated with the standard uncertainty stem:[u(y)].


[[scls_7-9-2]]
==== Numerical tolerance associated with a numerical value

Let stem:[n_{"dig"}] denote the number of significant decimal digits regarded as meaningful in a numerical value stem:[z]. The numerical tolerance stem:[delta] associated with stem:[z] is given as follows:

. express stem:[z] in the form stem:[c xx 10^{cc(l)}], where stem:[c] is an stem:[n_{"dig"}] decimal digit integer and stem:[cc(l)] an integer;
. take
+
--
[[eq18]]
[stem]
++++
delta = 1/2  10^{cc(l)}.
++++
--

[[ex1_7-9-2]]
[example]
The estimate of the output quantity for a nominally 100 g measurement standard of mass <<JCGM-100,clause=7.2.2>> is stem:[y = 100.02147" "rm(g)]. The standard uncertainty stem:[u(y) = 0.00035" "rm(g)], both significant digits being regarded as meaningful. Thus, stem:[n_{"dig"} = 2] and stem:[u(y)] can be expressed as stem:[35 xx 10^{-5}" " rm(g)], and so stem:[c = 35] and stem:[cc(l) = -5]. Take stem:[delta = 1/2 xx 10^{-5}] stem:[g = 0.000005 " "rm(g)].

[example]
As <<ex1_7-9-2>> except that only one significant decimal digit in stem:[u(y)] is regarded as meaningful. Thus, stem:[n_{"dig"} = 1] and stem:[u(y) = 0.0004" "rm(g) = 4 xx 10^{-4}" "rm(g)], giving stem:[c = 4] and stem:[cc(l) = -4]. Hence, stem:[delta = 1/2 xx 10^{-4}] stem:[g = 0.00005" "rm(g)].

[example]
In a temperature measurement, stem:[u(y) = 2 K]. Then, stem:[n_{"dig"} = 1] and stem:[u(y) = 2 x 10^0 K], giving stem:[c = 2] and stem:[cc(l) = 0]. Thus, stem:[delta = 1/2 xx 10^0] stem:[K = 0.5 K].


==== Objective of adaptive procedure

The objective of the adaptive procedure given in <<scls_7-9-4>> is to provide

. an estimate stem:[y] of stem:[ii(Y)],
. an associated standard uncertainty stem:[u(y)], and
. the endpoints stem:[y_{"low"}] and stem:[y_{"high"}] of a coverage interval for stem:[ii(Y)] corresponding to a stipulated coverage probability such that each of these four values can be expected to meet the numerical tolerance required.

NOTE: By its stochastic nature, the procedure cannot be guaranteed to provide such an interval.

NOTE: stem:[y] and stem:[u(y)] generally "converge" considerably faster than stem:[y_{"low"}] and stem:[y_{"high"}] with respect to the number of Monte Carlo trials.

NOTE: Generally, the larger is the coverage probability, the larger is the number of Monte Carlo trials required to deter-mine stem:[y_{"low"}] and stem:[y_{"high"}] for a given numerical tolerance.


[[scls_7-9-4]]
==== Adaptive procedure

A practical approach, involving carrying out a sequence of applications of MCM, is as follows:

. [[item_7-9-4a]]set stem:[n_{"dig"}] to an appropriate small positive integer (see <<scls_7-9-2>>);
. [[item_7-9-4b]]set
+
--
[stem%unnumbered]
++++
M = max(J, 10^4),
++++

where stem:[J] is the smallest integer greater than or equal to stem:[100//(1 - p)];
--

. set stem:[h = 1], denoting the first application of MCM in the sequence;
. [[item_7-9-4d]]carry out stem:[ii(M)] Monte Carlo trials, as in <<scls_7-3>> and <<scls_7-4>>;
. use the stem:[ii(M)] model values stem:[y_1,..., y_M] so obtained to calculate, as in <<scls_7-5>> to <<scls_7-7>>, y^(h)^, u(y^(h)^), y_{"low"}^(h)^ and y_{"high"}^(h)^ as an estimate of stem:[ii(Y)], the associated standard uncertainty, and the left- and right-hand endpoints of a stem:[100p " %"] coverage interval, respectively, i.e. for the __h__th member of the sequence;
. if stem:[h = 1], increase stem:[h] by one and return to step <<item_7-9-4d>>;
. [[item_7-9-4g]]calculate the standard deviation stem:[s_y] associated with the average of the estimates stem:[y^{(1)},..., y^{(h)}] of stem:[ii(Y)], given by
+
--
[stem%unnumbered]
++++
s_y^2 = 1 / {h(h - 1)} sum_{r=1}^{h} (y^{(r)} - y)^2,
++++

where

[stem%unnumbered]
++++
y = 1/h sum_{r=1}^{h} y^{(r)};
++++
--

. [[item_7-9-4h]]calculate the counterpart of this statistic for stem:[u(y)], stem:[y_{"low"}] and stem:[y_{"high"}];
. use all stem:[h xx ii(M)] model values available so far to form stem:[u(y)];
. calculate the numerical tolerance stem:[delta] associated with stem:[u(y)] as in <<scls_7-9-2>>;
. [[item_7-9-4k]]if any of stem:[2s_y], stem:[2s_{u(y)}], stem:[2s_{y_{"low"}}] and stem:[2s_{y_{"high"}}] exceeds stem:[delta], increase stem:[h] by one and return to step d);
. regard the overall computation as having stabilized, and use all stem:[h xx ii(M)] model values obtained to calculate stem:[y], stem:[u(y)] and a stem:[100p " %"] coverage interval, as in <<scls_7-5>> to <<scls_7-7>>.


NOTE: Normally stem:[n_{"dig"}] in step <<item_7-9-4a>> would be chosen to be 1 or 2.

NOTE: The choice of stem:[ii(M)] in step <<<item_7-9-4b>>> is arbitrary, but has been found suitable in practice.

NOTE: In step <<item_7-9-4g>>, stem:[y] can be regarded as a realization of a random variable with standard deviation stem:[s_y].

NOTE: The standard deviations formed in steps <<item_7-9-4g>> and <<item_7-9-4h>> tend to reduce in a manner proportional to stem:[h^{-1//2}] (cf. <<scls_5-9-6>> <<note2_5-9-6>>).


NOTE: In situations where a coverage interval is not required, the test for stabilization of the computation in step <<item_7-9-4k>> can be based instead on stem:[2s_y] and stem:[2s_{u(y)}] only.


NOTE: The factor 2 used in step <<item_7-9-4k>> is based on regarding the averages as realizations of Gaussian variables, and corresponds to a coverage probability of approximately 95 %.

[NOTE]
====
An alternative, non-adaptive approach for a 95 % probabilistically symmetric coverage interval, which can be obtained using the statistics of the binomial distribution <<David1981>>, is as follows. Select stem:[M = 10^5] or stem:[M = 10^6]. Form the interval stem:[[y_{(r)}, y_{(s)}\]], where, for stem:[M = 10^5], stem:[r = 2420] and stem:[s = 97581], or, for stem:[M = 10^6], stem:[r = 24747] and stem:[s = 975254]. This interval is a 95 % statistical coverage interval at the level of confidence 0.99 <<JCGM-100,clause=C.2.30>> <<Willink2004>>, i.e. the coverage probability will be no less than 95 % in at least 99 % of uses of MCM. The average coverage probability of such an interval will be stem:[(s - r)//(M + 1)], which is greater than 95 % by an amount that becomes smaller as stem:[ii(M)] is increased, viz. 95.16 % for stem:[M = 10^5] and 95.05 % for stem:[M = 10^6]. (There are other possibilities for stem:[r] and stem:[s]; they do not have to sum to stem:[M + 1]. A sufficient condition <<David1981,clause=2.6>> is that stem:[s - r] satisfies

[stem%unnumbered]
++++
sum_{j=s-r}^{ii(M)} C_j p^j (1 - p)^{ii(M)-j} < 1 - 0.99,
++++

where

[stem%unnumbered]
++++
""^{ii(M)} C_j = {ii(M)!} / {j! (M - j)!},
++++

the best result being when this inequality is just satisfied.) These results can be extended to other coverage probabilities (and other choices of stem:[ii(M)]).
====
