
== Validation of results

[[scls_8-1]]
=== Validation of the GUM uncertainty framework using a Monte Carlo method

==== {blank}

The GUM uncertainty framework can be expected to work well in many circumstances. However, it is not always straightforward to determine whether all the conditions for its application (see <<scls_5-7>> and <<scls_5-8>>) hold. Indeed, the degree of difficulty of doing so would typically be considerably greater than that required to apply MCM, assuming suitable software were available <<Cox-Harris2006>>. Therefore, since these circumstances cannot readily be tested, any cases of doubt should be validated. Since the domain of validity for MCM is broader than that for the GUM uncertainty framework, it is recommended that both the GUM uncertainty framework and MCM be applied and the results compared. Should the comparison be favourable, the GUM uncertainty framework could be used on this occasion and for sufficiently similar problems in the future. Otherwise, consideration should be given to using MCM or another appropriate approach instead.


==== {blank}

Specifically, it is recommended that the two steps below and the following comparison process be carried out:

. apply the GUM uncertainty framework (possibly with the law of propagation of uncertainty based on a higher-order Taylor series approximation) (see <<scls_5-6>>) to yield a stem:[100p " %"] coverage interval stem:[y +- U_p] for the output quantity, where stem:[p] is the stipulated coverage probability;

. apply the adaptive Monte Carlo procedure (see <<scls_7-9-4>>) to provide (approximations to) the standard uncertainty stem:[u(y)] and the endpoints stem:[y_{"low"}] and stem:[y_{"high"}] of the required (probabilistically symmetric or shortest) stem:[100p " %"] coverage interval for the output quantity. Also see <<scls_8-2>>.


==== {blank}

A comparison procedure has the following objective: determine whether the coverage intervals obtained by the GUM uncertainty framework and MCM agree to within a stipulated numerical tolerance. This numerical tolerance is assessed in terms of the endpoints of the coverage intervals and corresponds to that given by expressing the standard uncertainty stem:[u(y)] to what is regarded as a meaningful number of significant decimal digits (cf. <<scls_7-9-2>>). The procedure is as follows:

. form a numerical tolerance stem:[delta] associated with stem:[u(y)] as described in <<scls_7-9-2>>;
. compare the coverage intervals obtained by the GUM uncertainty framework and MCM to determine whether the required number of correct decimal digits in the coverage interval provided by the GUM uncertainty framework has been obtained. Specifically, determine
+
--
[[eq19]]
[stem]
++++
d_{"low"} = |y - U_{"p"} - y_{"low"}|,
++++

[[eq20]]
[stem]
++++
d_{"high"} = |y + U_{"p"} - y_{"high"}|,
++++

viz. the absolute differences of the respective endpoints of the two coverage intervals. Then, if both stem:[d_{"low"}] and stem:[d_{"high"}] are no larger than stem:[delta], the comparison is favourable and the GUM uncertainty framework has been validated in this instance.
--

NOTE: The choice of stem:[100p" "%] coverage interval will influence the comparison. Therefore, the validation applies for the specified coverage probability stem:[p] only.


[[scls_8-2]]
=== Obtaining results from a Monte Carlo method for validation purposes

A sufficient number stem:[M] of Monte Carlo trials (see <<scls_7-2>>) should be performed in obtaining MCM results for the validation purposes of <<scls_8-1>>. Let stem:[n_{"dig"}] denote the number of significant decimal digits required in stem:[u(y)] (see <<scls_7-9-1>>) when validating the GUM uncertainty framework using MCM. Let stem:[delta] denote the numerical tolerance associated with stem:[u(y)] (see <<scls_7-9-2>>). Then it is recommended that the adaptive Monte Carlo procedure (see <<scls_7-9-4>>) be used to provide MCM results to a numerical tolerance of stem:[delta//5]. Such results can be obtained by replacing stem:[delta] by stem:[delta//5] in step <<item_7-9-4k>> of that procedure.

NOTE: It can be expected that the use of a numerical tolerance of stem:[delta//5] would require a value of stem:[M] of the order of 25 times that for a numerical tolerance of stem:[delta]. Such a value of stem:[ii(M)] might present efficiency problems for some computers in operating with vector arrays of dimension stem:[ii(M)]. In such a case, calculations can instead be based on an approximation to stem:[g_Y (eta)] derived from a suitable histogram of the stem:[y_r], in which the cell frequencies in the histogram are updated as the Monte Carlo calculation proceeds. Cf. <<scls_7-8-3>> <<note1_7-8-3>>.
