
[[annexB]]
[appendix]
== Sensitivity coefficients and uncertainty budgets

=== {blank}

Neither the propagation of distributions nor its implementation using MCM provides sensitivity coeffi-cients <<JCGM-100,clause=5.1.3>>. However, by holding all input quantities but one fixed at their best estimates, MCM can be used to provide the PDF for the output quantity for the model having just that input quantity as a variable <<Cox-Harris2006>>. The ratio of the standard deviation of the resulting model values (cf. <<scls_7-6>>) and the standard uncertainty associated with the best estimate of the relevant input quantity can be taken as a sensitivity coefficient. This ratio corresponds to that which would be obtained by taking all higher-order terms in the Taylor series expansion of the model into account. This approach may be viewed as a generalization of the approximate partial-derivative formula in the GUM <<JCGM-100,clause=5.1.3 note 2>>. Both the sensitivity coefficients and the contributions for each input quantity to the uncertainty associated with the estimate of the output quantity will in general differ from those obtained with the GUM.


=== {blank}

In many measurement contexts it is common practice to list the uncertainty components stem:[u_i(y) = |c_i| u(x_i)], stem:[i = 1,..., N], where stem:[c_i] is the __i__th sensitivity coefficient and stem:[u(x_i)] the standard uncertainty associated with the __i__th input estimate stem:[x_i], contributing to the standard uncertainty stem:[u(y)]. Usually these are presented in a table, the "uncertainty budget". This practice may be useful to identify the dominant terms contributing to stem:[u(y)] associated with the estimate of the output quantity. However, in cases for which (a valid implementation of) the propagation of distributions is more appropriate, an uncertainty budget should be regarded as a qualitative tool.
