= CRITERIA TO ASSESS THE QUALITY OF NOMINATED NUCLEIC ACID REFERENCE MATERIALS WITH STATED NOMINAL PROPERTIES
:copyright-year: 2008
:revdate: 2008-09-12
:language: en
:docnumber: JCTML-EC-07
:doctype: brochure
:title-en: JCTLM WGI. NUCLEIC ACID REVIEW TEAM
:title-appendix-en: CRITERIA TO ASSESS THE QUALITY OF NOMINATED NUCLEIC ACID REFERENCE MATERIALS WITH STATED NOMINAL PROPERTIES
:appendix-id: II
:committee-en: Joint Committee for Traceability in Laboratory Medicine
:committee-fr: Comité commun pour la traçabilité en médecine de laboratoire
:committee-acronym: JCTLM
:mn-document-class: bipm
:mn-output-extensions: xml,html,pdf,rxl
:local-cache-only:
:data-uri-image:


== BACKGROUND

The JCTLM quality manual requires expert review of nominated certified reference materials, to assure they meet the quality requirements of the JCTLM for inclusion in its database of available higher order reference materials and methods/procedures, In accordance with JCTLM Quality Manual WG1-P-01, nominated materials are reviewed to assure compliance with quality criteria cited in ISO 15194:2003 and ISO Guide 34.

However, it has been recognised by ISO TC 212 WG2 and JCTLM that ISO 15194 applies fully to CRMs with assigned values of differential or rational quantities, and only very brief guidance on how to deal with nominal properties and ordinal quantities is given. The concept of metrological traceability, is applicable to ordinal quantities but not to nominal properties (See Appendix I). Therefore, although there are some common quality criteria for all reference materials to be considered in accordance with ISO 15194 and ISO Guide 34 (e.g. stability, homogeneity and commutability) there is limited guidance on the criteria that need to be fulfilled to consider a reference material for nominal properties as of higher order or high quality.

JCTLM review teams are currently expected to review reference materials for nominal properties, and have been charged with considering and documenting criteria which should be applied to assess the quality of such reference materials.


== JCTLM NUCLEIC ACID REVIEW TEAM APPROACH

The JCTLM Nucleic Acid Review Team leader invited international expert opinion on criteria which could/should be applied to assess the "quality" and "higher order traceability" of JCTLM database nominated reference materials -- in this case nucleic acids, for which there are only have stated "nominal qualities" -- most usually nucleic acid sequence.

The JCTLM nucleic acid review team (Appendix II) was consulted and contributions solicited by email "discussion" and related document sharing. The majority (7/8) of expert members actively participated in the process, contributing criteria and opinion. Additional expert opinion was also obtained from other internationally recognised experts in molecular biology and nucleic acid reference material development (Appendix II).

The existing knowledge base of relevant guidance documents for nucleic acid assays and reference materials and international standardisation initiatives in qualitative genetic analysis, was also reviewed with respect to stated criteria for nucleic acid method validation, test and material quality criteria and sequence identity confidence. (Appendix III).

The consultation process was very broad as the team believes co-ordination is required to ensure harmonisation, although to date very little specific reference has been made to quality criteria for sequence verification.

Draft nucleic acid sequence quality criteria were also discussed in a presentation given to JCTLM members and other relevant stakeholders at the 2008 JCTLM WG meeting, prior to preparation, review team review and submission of this consensus document.


== NOMINAL PROPERTY QUALITY CRITERIA FOR NUCLEIC ACID RM REVIEW

These criteria for quality review of stated nominal properties, specifically -- sequence, of a JCTLM nominated nucleic acid based CRM are to be used to complement the JCTLM CRM Review Checklist -- ISO 15194, WG1-P-03-F-01.

For nucleic acid CRM identity the following criteria will be additionally applied in reviewing the nominal quality "sequence":

. Quality-scored bi-directional sequencing as the logical 'gold standard' method of choice for traceability shall be applied (<<note1>>)

. Ideally verification should be by:
+
--
* alternative sequence assays
* inter-laboratory studies (to validate use of reference material) (<<note2>>,<<note3>>,<<note4>>)
The uncertainty can then be expressed as the probability of a miss called base or bases in the sequence of nucleic acids in the target, for example using a PHRED score / confidence statement (ordinal quantity!) (<<note2>>,<<note3>>)
--

. The CRM is then considered to be "Traceable" to base nucleotide reference. (<<note5>>)

[[note1]]
[NOTE]
====
Sequencing may not be considered appropriate for all RMs (eg tri-nucleotide repeat disorders). Decisions must be made on a case by case basis in accord with expert opinion and the JCTLM nominated nucleic acid CRM.

In accordance with ISO Guide 34 and ISO 15194 revisions, reference materials created by PCR, cell culture and plasmid-generated must be sequenced per batch, Otherwise strong evidence would have to be provided that the production process is sufficiently reproducible and that fluctuations would not have an impact on the homogeneity, stability and characteristics of the material
====


[[note2]]
[NOTE]
====
Guidance document on the use of reference materials in genetic testing -- EUROGENTEST

4.6 Identity checks

In the case of the identification of a nucleic acid sequence, DNA sequencing can be considered as one of the more robust methods. For validation purposes, attention should be paid that the sequence of interest has been obtained using forward and backward sequencing primers spanning the same target region. The uncertainty can then be expressed as the probability of misreadings in the sequence of nucleic acids in the target, for example using a PHRED score
====


[[note3]]
[NOTE]
====
External RNA Control Consortium (ERCC) guidance on Certification of Sequence ~100,000 bases of DNA

* sequence with multiple methods
* sequence both strands
* sequence with redundant coverage
* estimate error rates from data
* classify regions of sequence e.g.  _"`Most Confident,`" "`Very Confident,`" "`Confident,`" and "`Ambiguous.`"_
====


[[note4]]
NOTE: Additional verification by sequencing with alternative methods may not be possible or practical -- dependent on size of RM sequence, and confidence of sequence quality.


[[note5]]
[NOTE]
====
Statements of DNA sequence traceability

* Sequence results will be traceable to the identities of the individual nucleotides. (Not an SI unit, but traceability to an internationally accepted reference unit)
====


== Summary

Expert and documented opinion on criteria for determination of the nominal property nucleic acid sequence "quality" has been reviewed and collated. The above criteria for sequence verification represent the majority opinion of the review team, and are closely aligned with other developing standardization initiatives in the area. Sequencing may not be considered appropriate for all RMs ( eg tri-nucleotide repeat disorders), therefore nucleic acid based RMs with nominal properties need to be reviewed on a case by case basis taking expert advise from the review team.


== Further Recommendations

Although the above nucleic acid sequence quality criteria have been formulated on the basis of the current "best practice" guidance available and expert opinion, it is recognised by the review team and other expert stakeholders that nucleic acid based analytical technology, and associated reference material development is evolving rapidly. For example, conventional Sanger sequencing is being increasingly displaced by next generation (ultra high throughput) sequencing, and non-coding RNA with non-linear or 2nd dimension sequence for which there are different considerations for quality criteria. The JCTLM nucleic acid nominal property review process and quality guidance should be flexible and adaptive and reviewed annually, in order to take account of emerging nucleic acid CRM nominations.

Current members of, and consultants to, the nucleic acid review team contribute to the other standardisation initiatives discussed, so are well placed with relevant expertise to:

* Continue to review knowledge and update criteria to reflect evolving best practice and technological changes in RM production / QA
* Continue to contribute to related international initiatives including ISO REMCO WG developing standards for CRMs for qualitative analysis


[appendix]
== DEFINITIONS

=== ISO REMCO definition of a CRM

Reference material, characterized by a metrologically valid procedure for one or more specified properties, accompanied by a certificate that provides the value of the specified property, its associated uncertainty, and a statement of metrological traceability

NOTE: The concept of value includes qualitative attributes such as identity or sequence. Uncertainties for such attributes may be expressed as probabilities.

NOTE: Metrologically valid procedures for the production and certification of reference materials are given in, among others, ISO Guides 34 and 35


=== INTERNATIONAL VOCABULARY OF METROLOGY VIM (JCGM 2008)

==== Nominal property

Property of a phenomenon, body, or substance, where the property has no magnitude

* e.g. sex of a human being
* e.g. colour of paint
* e.g. sequence of amino acids in a polypeptide

SEQUENCE OF BASES IN A NUCLEIC ACID = NOMINAL PROPERTY (YES/NO -- QUALITATIVE IDENTITY TEST)


[appendix]
== EXPERT CONTRIBUTION

=== JCTLM Nucleic Acid Review Team

. Helen Parkes -- Senior Consultant Biomeasurement, LGC, UK
. Morag Ferguson -- NIBSC (WHO / IU RMs) √
. Joan Gordon -- President, Maine Molecular QCI √
. Tomoshige Hori -- Director, Standardisation and Strategy, Japanese Bioindustry Association √
. Lisa Kalman -- GeT-RM, Laboratory Practice Evaluation and Genomics Branch, CDC, Atlanta √
. Roberta Madej -- Director, Global Standardisation, Roche Molecular Systems & Chair CLSI molecular methods area committee √
. Heinz Schimmel -- IRMM, Life Science RMs √


=== Other experts consulted

[start=8]
. Marc Salit -- NIST, ERCC RM certification, MGED
. David Gancberg -- IRMM, Eurogentest documentation on genetic testing RM
. Carole Foy -- LGC, EMERALD, USP nucleic acid chapter expert
. David Smith -- Associate Director Scientific Awareness, Luminex Corporation


[appendix]
== Existing Knowledge Base reviewed

=== Supporting documents

. CLSI MM17-A- Verification and Validation of Multiplex Nucleic Acid Assays; Proposed Guideline
. CLGGS (draft) -- Characterisation of DNA Microarray Controls
. ERCC -- External RNA Controls Consortium (2005) Proposed methods for testing and selecting ERCC external RNA controls. BMC Genomics 6:150
. Eurogentest -- Guidance document on the use of reference materials in genetic testing (approval) Project : NoE EuroGentest, Unit 1, WP1.6 D. Gancberg, P. Corbisier, H. Schimmel, H. Emons
. IRMM -- Certified Reference Materials for Genetic Testing Eurogentest presentations 2007, 2008 D. Gancberg
. OECD -- OECD guidelines for quality assurance in molecular genetic testing 2007
. JBA -- Trends in international standardization of molecular genetic testing for clinical application
. CLSI C53 (P): Characterisation and Qualification of Commutable Reference Materials for laboratory medicine
. ISO REMCO N863 -- ad hoc group (AHG 01) gap analysis report on CRMs for qualitative analysis (testing of nominal properties)


=== International Standardization Initiatives

International committees considering additional quality guidelines on qualitative analysis

[start=10]
. Various standardisation bodies (ISO REMCO, ISO TC 212, etc)
. Professional organisations (CLSI, AOAC, IUPAC, Eurachem, etc)
. Networks (ERCC, EUROGENTEST, MGED, JCTLM, Genomics Standards Consortium etc)
