= Technical Annex for the International Temperature Scale of 1990 (ITS-90)
:appendix-id: 2
:partnumber: 1
:edition: 9
:copyright-year: 2017
:revdate: 2017-06-28
:language: en
:docnumber: MeP-K
:title-appendix-en: Technical Annex for the International Temperature Scale of 1990 (ITS-90)
:doctype: guide
:docstage: in-force
:docsubstage: 60
:imagesdir: images
:docfile: MeP-K-technical-annex.adoc
:mn-document-class: bipm
:mn-output-extensions: xml,html,pdf,rxl
:local-cache-only:
:data-uri-image:


[.preface]
== Abstract

This Technical Annex includes specifications beyond the definitions in the text of the International Temperature Scale of 1990 (ITS-90) that are deemed essential for the unambiguous realization of the ITS-90. Specifications within the Technical Annex are considered mandatory extensions of the text of the ITS-90.

For material taken directly from the text of the ITS-90, the _mise en pratique_ refers to "defined" or "assigned" values or procedures. Where additional material other than the ITS-90 text has been deemed essential for inclusion in the Technical Annex, the _mise en pratique_ of the definition of the kelvin refers to "specified" values or procedures.


== Isotopic composition and corrections for the triple point of water

The effects of isotopic composition on the triple point of water (TPW) are discussed in detail in [<<White2010,White and Tew 2010>>, <<Ripple2005,Ripple _et al._ 2005>>].

The international science community, through the International Atomic Energy Agency, uses a defined Standard Mean Ocean Water (SMOW) as a point of reference for studies in the isotopic composition of waters. In practice, measurements of isotopic composition are made with respect to Vienna-SMOW (VSMOW) and Standard Light Antarctic Precipitation (SLAP) [Gonfiantini 1978, <<Li1988,Li _et al._ 1988>>]; two widely distributed standard reference water samples that span the isotopic range of naturally occurring samples. The International Union of Pure and Applied Chemistry (IUPAC) recommended the following amount-of-substance ratios for VSMOW, based on the most reliable measurements available [De <<Laeter2003,Laeter _et al._ 2003>>]:


[stem%unnumbered]
++++
(""^2"H"//""^1"H")_{VSMOW} = 0.00015576(5),
++++

[stem%unnumbered]
++++
(""^{18}"O" // ""^{16}"O")_{VSMOW} = 0.0020052(5),
++++

[stem%unnumbered]
++++
(""^{17}"O"//""^{16}"O")_{VSMOW}  =  0.0003799(9).
++++


For the purposes of thermometry, these absolute values are specified for the isotopic composition of the water used for realizing the definition of the kelvin with the assigned temperature stem:[T_{90}("TPW") = 273.16 " K"]. However, variations in isotopic composition of water can be measured much more accurately in relative mode (that is, relative to that of VSMOW) than in absolute mode. This is the reason why the scale definition for isotope values of water is still artefact-based. Isotopic deviations of artefact VSMOW from SMOW are negligible when expressed as an equivalent change in the TPW temperature.

Variations in amount-of-substance ratios are conventionally reported as deviations from VSMOW, such as


[stem]
++++
delta ""^{18}"O"_{"CAL"} = [{(""^{18}"O"//""^{16}"O")_{"sample"} - (""^{18}"O"//""^{16}"O")_{VSMOW}} / {(""^{18}"O"//""^{16}"O")_{VSMOW}}],
++++


and similarly for stem:[delta "D"] (where symbol stem:["D"] designates ^2^H, and symbol H will subsequently designate ^1^H) and stem:[delta]^17^O. The subscript CAL emphasizes that the stem:[delta]-value has been determined with respect to VSMOW. Usually the results are in the parts-per-thousand range, so are expressed in permil (per thousand, ‰).

Besides VSMOW, to further improve the inter-laboratory reproducibility of the water isotopic composition measurements, SLAP is also used to define the scale. The stem:[delta]-values of SLAP have been defined based on consensus between expert laboratories taking part in a large international intercomparison [Gonfiantini, 1984]. They are stem:[delta "D" = -428 ‰] and stem:[delta ""^{18}"O" = -55.5 ‰] with respect to VSMOW. These consensus values are used in the definition of the so-called normalized VSMOW-SLAP scale:


[stem]
++++
delta ""^{18} "O" ("sample")_{"NORM"} = [delta ""^{18} "O" ("sample")_{"CAL"} {(-0.0555)}/{delta ""^{18} "O"("SLAP")_{"CAL"}}],
++++

and similarly for stem:[delta "D"], with the value stem:[-0.428] in the nominator. All isotope laboratories usually report their isotope stem:[delta]-values for water in this normalized way.

For all naturally occurring surface waters, the isotopic composition is sufficiently close to that of VSMOW, and the correlation between the ^18^O and the ^17^O contents is so strong [<<Meijer1998,Meijer and Li 1998>>] that the effect of the isotopes on the TPW temperature can be specified by a linear function of only the stem:[delta "D"] and stem:[delta]^18^O values:


[stem]
++++
T_{"meas"} = T_{90} ("TPW") + A("D") cdot delta D + A ("O") cdot delta^{18} "O" ,
++++


where the last term on the right accounts for both the ^18^O and the ^17^O effects, but requires only the knowledge of the δ^18^O value. The most precise set of isotopic depression constants presently available, and those specified for use with the ITS-90, are by Faghihi _et al._ (<<Faghihi2015a,2015a>> and <<Faghihi2015b,2015b>>). These values are: stem:[A("D") = 673" "mu"K"] and stem:[A("O") = 630" "mu"K"], withestimated standard uncertainties of stem:[4" "mu"K"] and stem:[10" "mu"K"], respectively. These values have been derived using stem:[delta]-values expressed on the normalized VSMOW-SLAP scale.

The practice, introduced by some manufacturers, of adding enriched water to the initial source water to compensate for the isotope depletion taking place during the purification process is not recommended. After adding enriched water, full isotope analysis including the difficult measurement of δ^17^O is required, with less accurate and less reliable results. For TPW cells manufactured with addition of enriched water, the following correction equation is recommended:


[stem]
++++
T_{"meas"} = T_{90} ("TPW") + A("D") cdot delta "D" + A("O") cdot delta ""^{18}"O" + A(""^{17}"O") {delta ""^{17}"O" - [(1 + delta ""^{18}"O")^{0.528} -  1]} ,
++++


where the coefficient stem:[A(""^{17}"O") = 60" "mu"K"] given by <<White2010,White and Tew (2010)>> has an estimated standard uncertainty of stem:[1" "mu"K"].

It should be noted that the original references VSMOW and SLAP water are exhausted. Their successors, VSMOW2 and SLAP2 have been prepared with utmost care to resemble the originals to within the uncertainties. Only for SLAP2 the stem:[delta "D"] value is -427.5 ‰ instead of -428 ‰.


== Isotopic composition and corrections for the triple point of equilibrium hydrogen

The effects of isotopic composition on the triple point of equilibrium hydrogen (e-H~2~ TP) and uncertainties related to these effects are discussed in detail in [<<Steur2005,Steur _et al._ 2005>>, <<Fellmuth2005,Fellmuth _et al._ 2005>>].

The isotopic composition of commercially available hydrogen varies from an amount-of-substance ratio of about 27 micromole of D per mole of H to about 150 micromole of D per mole of H. It has been established that the discrepancies previously found at the triple point are mainly due to the variable deuterium content in the hydrogen used for its realization [<<Pavese2000,Pavese and Tew 2000>>, <<Pavese2002,Pavese _et al._ 2002>>].

It is therefore specified that the ITS-90 temperature assigned to the triple point of equilibrium hydrogen, stem:[T_{90}("e-H"_2 " TP") = 13.8033 " K"], is taken to refer to an amount-of-substance ratio of stem:[0.00008902] mole of D per mole of H. This is the isotopic ratio determined for SLAP [<<Gonfiantini1978,Gonfiantini 1978>>].

To correct to the isotopic reference ratio, the following function is specified:


[stem]
++++
T_{"meas" = T_{90} ("e-H"_2 "TP") + k_{"D"} (x - x_0),
++++


where stem:[x] denotes the amount-of-substance ratio of the sample in micromole D per mole H, stem:[x_0 = 89.02" "mu"mol/mol"] in the reference ratio specified above, and stem:[k_{"D"}] the triple-pointtemperature variation as a function of the deuterium ratio (the slope). The current value for stem:[k_{"D"}], specified for the ITS-90, was determined by Fellmuth _et al._ [<<Fellmuth2005,Fellmuth _et al._ 2005>>] as stem:[k_{"D"} = 5.42" "mu"K"//(mu"mol/mol")] with an estimated standard uncertainty of stem:[0.31" "mu"K"//(mu"mol/mol")].


== Isotopic composition for the vapour-pressure points of equilibrium hydrogen

The effects of isotopic composition on the vapour-pressure points of equilibrium hydrogen and the uncertainties related to these effects are discussed in detail in [<<Steur2005,Steur _et al._ 2005>>].

Isotopic fractionation manifests itself as a difference of as much as stem:[0.4 " mK"] between the dew point (vanishingly small liquid fraction) and the bubble point (vanishingly small vapour fraction) [<<Pavese2002,Pavese _et al._ 2002>>].

To reduce the effect of isotopic fractionation while maintaining coherence over the entire vapour-pressure range (i.e., including the triple point), it is therefore specified that the ITS-90 relations for the vapour pressure of equilibrium hydrogen are referenced to an amount-of-substance ratio of stem:[0.00008902] mole D per mole H, i.e. the isotopic ratio determined for SLAP.


== Isotopic composition and corrections for the triple point of neon

The effects of isotopic composition on the triple point of neon (Ne TP) and uncertainties related to these effects are discussed in detail in [<<Pavese2013,Pavese _et al._ 2013>>, <<Steur2012,Steur _et al._ 2012>>].

The isotopic composition of commercially available neon varies from an amount-of-substance ratio of about stem:[0.0915] mole of ^22^Ne per mole of Ne to about stem:[0.0948] mole of ^22^Ne per mole of Ne, and about stem:[0.0027] mole of ^21^Ne per mole of Ne to about stem:[0.0028] mole of ^21^Ne per mole of Ne. It has been established that the discrepancies previously found at the triple point are mainly due to the variable ^22^Ne content in the neon used for its realization [<<Pavese2008a,Pavese _et al._ 2008a>>, <<Pavese2008b,Pavese _et al._ 2008b>>].

It is therefore specified that the ITS-90 temperature assigned to the triple point of neon, stem:[T_{90} ("Ne TP") = 24.6651 " K"], is taken to refer to amount-of-substance ratios of stem:[0.0925] mole of ^22^Ne per mole of Ne and stem:[0.0027] mole of ^21^Ne per mole of Ne. This is the IUPAC isotopic composition [<<Wieser2011,Wieser and Coplen 2011>>].

To correct for the isotopic reference ratios, the following function is specified (pseudo-binary approach):


[stem]
++++
T_{"meas"} = T_{90}("Ne TP") + k_0 + k_1 (""^{22}x + ""^{21}x//2) + k_2 (""^{22}x + ""^{21}x//2)^2 ,
++++


where ^22^x and ^21^x denote the amount-of-substance ratios of the sample for ^22^Ne and ^21^Ne, respectively. The current values for the coefficients, specified for the ITS-90, are given by Pavese _et al._ [<<Pavese2013,Pavese _et al._ 2013>>] as stem:[k_0 = -0.01382 " K"], stem:[k_1 = 0.147350 " K"], stem:[k_2 = –0.000779 " K"] (stem:[k_1] and stem:[k_2] are rounded to six decimal figures which influences the correction by less than stem:[1" "mu"K"]). The estimated standard uncertainty of the slope of the function amounts to stem:[400" "mu"K"] for a quasi IUPAC isotopic composition, and to stem:[200" "mu"K"] for a quasi-pure ^20^Ne [<<Steur2012,Steur _et al._ 2012>>]. If the neon fixed point of the ITS-90 is realized via the triple point of ^20^Ne, an uncertainty in stem:[k_0] amounting to stem:[30" "mu"K"] has also to be considered.


[bibliography]
== References

* [[[De2003,1]]] De Laeter J.R., Böhlke J.K.,De Bièvre P., Hidaka H., Peiser H.S., Rosman K.J.R., Taylor P.D.P., 2003, _Pure Appl. Chem._, *75*, 683-800.

* [[[Faghihi2015a,1]]] Faghihi V., Peruzzi A., Aerts-Bijma A.T., Jansen H.G., Spriensma J.J., van Geel J., Meijer H.A.J., 2015a, _Metrologia_, *52*, 819-826.

* [[[Faghihi2015b,1]]] Faghihi V., Kozicki M., Aerts-Bijma A.T., Jansen H.G., Spriensma J.J., Peruzzi A., Meijer H.A.J., 2015b, _Metrologia_, *52*, 827-834.

* [[[FellmuthB2005,1]]] FellmuthB., Wolber L., Hermier Y., Pavese F., Steur P.P.M., Peroni I., Szmyrka-Grzebyk A., Lipinski L., Tew W.L., Nakano T., Sakurai H., Tamura O., Head D., Hill K.D., Steele A.G., 2005, _Metrologia_, *42*, 171-193.

* [[[Gonfiantini1978,1]]] Gonfiantini R., 1978, _Nature_, *271*, 534-536.

* [[[Gonfiantini2010,1]]] Gonfiantini R., 2010, Report on an advisory group meeting on stable isotope reference samples for geochemical and hydrochemical investigations, _IAEA Report to the Director General_.

* [[[Li1613,1]]] Li W.J., Ni B.L., Jin D.Q., Chang T.L., 1988, _Kexue Tongbao_ (Chinese Science Bulletin), *33*, 1610-1613.

* [[[Meijer1998,1]]] Meijer H.A.J., Li W., 1998, _Isot. Environ. Health Stud._, *34*, 349

* [[[Pavese2000,1]]] Pavese F., Tew W.L., 2000, "On the isotopic composition of commercial hydrogen vs 'natural isotopic composition' and the problems for the ITS-90 definition", Comité Consultatif de Thermométrie, Working Document CCT/2000-19.

* [[[Pavese2001,1]]] Pavese F., Tew W.L., Steele A., 2002 "Archival and theoretical considerations for isotopic dependence in the e-H~2~ fixed points", In: _TEMPMEKO 2001, 8th International Symposium on Temperature and Thermal Measurements in Industry and Science_, eds.Fellmuth _et al._ (VDI/VDE, Berlin), 429-434.

* [[[Pavese2008a,1]]] Pavese F., Fellmuth B., Hill, K.D., Head D., Hermier Y., Lipinski L., Nakano T., Peruzzi A., Sakurai H., Szmyrka-Grzebyk A., Steele A.G., Steur P.P.M., Tamura O., Tew W.L., Valkiers. S., Wolber. L., 2008a, _Int. J. Thermophys._, *29*, 57-66.

* [[[Pavese2008b,1]]] Pavese F., Fellmuth B., Hill K.D., Head D., Hermier Y., Lipinski L., Nakano T., Peruzzi A., Sakurai H., Szmyrka-Grzebyk A., Steele A.G., Steur P.P.M., Tamura O., Tew W.L., Valkiers S., Wolber L., 2008b, "Status of progress towards the determination of the relationship between neon triple-point temperature stem:[T_{"tp"}] and isotopic amount composition stem:[x]", Comité Consultatif de Thermométrie, Working Document CCT/08-06.

* [[[Pavese2013,1]]] Pavese F., Steur P.P.M., Hermier Y., Hill K.D., Kim J.S., Lipinski L., Nagao K., Nakano T., Peruzzi A., Sparasci F., Szmyrka-Grzebyk A., Tamura O., Tew W.L., Valkiers S., van Geel J., 2013, "Dependence of the Triple Point Temperature of Neon on Isotopic Composition and its Implications for the ITS-90", In: _Temperature: Its Measurement and Control in Science and Industry_, Vol. 8.

* [[[Ripple2005,1]]] Ripple D.C., Gam K.S., Hermier Y., Hill K.D., Rusby R.L., Steele A.G., Steur P.P.M., Stock M., Strouse G.F., White D.R., 2005, "Summary of Facts Relating to Isotopic Effects and the Triple Point of Water: Report of the ad hoc Task Group on the Triple Point of Water", Comité Consultatif de Thermométrie, Working Document CCT/05-07.

* [[[Steur2005,1]]] Steur P.P.M., Fellmuth B., Gam K.S., Hermier Y., Hill K.D., Pokhodun A.I., Ripple D.C., 2005, "Isotopic Effects in the Hydrogen Fixed Points: Report to the CCT", Comité Consultatif de Thermométrie, Working Document CCT/05-06.

* [[[Steur2012,1]]] Steur P.P.M., Pavese F., Fellmuth B., Hermier Y., Hill K.D., Kim J.S., Lipinski L., Nagao K., Nakano T., Peruzzi A., Sparasci F., Szmyrka-Grzebyk A., Tamura O., Tew W.L., Valkiers S., van Geel J., 2012, "Isotopic Effects in the Neon Fixed Point", Comité Consultatif de Thermométrie, Working Document CCT/12-21/rev.

* [[[White2010,1]]] White D.R., Tew W.L., 2010, _Int. J. Thermophys._, *31*, 1644-1653.

* [[[Wieser2011,1]]] Wieser M.E., Coplen T. B., 2011, _Pure Appl. Chem._, *83*, 359-396.

